FXG_PlayerBranch={}
--各分支立即建造相关数据
FXG_InstantBuild_Data=
{
	Hiigaran=
	{
		{
			Research="InstantBuild_Carrier",
			Type="Ship",
			ThingToBuild="hgn_carrier",
		},
		{
			Research="InstantBuild_Destroyer",
			Type="Ship",
			ThingToBuild="hgn_destroyer",
		},
		{
			Research="InstantBuild_CapShipProduction",
			Type="SubSystem",
			ThingToBuild="Hgn_MS_Production_CapShip",
		},
	},
	Kadesh=
	{
		{
			Research="InstantBuild_Mothership",
			Type="Ship",
			ThingToBuild="kad_mothership",
		},
		{
			Research="InstantBuild_IonCannon",
			Type="SubSystem",
			ThingToBuild="kad_m_ioncannon",
		},
		{
			Research="InstantBuild_Nagaul",
			Type="Ship",
			ThingToBuild="kad_guardianspirit",
		},
	},
	Keeper=
	{
		{
			Research="InstantBuild_Carrier",
			Type="Ship",
			ThingToBuild="kpr_carrier",
		},
		{
			Research="InstantBuild_Keeper",
			Type="Ship",
			ThingToBuild="kpr_destroyer1",
		},
		{
			Research="InstantBuild_ArsenalShip",
			Type="Ship",
			ThingToBuild="kpr_arsenalship",
		},
	},
	Taiidan=
	{
		{
			Research="InstantBuild_MissileDestroyer",
			Type="Ship",
			ThingToBuild="tai_missiledestroyer",
		},
		{
			Research="InstantBuild_ResearchStation",
			Type="Ship",
			ThingToBuild="tai_researchstation",
		},
		{
			Research="InstantBuild_Destroyer",
			Type="Ship",
			ThingToBuild="tai_destroyer",
		},
	},
	Turanic=
	{
		{
			Research="InstantBuild_CapShipProduction",
			Type="SubSystem",
			ThingToBuild="tur_as_CapShip",
		},
		{
			Research="InstantBuild_HeavyGunArray",
			Type="SubSystem",
			ThingToBuild="tur_as_HeavyGunArray",
		},
		{
			Research="InstantBuild_Carrier",
			Type="Ship",
			ThingToBuild="tur_carrier",
		},
	},
	Vaygr=
	{
		{
			Research="InstantBuild_Carrier",
			Type="Ship",
			ThingToBuild="vgr_carrier",
		},
		{
			Research="InstantBuild_CapShipProduction",
			Type="Ship",
			ThingToBuild="Vgr_MS_Production_CapShip",
		},
		{
			Research="InstantBuild_Destroyer",
			Type="Ship",
			ThingToBuild="vgr_destroyer",
		},
	},
}
--各分支初始化函数
FXG_RaceBranchFunction=
{
	Hiigaran=
	{
		function(iPlayer)
			Player_RestrictBuildOption(iPlayer,"hgn_assaultmarinefrigate")
		end
		,
		function(iPlayer)
			Player_RestrictBuildOption(iPlayer,"hgn_marinefrigate2")
		end
		,
		function(iPlayer)
			Player_RestrictBuildOption(iPlayer,"hgn_assaultmarinefrigate")
		end
		,
	},
	Kadesh=
	{
		function()
		end
		,
		function()
		end
		,
		function()
		end
		,
	},
	Keeper=
	{
		function()
		end
		,
		function()
		end
		,
		function()
		end
		,
	},
	Taiidan=
	{
		function()
		end
		,
		function()
		end
		,
		function()
		end
		,
	},
	Turanic=
	{
		function()
		end
		,
		function()
		end
		,
		function()
		end
		,
	},
	Vaygr=
	{
		function()
		end
		,
		function()
		end
		,
		function()
		end
		,
	},
}
FXG_ALLFRIGATE = 
{
	"hgn_assaultfrigate","hgn_torpedofrigate","hgn_ioncannonfrigate","hgn_marinefrigate2","hgn_assaultmarinefrigate","hgn_defensefieldfrigate",
	"vgr_assaultfrigate","vgr_heavymissilefrigate","vgr_infiltratorfrigate","vgr_EWfighter","vgr_artilleryfrigate",
	"kad_fuelpod","kad_militaryfuelpod","kad_multibeamfrigate",
	"kpr_assaultfrigate","kpr_defensefieldfrigate","kpr_ioncannonfrigate","kpr_destroyerfrigate",
	"tai_standardfrigate","tai_supportfrigate","tai_ioncannonfrigate","tai_defensefrigate",
	"tur_vulcanfrigate","tur_SiegeDrillfrigate","tur_ionarrayfrigate","tur_Energyfrigate",
}
--各分支召唤相关数据
FXG_Sumon_Data = 
{
	Hiigaran=
	{
		{
			Unit="hgn_torpedofrigate",
			NeedUnits={"hgn_carrier","hgn_mothership","hgn_shipyard"},
			Research="Sumon_TorpedoFrigate",
			Cost=660,
			UnitCap=35,
			TotalUnitCap=35,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="hgn_assaultmarinefrigate",
			NeedUnits={"hgn_carrier","hgn_mothership","hgn_shipyard"},
			Research="Sumon_MarineFrigate",
			Cost=960,
			UnitCap=6,
			TotalUnitCap=35,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="hgn_assaultfrigate",
			NeedUnits={"hgn_carrier","hgn_mothership","hgn_shipyard"},
			Research="Sumon_AssaultFrigate",
			Cost=720,
			UnitCap=35,
			TotalUnitCap=35,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
	},
	Kadesh=
	{
		{
			Unit="kad_fuelpod",
			NeedUnits={"kad_carrier","kad_mothership","kad_mothershiplight"},
			Research="Sumon_FuelPod",
			Cost=1500,
			UnitCap=4,
			TotalUnitCap=30,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="kad_militaryfuelpod",
			NeedUnits={"kad_carrier","kad_mothership","kad_mothershiplight"},
			Research="Sumon_MilitaryFuelPod",
			Cost=960,
			UnitCap=6,
			TotalUnitCap=30,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="kad_multibeamfrigate",
			NeedUnits={"kad_carrier","kad_mothership","kad_mothershiplight"},
			Research="Sumon_MultiBeamFrigate",
			Cost=840,
			UnitCap=30,
			TotalUnitCap=30,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
	},
	Keeper=
	{
		{
			Unit="kpr_assaultfrigate",
			NeedUnits={"kpr_deliver","kpr_carrier","kpr_balcoragate"},
			Research="",
			Cost=720,
			UnitCap=30,
			TotalUnitCap=30,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="kpr_destroyerfrigate",
			NeedUnits={"kpr_deliver","kpr_carrier","kpr_balcoragate"},
			Research="",
			Cost=780,
			UnitCap=30,
			TotalUnitCap=30,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="kpr_defensefieldfrigate",
			NeedUnits={"kpr_deliver","kpr_carrier","kpr_balcoragate"},
			Research="",
			Cost=960,
			UnitCap=4,
			TotalUnitCap=30,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
	},
	Taiidan=
	{
		{
			Unit="tai_standardfrigate",
			NeedUnits={"tai_carrier","tai_mothership","tai_shipyard"},
			Research="Sumon_AssaultFrigate",
			Cost=690,
			UnitCap=35,
			TotalUnitCap=35,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="tai_supportfrigate",
			NeedUnits={"tai_carrier","tai_mothership","tai_shipyard"},
			Research="Sumon_SupportFrigate",
			Cost=510,
			UnitCap=35,
			TotalUnitCap=35,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="tai_ioncannonfrigate",
			NeedUnits={"tai_carrier","tai_mothership","tai_shipyard"},
			Research="Sumon_IonCannonFrigate",
			Cost=780,
			UnitCap=35,
			TotalUnitCap=35,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
	},
	Turanic=
	{
		{
			Unit="tur_vulcanfrigate",
			NeedUnits={"tur_carrier","tur_heavycruiser","tur_shipyard"},
			Research="Sumon_VulcanFrigate",
			Cost=690,
			UnitCap=30,
			TotalUnitCap=30,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="tur_ionarrayfrigate",
			NeedUnits={"tur_carrier","tur_heavycruiser","tur_shipyard"},
			Research="Sumon_IonArrayFrigate",
			Cost=720,
			UnitCap=30,
			TotalUnitCap=30,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="tur_SiegeDrillfrigate",
			NeedUnits={"tur_carrier","tur_heavycruiser","tur_shipyard"},
			Research="Sumon_SiegeDrillFrigate",
			Cost=960,
			UnitCap=6,
			TotalUnitCap=30,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
	},
	Vaygr=
	{
		{
			Unit="vgr_assaultfrigate",
			NeedUnits={"vgr_carrier","vgr_shipyard","vgr_mothership"},
			Research="Sumon_AssaultFrigate",
			Cost=660,
			UnitCap=35,
			TotalUnitCap=35,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="vgr_infiltratorfrigate",
			NeedUnits={"vgr_carrier","vgr_shipyard","vgr_mothership"},
			Research="Sumon_InfiltratorFrigate",
			Cost=960,
			UnitCap=6,
			TotalUnitCap=35,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
		{
			Unit="vgr_heavymissilefrigate",
			NeedUnits={"vgr_carrier","vgr_shipyard","vgr_mothership"},
			Research="Sumon_HeavyMissileFrigate",
			Cost=780,
			UnitCap=35,
			TotalUnitCap=35,
			SameTypeUnits=FXG_ALLFRIGATE,
		},
	},
}