Ship = 0
SubSystem = 1
build =  { 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Swarmer", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "FighterProduction", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 2, 
        DisplayedName = "$9000", 
        Description = "$9001", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_AssaultSwarmer", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "FighterProduction", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 3, 
        DisplayedName = "$9002", 
        Description = "$9003", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_LanceSwarmer", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "FighterProduction", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 5, 
        DisplayedName = "$9004",
        Description = "$9005",
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_VariationSwarmer",
        RequiredResearch = "", 
        RequiredFleetSubSystems = "LiquidMetal",
        RequiredShipSubSystems = "", 
        DisplayPriority = 15,
        DisplayedName = "$9010",
        Description = "$9011", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_AdvancedSwarmer",
        RequiredResearch = "", 
        RequiredFleetSubSystems = "CorvetteProduction",
        RequiredShipSubSystems = "", 
        DisplayPriority = 11,
        DisplayedName = "$9006",
        Description = "$9007", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_AdvancedAssaultSwarmer", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "CorvetteProduction", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 13, 
        DisplayedName = "$9008", 
        Description = "$9009", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_FuelPod", 
        RequiredResearch = "KadCapital1", 
        RequiredFleetSubSystems = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 20, 
        DisplayedName = "$9014", 
        Description = "$9015", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_MultiBeamFrigate", 
        RequiredResearch = "KadCapital1", 
        RequiredFleetSubSystems = "CapShipProduction", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 23, 
        DisplayedName = "$9016", 
        Description = "$9017", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_MilitaryFuelPod", 
        RequiredResearch = "KadCapital2", 
        RequiredFleetSubSystems = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 25, 
        DisplayedName = "$9018", 
        Description = "$9019", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Carrier", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CapShip", 
        DisplayPriority = 30, 
        DisplayedName = "$9026", 
        Description = "$9027", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_GuardianSpirit", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "SuperSwarmer", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 31, 
        DisplayedName = "$9012", 
        Description = "$9013", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Mothership", 
        RequiredResearch = "KadCapital1", 
        RequiredFleetSubSystems = "! KadNebula", 
        DisplayPriority = 32, 
        DisplayedName = "$9020", 
        Description = "$9021", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "kad_mothershipDark", 
        RequiredResearch = "KadCapital2", 
        RequiredFleetSubSystems = "! PhasedCannon", 
        DisplayPriority = 33, 
        DisplayedName = "$9024", 
        Description = "$9025", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_MothershipLight", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "KadLight", 
        RequiredFleetSubSystems = "! KadPhasedCannon", 
        DisplayPriority = 34, 
        DisplayedName = "$9022", 
        Description = "$9023", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Araneid", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "PlatformProduction", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 41, 
        DisplayedName = "$9034", 
        Description = "$9035", 
    },
  { 
     Type = Ship, 
     ThingToBuild = "Kad_GunTurret", 
     RequiredResearch = "", 
     RequiredFleetSubSystems = "PlatformProduction", 
        RequiredShipSubSystems = "", 
     DisplayPriority = 42, 
     DisplayedName = "$9030", 
     Description = "$9031", 
  },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Salvager", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 50, 
        DisplayedName = "$9038", 
        Description = "$9039",
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Probe", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 51, 
        DisplayedName = "$9042", 
        Description = "$9043", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_ResourceFuelPod", 
        RequiredResearch = "KadCapital1", 
        RequiredFleetSubSystems = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 53, 
        DisplayedName = "$9040", 
        Description = "$9041", 
    }, 
     --{ 
        --Type = Ship, 
        --ThingToBuild = "Kad_proximitysensor", 
        --RequiredResearch = "proximitysensor", 
        --RequiredShipSubSystems = "", 
        --DisplayPriority = 55, 
        --DisplayedName = "$9044", 
        --Description = "$9045", 
    --}, 
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_M_Capship",
    	RequiredResearch = "",
    	RequiredFleetSubSystems = "CorvetteProduction",
    	DisplayPriority = 1,
    	DisplayedName = "$9050",
    	Description = "$9051",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_M_CapshipAdvanced",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "CapShip",
    	DisplayPriority = 2,
    	DisplayedName = "$9052",
    	Description = "$9053",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_M_IonCannon",
    	RequiredResearch = "KadCapital3",
    	RequiredShipSubSystems = "CapShipAdvanced",
    	DisplayPriority = 3,
    	DisplayedName = "$9070",
    	Description = "$9071",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_Fighter",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "",
    	DisplayPriority = 1,
    	DisplayedName = "$9054",
    	Description = "$9055",
    },
	--{
    --	Type = SubSystem,
    --	ThingToBuild = "Kad_C_Lance",
    --	RequiredResearch = "",
    --	RequiredShipSubSystems = "FighterProduction",
    --	DisplayPriority = 5,
    --	DisplayedName = "$9056",
    --	Description = "$9057",
    --},
    --{
    --	Type = SubSystem,
    --	ThingToBuild = "Kad_C_PlasmaBomb",
    --	RequiredResearch = "",
    --	RequiredShipSubSystems = "FighterProduction",
    --	DisplayPriority = 5,
    --	DisplayedName = "$9075",
    --	Description = "$9076",
    --},
    --{
    --	Type = SubSystem,
    --	ThingToBuild = "Kad_C_Frigate",
    --	RequiredResearch = "",
    --	RequiredShipSubSystems = "FighterProduction",
    --	DisplayPriority = 2,
    --	DisplayedName = "$9064",
    --	Description = "$9065",
    --},
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_Corvette",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "FighterProduction",
    	DisplayPriority = 2,
    	DisplayedName = "$9077",
    	Description = "$9078",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_PlatformControl",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "FighterProduction",
    	DisplayPriority = 3,
    	DisplayedName = "$9062",
    	Description = "$9063",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_LiquidMetal",
    	RequiredResearch = "",
    	RequiredFleetSubSystems = "CorvetteProduction",
    	DisplayPriority = 4,
    	DisplayedName = "$9058",
    	Description = "$9059",
    },
	{
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_Hyperspace",
    	RequiredResearch = "KadCapital1",
    	RequiredShipSubSystems = "",
    	DisplayPriority = 5,
    	DisplayedName = "$9079",
    	Description = "$9080",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_MultiBeam",
    	RequiredResearch = "KadCapital1",
    	RequiredFleetSubSystems = "",
    	DisplayPriority = 6,
    	DisplayedName = "$9066",
    	Description = "$9067",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_SuperSwarmer",
    	RequiredResearch = "KadCapital1",
    	RequiredFleetSubSystems = "",
    	DisplayPriority = 7,
    	DisplayedName = "$9083",
    	Description = "$9084",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_MultiBeam_F",
    	RequiredResearch = "KadCapital2",
    	RequiredFleetSubSystems = "",
    	DisplayPriority = 6,
    	DisplayedName = "$9066",
    	Description = "$9067",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_SuperSwarmer_F",
    	RequiredResearch = "KadCapital2",
    	RequiredFleetSubSystems = "",
    	DisplayPriority = 7,
    	DisplayedName = "$9083",
    	Description = "$9084",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_C_Cloak",
    	RequiredResearch = "KadCapital2",
    	RequiredShipSubSystems = "",
    	DisplayPriority = 8,
    	DisplayedName = "$9085",
    	Description = "$9086",
    },
    --{
    --	Type = SubSystem,
    --	ThingToBuild = "Kad_C_ClusterGun",
    --	RequiredResearch = "",
    --	RequiredShipSubSystems = "Lance",
    --	DisplayPriority = 6,
    --	DisplayedName = "$9060",
    --	Description = "$9061",
    --},
    --{
    --	Type = SubSystem,
    --	ThingToBuild = "Kad_C_Missile",
    --	RequiredResearch = "",
    --	RequiredShipSubSystems = "CorvetteProduction",
    --	DisplayPriority = 6,
    --	DisplayedName = "$9068",
    --	Description = "$9069",
    --},
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_Module_FireControl",
    	RequiredResearch = "Never",
    	RequiredShipSubSystems = "",
    	DisplayPriority = 4,
    	DisplayedName = "$9068",
    	Description = "$9069",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_Module_Key2",
    	RequiredResearch = "Never",
    	RequiredShipSubSystems = "",
    	DisplayPriority = 4,
    	DisplayedName = "$9068",
    	Description = "$9069",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "Kad_Module_Key3",
    	RequiredResearch = "Never",
    	RequiredShipSubSystems = "",
    	DisplayPriority = 4,
    	DisplayedName = "$9068",
    	Description = "$9069",
    },
}
