Ship = 0
SubSystem = 1
build = {
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_Fighter",
    --RequiredResearch = "",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 0,
    --DisplayedName = "$7000",
    --Description = "$7001",
  --},
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_Corvette",
    --RequiredResearch = "InstaFighterTech",
    --RequiredFleetSubSystems = "",
    --DisplayPriority = 0,
    --DisplayedName = "$7374",
    --Description = "$7375",
  --},
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_PlatformControl",
    --RequiredResearch = "",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 0,
    --DisplayedName = "$7389",
    --Description = "$7390",
  --},
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_ResearchArmour",
    --RequiredResearch = "",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 1,
    --DisplayedName = "$7382",
    --Description = "$7383",
  --},
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_ResearchSpeed",
    --RequiredResearch = "",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 2,
    --DisplayedName = "$7380",
    --Description = "$7381",
  --},
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AC_Frigate",
    RequiredResearch = "InstaFrigateTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 1,
    DisplayedName = "$9382",
    Description = "$9383",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AC_Weapon",
    RequiredResearch = "InstaLightWeaponTech & InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "CapShipProduction",
    DisplayPriority = 2,
    DisplayedName = "$9388",
    Description = "$9389",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AC_HeavyMissile",
    RequiredResearch = "",
    RequiredShipSubSystems = "AttackCarrierWeapon",
    RequiredFleetSubSystems = "CapShipadvanced",
    DisplayPriority = 3,
    DisplayedName = "$9371",
    Description = "$9372",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AC_Hyperspace",
    RequiredResearch = "InstaLightWeaponTech | InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 4,
    DisplayedName = "$9377",
    Description = "$9378",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AC_Repair",
    RequiredResearch = "InstaFrigateTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 5,
    DisplayedName = "$9380",
    Description = "$9381",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AC_Raid",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CapShipadvanced",
    DisplayPriority = 6,
    DisplayedName = "$9384",
    Description = "$9385",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AS_Fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$9351",
    Description = "$9352",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AS_LightWeapon",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 2,
    DisplayedName = "$9353",
    Description = "$9354",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AS_HeavyWeapon",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 3,
    DisplayedName = "$9355",
    Description = "$9356",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AS_Hyperspace",
    RequiredResearch = "InstaLightWeaponTech | InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 4,
    DisplayedName = "$9377",
    Description = "$9378",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AS_TurretArray",
    RequiredResearch = "InstaCapShipTech & InstaLightWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 5,
    DisplayedName = "$9386",
    Description = "$9387",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AS_HeavyGunArray",
    RequiredResearch = "InstaCapShipTech & InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 6,
    DisplayedName = "$9369",
    Description = "$9370",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AS_Frigate",
    RequiredResearch = "InstaFrigateTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 7,
    DisplayedName = "$9363",
    Description = "$9364",
    --DisplayPriority = 4,
    --DisplayedName = "$9361",
    --Description = "$9362",
  },
  --{
  --  Type = SubSystem,
  --  ThingToBuild = "Tur_AS_CapShip",
  --  RequiredResearch = "",
  --  RequiredFleetSubSystems = "FrigateProduction",
  --  DisplayPriority = 6,
  --  DisplayedName = "$9363",
  --  Description = "$9364",
  --},
  {
    Type = SubSystem,
    ThingToBuild = "Tur_AS_CapShipAdvanced",
    RequiredResearch = "InstaHeavyWeaponTech",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 8,
    DisplayedName = "$9373",
    Description = "$9374",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_R_turret",
    RequiredResearch = "",
    RequiredFleetSubSystems = "LightWeapon",
    DisplayPriority = 1,
    DisplayedName = "$9357",
    Description = "$9358",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_R_heavygun",
    RequiredResearch = "",
    RequiredFleetSubSystems = "HeavyWeapon",
    DisplayPriority = 2,
    DisplayedName = "$9359",
    Description = "$9360",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_R_hyperspace",
    RequiredResearch = "InstaLightWeaponTech | InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 3,
    DisplayedName = "$9377",
    Description = "$9379",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_R_CloakProduction",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 4,
    DisplayedName = "$9365",
    Description = "$9366",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_R_FrigateAdvanced",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 5,
    DisplayedName = "$9367",
    Description = "$9368",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_HC_Weapon",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CapShipadvanced | KeyToAllShips",
    DisplayPriority = 1,
    DisplayedName = "$9375",
    Description = "$9376",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tur_HC_Hyperspace",
    RequiredResearch = "InstaLightWeaponTech | InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 2,
    DisplayedName = "$9377",
    Description = "$9379",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_Scout",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 1,
    DisplayedName = "$9301",
    Description = "$9302",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_Fighter",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction | KeyToAllShips",
    RequiredShipSubSystems = "",
    DisplayPriority = 2,
    DisplayedName = "$9303",
    Description = "$9304",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_AttackBomber",
    RequiredResearch = "",
    RequiredFleetSubSystems = "(FighterProduction & HeavyWeapon) | KeyToAllShips",
    RequiredShipSubSystems = "",
    DisplayPriority = 3,
    DisplayedName = "$9305",
    Description = "$9306",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_StandardCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "(FighterProduction & LightWeapon) | KeyToAllShips",
    RequiredShipSubSystems = "",
    DisplayPriority = 10,
    DisplayedName = "$9309",
    Description = "$9310",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_MissileCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "(FighterProduction & LightWeapon) | KeyToAllShips",
    RequiredShipSubSystems = "",
    DisplayPriority = 11,
    DisplayedName = "$9311",
    Description = "$9312",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_MinelayerCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "(FighterProduction & HeavyWeapon) | KeyToAllShips",
    RequiredShipSubSystems = "",
    DisplayPriority = 12,
    DisplayedName = "$9313",
    Description = "$9314",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_TorpedoCorvette",
    RequiredResearch = "InstaFrigateadvancedTech",
    RequiredFleetSubSystems = "FighterProduction | KeyToAllShips",
    RequiredShipSubSystems = "",
    DisplayPriority = 14,
    DisplayedName = "$9307",
    Description = "$9308",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_VulcanFrigate",
    RequiredResearch = "InstaFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    RequiredFleetSubSystems = "LightWeapon | KeyToAllShips",
    DisplayPriority = 21,
    DisplayedName = "$9317",
    Description = "$9318",
  },

  {
    Type = Ship,
    ThingToBuild = "Tur_IonArrayFrigate",
    RequiredResearch = "InstaFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    RequiredFleetSubSystems = "HeavyWeapon | KeyToAllShips",
    DisplayPriority = 22,
    DisplayedName = "$9321",
    Description = "$9322",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_SiegeDrillFrigate",
    RequiredResearch = "InstaFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    RequiredFleetSubSystems = "FrigateCapture | KeyToAllShips",
    DisplayPriority = 23,
    DisplayedName = "$9319",
    Description = "$9320",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_EnergyFrigate",
    RequiredResearch = "InstaFrigateTech",
    RequiredShipSubSystems = "FrigateProduction",
    RequiredFleetSubSystems = "FrigateCapture | KeyToAllShips",
    DisplayPriority = 24,
    DisplayedName = "$9315",
    Description = "$9316",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_ResourceController",
    RequiredResearch = "InstaLightWeaponTech | InstaHeavyWeaponTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 32,
    DisplayedName = "$9327",
    Description = "$9328",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_Carrier",
    RequiredResearch = "",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 33,
    DisplayedName = "$9323",
    Description = "$9324",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_HeavyCruiser",
    RequiredResearch = "",
    RequiredShipSubSystems = "CapShipProduction & CapShipadvanced",
    DisplayPriority = 34,
    DisplayedName = "$9329",
    Description = "$9330",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_Shipyard",
    RequiredResearch = "",
    RequiredShipSubSystems = "Hyperspace | CapShipProduction", 
    DisplayPriority = 35,
    DisplayedName = "$9325",
    Description = "$9326",
  },
--{
 --Type = Ship,
 --ThingToBuild = "tur_heavygunturret",
 --RequiredResearch = "",
 --RequiredShipSubSystems = "PlatformProduction",
 --DisplayPriority = 41,
 --DisplayedName = "$9329",
 --Description = "$9330",
--},
  {
    Type = Ship,
    ThingToBuild = "Tur_CloakGenerator",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    RequiredFleetSubSystems = "Frigateadvanced",
    DisplayPriority = 30,
    DisplayedName = "$9333",
    Description = "$9334",
  },
--{
  --Type = Ship,
  --ThingToBuild = "tur_gravwellgenerator",
  --RequiredResearch = "",
  --RequiredShipSubSystems = "PlatformProduction",
  --DisplayPriority = 44,
  --DisplayedName = "$9335",
  --Description = "$9336",
--},
  {
    Type = Ship,
    ThingToBuild = "Tur_ResourceCollector",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 52,
    DisplayedName = "$9335",
    Description = "$9336",
  },
  {
    Type = Ship,
    ThingToBuild = "Tur_Garbage",
    RequiredResearch = "InstaFrigateTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 53,
    DisplayedName = "$9337",
    Description = "$9338",
  },
--{
  --Type = Ship,
  --ThingToBuild = "tur_probe",
  --RequiredResearch = "",
  --RequiredShipSubSystems = "",
  --DisplayPriority = 54,
  --DisplayedName = "$9339",
  --Description = "$9340",
--},
}
