Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research = {
----SP Tech
  {
    Name = "Tur_FateOfTheEscortFleet",
    RequiredResearch = "",
    RequiredSubSystems = "KeyToAllShips",
    Cost = 100,
    Time = 45,
    DisplayedName = "$9469",
    DisplayPriority = 100,
    Description = "$9470",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_heavycruiser",
    --UpgradeName = "WEAPONDAMAGE",
    --UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9469",
  },
  {
    Name = "Tur_DrillSpeedUpgrade",
    RequiredResearch = "Never",
    RequiredSubSystems = "",
    Cost = 100,
    Time = 45,
    DisplayedName = "$9469",
    DisplayPriority = 100,
    Description = "$9470",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_siegedrillfrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 4/3,
    Icon = Icon_Speed,
    ShortDisplayedName = "$9469",
  },
----MP Tech
  {
    Name = "InstaFighterTech",
    RequiredResearch = "",
    RequiredSubSystems = "FighterProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaCorvetteTech",
    RequiredResearch = "",
    RequiredSubSystems = "CorvetteProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaFrigateTech",
    RequiredResearch = "",
    RequiredSubSystems = "RecycleStation",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaCapShipTech",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaHeavyGunArrayTech",
    RequiredResearch = "",
    RequiredSubSystems = "HeavyGunArray | KeyToAllShips",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaLightWeaponTech",
    RequiredResearch = "",
    RequiredSubSystems = "LightWeapon",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaHeavyWeaponTech",
    RequiredResearch = "",
    RequiredSubSystems = "HeavyWeapon",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaFrigateadvancedTech",
    RequiredResearch = "",
    RequiredSubSystems = "Frigateadvanced",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "scoutCloakTech",
    RequiredResearch = "",
    RequiredSubSystems = "Frigateadvanced",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9367",
    DisplayPriority = 2,
    Description = "$9368",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "tur_scout",
    UpgradeName = "Cloak",
    Icon = Icon_Cloak,
    ShortDisplayedName = "$9405",
  },
  {
    Name = "Tur_LightWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "LightWeapon | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9471",
    DisplayPriority = 100,
    Description = "$9472",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9451",
  },
  {
    Name = "Tur_LightWeaponUpgrade2",
    RequiredResearch = "Tur_LightWeaponUpgrade1",
    RequiredSubSystems = "(LightWeapon & RecycleStation) | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9473",
    DisplayPriority = 100,
    Description = "$9474",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9452",
  },
  {
    Name = "Tur_LightWeaponUpgrade3",
    RequiredResearch = "Tur_LightWeaponUpgrade2",
    RequiredSubSystems = "(LightWeapon & CapShipadvanced) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9475",
    DisplayPriority = 100,
    Description = "$9476",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9453",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "HeavyWeapon | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9477",
    DisplayPriority = 100,
    Description = "$9478",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_torpedocorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9454",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade2",
    RequiredResearch = "Tur_HeavyWeaponUpgrade1",
    RequiredSubSystems = "(HeavyWeapon & RecycleStation) | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9479",
    DisplayPriority = 100,
    Description = "$9480",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_torpedocorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9455",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade3",
    RequiredResearch = "Tur_HeavyWeaponUpgrade2",
    RequiredSubSystems = "(HeavyWeapon & CapShipadvanced) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9481",
    DisplayPriority = 100,
    Description = "$9482",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_torpedocorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9456",
  },
  {
    Name = "Tur_CapitalWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9483",
    DisplayPriority = 300,
    Description = "$9484",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9457",
  },
  {
    Name = "Tur_CapitalWeaponUpgrade2",
    RequiredResearch = "Tur_CapitalWeaponUpgrade1",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9485",
    DisplayPriority = 300,
    Description = "$9486",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9458",
  },
  {
    Name = "Tur_CapitalWeaponUpgrade3",
    RequiredResearch = "Tur_CapitalWeaponUpgrade2",
    RequiredSubSystems = "(CapShipProduction & CapShipadvanced) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9487",
    DisplayPriority = 300,
    Description = "$9488",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9459",
  },
  {
    Name = "Tur_AirHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "FighterProduction | KeyToAllShips",
    Cost = 700,
    Time = 112,
    DisplayedName = "$9489",
    DisplayPriority = 101,
    Description = "$9490",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9460",
  },
  {
    Name = "Tur_AirHealthUpgrade2",
    RequiredResearch = "Tur_AirHealthUpgrade1",
    RequiredSubSystems = "RecycleStation | KeyToAllShips",
    Cost = 1050,
    Time = 140,
    DisplayedName = "$9491",
    DisplayPriority = 101,
    Description = "$9492",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9461",
  },
  {
    Name = "Tur_AirHealthUpgrade3",
    RequiredResearch = "Tur_AirHealthUpgrade2",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 1400,
    Time = 168,
    DisplayedName = "$9493",
    DisplayPriority = 101,
    Description = "$9494",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9462",
  },
  {
    Name = "Tur_FrigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "RecycleStation | KeyToAllShips",
    Cost = 1000,
    Time = 160,
    DisplayedName = "$9495",
    DisplayPriority = 201,
    Description = "$9496",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9463",
  },
  {
    Name = "Tur_FrigateHealthUpgrade2",
    RequiredResearch = "Tur_FrigateHealthUpgrade1",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 1500,
    Time = 200,
    DisplayedName = "$9497",
    DisplayPriority = 201,
    Description = "$9498",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$9464",
  },
  {
    Name = "Tur_FrigateHealthUpgrade3",
    RequiredResearch = "Tur_FrigateHealthUpgrade2",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 2000,
    Time = 240,
    DisplayedName = "$9499",
    DisplayPriority = 201,
    Description = "$9500",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$9465",
  },
  {
    Name = "Tur_UtilityHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 400,
    Time = 64,
    DisplayedName = "$9501",
    DisplayPriority = 201,
    Description = "$9502",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Utility",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9466",
  },
  {
    Name = "Tur_UtilityHealthUpgrade2",
    RequiredResearch = "Tur_UtilityHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 600,
    Time = 80,
    DisplayedName = "$9503",
    DisplayPriority = 201,
    Description = "$9504",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Utility",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$9467",
  },
  {
    Name = "Tur_UtilityHealthUpgrade3",
    RequiredResearch = "Tur_UtilityHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 800,
    Time = 96,
    DisplayedName = "$9505",
    DisplayPriority = 201,
    Description = "$9506",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Utility",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$9468",
  },
-----------------------------------------------------------------
-----------------------------------------------------------------
  {
    Name = "Tur_LightWeaponUpgrade1_1",
    RequiredResearch = "Tur_LightWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9471",
    DisplayPriority = 100,
    Description = "$9472",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9451",
  },
  {
    Name = "Tur_LightWeaponUpgrade2_1",
    RequiredResearch = "Tur_LightWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9473",
    DisplayPriority = 100,
    Description = "$9474",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9452",
  },
  {
    Name = "Tur_LightWeaponUpgrade3_1",
    RequiredResearch = "Tur_LightWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9475",
    DisplayPriority = 100,
    Description = "$9476",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9453",
  },
  {
    Name = "Tur_LightWeaponUpgrade1_2",
    RequiredResearch = "Tur_LightWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9471",
    DisplayPriority = 100,
    Description = "$9472",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_standardcorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9451",
  },
  {
    Name = "Tur_LightWeaponUpgrade2_2",
    RequiredResearch = "Tur_LightWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9473",
    DisplayPriority = 100,
    Description = "$9474",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_standardcorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9452",
  },
  {
    Name = "Tur_LightWeaponUpgrade3_2",
    RequiredResearch = "Tur_LightWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9475",
    DisplayPriority = 100,
    Description = "$9476",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_standardcorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9453",
  },
  {
    Name = "Tur_LightWeaponUpgrade1_3",
    RequiredResearch = "Tur_LightWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9471",
    DisplayPriority = 100,
    Description = "$9472",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_vulcanfrigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9451",
  },
  {
    Name = "Tur_LightWeaponUpgrade2_3",
    RequiredResearch = "Tur_LightWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9473",
    DisplayPriority = 100,
    Description = "$9474",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_vulcanfrigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9452",
  },
  {
    Name = "Tur_LightWeaponUpgrade3_3",
    RequiredResearch = "Tur_LightWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9475",
    DisplayPriority = 100,
    Description = "$9476",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_vulcanfrigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9453",
  },
  {
    Name = "Tur_LightWeaponUpgrade1_4",
    RequiredResearch = "Tur_LightWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9471",
    DisplayPriority = 100,
    Description = "$9472",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_missilecorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9451",
  },
  {
    Name = "Tur_LightWeaponUpgrade2_4",
    RequiredResearch = "Tur_LightWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9473",
    DisplayPriority = 100,
    Description = "$9474",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_missilecorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9452",
  },
  {
    Name = "Tur_LightWeaponUpgrade3_4",
    RequiredResearch = "Tur_LightWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9475",
    DisplayPriority = 100,
    Description = "$9476",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_missilecorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9453",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade1_1",
    RequiredResearch = "Tur_HeavyWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9477",
    DisplayPriority = 100,
    Description = "$9478",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_minelayercorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9454",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade2_1",
    RequiredResearch = "Tur_HeavyWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9479",
    DisplayPriority = 100,
    Description = "$9480",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_minelayercorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9455",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade3_1",
    RequiredResearch = "Tur_HeavyWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9481",
    DisplayPriority = 100,
    Description = "$9482",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_minelayercorvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9456",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade1_2",
    RequiredResearch = "Tur_HeavyWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9477",
    DisplayPriority = 100,
    Description = "$9478",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_attackbomber",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9454",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade2_2",
    RequiredResearch = "Tur_HeavyWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9479",
    DisplayPriority = 100,
    Description = "$9480",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_attackbomber",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9455",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade3_2",
    RequiredResearch = "Tur_HeavyWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9481",
    DisplayPriority = 100,
    Description = "$9482",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_attackbomber",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9456",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade1_3",
    RequiredResearch = "Tur_HeavyWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9477",
    DisplayPriority = 100,
    Description = "$9478",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_ionarrayfrigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9454",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade2_3",
    RequiredResearch = "Tur_HeavyWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9479",
    DisplayPriority = 100,
    Description = "$9480",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_ionarrayfrigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9455",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade3_3",
    RequiredResearch = "Tur_HeavyWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9481",
    DisplayPriority = 100,
    Description = "$9482",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_ionarrayfrigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9456",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade1_4",
    RequiredResearch = "Tur_HeavyWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9477",
    DisplayPriority = 100,
    Description = "$9478",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_SiegeDrillfrigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9454",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade2_4",
    RequiredResearch = "Tur_HeavyWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9479",
    DisplayPriority = 100,
    Description = "$9480",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_SiegeDrillfrigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9455",
  },
  {
    Name = "Tur_HeavyWeaponUpgrade3_4",
    RequiredResearch = "Tur_HeavyWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9481",
    DisplayPriority = 100,
    Description = "$9482",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_SiegeDrillfrigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9456",
  },
  {
    Name = "Tur_CapitalWeaponUpgrade1_1",
    RequiredResearch = "Tur_CapitalWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9483",
    DisplayPriority = 300,
    Description = "$9484",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9457",
  },
  {
    Name = "Tur_CapitalWeaponUpgrade2_1",
    RequiredResearch = "Tur_CapitalWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9485",
    DisplayPriority = 300,
    Description = "$9486",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9458",
  },
  {
    Name = "Tur_CapitalWeaponUpgrade3_1",
    RequiredResearch = "Tur_CapitalWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9487",
    DisplayPriority = 300,
    Description = "$9488",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9459",
  },
  {
    Name = "Tur_AirHealthUpgrade1_1",
    RequiredResearch = "Tur_AirHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9489",
    DisplayPriority = 101,
    Description = "$9490",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9460",
  },
  {
    Name = "Tur_AirHealthUpgrade2_1",
    RequiredResearch = "Tur_AirHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9491",
    DisplayPriority = 101,
    Description = "$9492",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9461",
  },
  {
    Name = "Tur_AirHealthUpgrade3_1",
    RequiredResearch = "Tur_AirHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9493",
    DisplayPriority = 101,
    Description = "$9494",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9462",
  },
  {
    Name = "Tur_FrigateHealthUpgrade1_1",
    RequiredResearch = "Tur_FrigateHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9495",
    DisplayPriority = 201,
    Description = "$9496",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9463",
  },
  {
    Name = "Tur_FrigateHealthUpgrade2_1",
    RequiredResearch = "Tur_FrigateHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9497",
    DisplayPriority = 201,
    Description = "$9498",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9464",
  },
  {
    Name = "Tur_FrigateHealthUpgrade3_1",
    RequiredResearch = "Tur_FrigateHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9499",
    DisplayPriority = 201,
    Description = "$9500",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9465",
  },
  {
    Name = "Tur_UtilityHealthUpgrade1_1",
    RequiredResearch = "Tur_UtilityHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9501",
    DisplayPriority = 201,
    Description = "$9502",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_resourcecontroller",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9466",
  },
  {
    Name = "Tur_UtilityHealthUpgrade2_1",
    RequiredResearch = "Tur_UtilityHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9503",
    DisplayPriority = 201,
    Description = "$9504",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_resourcecontroller",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$9467",
  },
  {
    Name = "Tur_UtilityHealthUpgrade3_1",
    RequiredResearch = "Tur_UtilityHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9505",
    DisplayPriority = 201,
    Description = "$9506",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_resourcecontroller",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$9468",
  },
  {
    Name = "Tur_UtilityHealthUpgrade1_2",
    RequiredResearch = "Tur_UtilityHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9501",
    DisplayPriority = 201,
    Description = "$9502",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_cloakgenerator",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9466",
  },
  {
    Name = "Tur_UtilityHealthUpgrade2_2",
    RequiredResearch = "Tur_UtilityHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9503",
    DisplayPriority = 201,
    Description = "$9504",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_cloakgenerator",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$9467",
  },
  {
    Name = "Tur_UtilityHealthUpgrade3_3",
    RequiredResearch = "Tur_UtilityHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9505",
    DisplayPriority = 201,
    Description = "$9506",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_cloakgenerator",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$9468",
  },
  {
    Name = "Tur_UtilityHealthUpgrade1_3",
    RequiredResearch = "Tur_UtilityHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9501",
    DisplayPriority = 201,
    Description = "$9502",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_shipyard",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9466",
  },
  {
    Name = "Tur_UtilityHealthUpgrade2_3",
    RequiredResearch = "Tur_UtilityHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9503",
    DisplayPriority = 201,
    Description = "$9504",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_shipyard",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$9467",
  },
  {
    Name = "Tur_UtilityHealthUpgrade3_3",
    RequiredResearch = "Tur_UtilityHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9505",
    DisplayPriority = 201,
    Description = "$9506",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_shipyard",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$9468",
  },
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")