Number_Properties_Priority = 2.0

Number_Properties = {
	dm_challenge_research_baseline = 0,
}

String_Properties_Priority = 2.0

String_Properties = {
	dm_carriersonly_build_restrict = "",
	dm_carriersonly_research_restrict = "",
	generic_mp_build_restrict = "Vgr_Mothership,Vgr_PlanetKillerMissile,Vgr_CommandCorvette,Vgr_MinelayerCorvette,Vgr_Probe,Vgr_Probe_ECM,Vgr_WeaponPlatform_gun,Vgr_C_Module_PlatformControl,Vgr_MS_Module_PlatformControl,Vgr_C_Module_CloakGenerator,Vgr_MS_Module_CloakGenerator,Vgr_C_Module_HyperspaceInhibitor,Vgr_MS_Module_HyperspaceInhibitor,Vgr_C_Module_FireControl,Vgr_MS_Module_FireControl,Vgr_C_Sensors_AdvancedArray,Vgr_MS_Sensors_AdvancedArray,Vgr_C_Sensors_DetectHyperspace,Vgr_MS_Sensors_DetectHyperspace",
	generic_mp_research_restrict = "PlasmaBombs,LanceBeams,CorvetteLaser,CorvetteCommand,EWfighterTech,FrigateAssault,FrigateInfiltrationTech,BattlecruiserIonWeapons,DestroyerGuns,HyperspaceGateTech,PlatformHeavyMissiles,ScoutEMPAbility,WeakVgrHeavyMissiles,HyperspaceRecoveryTimeUpgradeSPGAME,HyperspaceTransitionTimeUpgradeSPGAME,VaygrCarrierHealthRegenDowngrade,ShipyardSpeedDowngradeSPGAME,SuperCapHealthUpgradeSPGAME,VaygrFrigateHealthUpgradeSPGAME,VaygrFrigateHealthRegenDowngradeSPGAME,CorvetteHealthUpgradeSPGAME,ExtraStrongVgrHeavyMissilesSPGAME,VaygrCaptureHack,VaygrReduceCaptureHack,VaygrRadiationImmunityHack,VaygrCarrierHealthUpgrade,CorvetteGraviticAttraction,ProbeProxSensor,ProbeSensorDisruption,vgrBUILDSPEEDUpgrade1,vgrBUILDSPEEDUpgrade2,CorvetteHealthUpgrade1,CorvetteHealthUpgrade2,CorvetteSpeedUpgrade1,CorvetteSpeedUpgrade2,FrigateHealthUpgrade1,FrigateHealthUpgrade2,FrigateSpeedUpgrade1,SpeedUpgrade2,SuperCapHealthUpgrade1,SuperCapHealthUpgrade2,SuperCapSpeedUpgrade1,SuperCapSpeedUpgrade2,PlatformHealthUpgrade1,PlatformHealthUpgrade2,UtilityHealthUpgrade1,UtilityHealthUpgrade2",
	generic_sp_build_restrict = "",
	generic_sp_research_restrict = "cpuplayers_defensive,cpuplayers_aggressive,cpuplayers_dynamic,cpuplayers_norushtime5,cpuplayers_norushtime10,cpuplayers_norushtime15,AllShipBuildSpeed,AllShipBuildSpeedHard,AllShipBuildSpeedExpert,ResourceCollectionRateHard,ResourceCollectionRateExpert",
}
