Ship = 0
SubSystem = 1
build = {
{
    Type = SubSystem,
    ThingToBuild = "ben_module_repair",
    RequiredResearch = "",
    RequiredFleetSubSystems = "SleeplessCity2|SleeplessCity3",
    DisplayPriority = 10,
    DisplayedName = "$11157",
    Description = "$11158",
  },
{
    Type = SubSystem,
    ThingToBuild = "ben_module_ionbeam",
    RequiredResearch = "",
    RequiredFleetSubSystems = "SleeplessCity3",
    DisplayPriority = 20,
    DisplayedName = "$11159",
    Description = "$11160",
  },
{
    Type = SubSystem,
    ThingToBuild = "ben_module_sleeplesscity1",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 10,
    DisplayedName = "$11151",
    Description = "$11152",
  },
{
    Type = SubSystem,
    ThingToBuild = "ben_module_sleeplesscity2",
    RequiredResearch = "SleeplessCityLv1",
    RequiredShipSubSystems = "",
    DisplayPriority = 20,
    DisplayedName = "$11153",
    Description = "$11154",
  },
{
    Type = SubSystem,
    ThingToBuild = "ben_module_sleeplesscity3",
    RequiredResearch = "SleeplessCityLv2",
    RequiredShipSubSystems = "",
    DisplayPriority = 30,
    DisplayedName = "$11155",
    Description = "$11156",
  },
{
    Type = Ship,
    ThingToBuild = "ben_fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 20,
    DisplayedName = "$11100",
    Description = "$11101",
  },
{
    Type = Ship,
    ThingToBuild = "ben_corvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "SleeplessCity2|SleeplessCity3",
    DisplayPriority = 20,
    DisplayedName = "$11114",
    Description = "$11115",
  },
{
    Type = Ship,
    ThingToBuild = "Ben_cloakfieldplatform",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity2|SleeplessCity3",
    DisplayPriority = 10,
    DisplayedName = "$11122",
    Description = "$11123",
  },
{
    Type = Ship,
    ThingToBuild = "Ben_defensefieldplatform",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity2|SleeplessCity3",
    DisplayPriority = 20,
    DisplayedName = "$11124",
    Description = "$11125",
  },
{
    Type = Ship,
    ThingToBuild = "Ben_jamfieldplatform",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity2|SleeplessCity3",
    DisplayPriority = 30,
    DisplayedName = "$11126",
    Description = "$11127",
  },
{
    Type = Ship,
    ThingToBuild = "Ben_jumpfieldplatform",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity3",
    DisplayPriority = 40,
    DisplayedName = "$11128",
    Description = "$11129",
  },
{
    Type = Ship,
    ThingToBuild = "Ben_gravityfieldplatform",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity3",
    DisplayPriority = 50,
    DisplayedName = "$11130",
    Description = "$11131",
  },
{
    Type = Ship,
    ThingToBuild = "Ben_pulsarfrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity1|SleeplessCity2|SleeplessCity3",
    DisplayPriority = 20,
    DisplayedName = "$11116",
    Description = "$11117",
  },
{
    Type = Ship,
    ThingToBuild = "Ben_ioncannonfrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity2|SleeplessCity3",
    DisplayPriority = 30,
    DisplayedName = "$11110",
    Description = "$11111",
  },
{
    Type = Ship,
    ThingToBuild = "Ben_controlfrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity3",
    DisplayPriority = 40,
    DisplayedName = "$11118",
    Description = "$11119",
  },
{
    Type = Ship,
    ThingToBuild = "ben_destroyer",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity2|SleeplessCity3",
    DisplayPriority = 40,
    DisplayedName = "$11112",
    Description = "$11113",
  },
{
    Type = Ship,
    ThingToBuild = "ben_floatingcity",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity1|SleeplessCity2|SleeplessCity3",
    DisplayPriority = 50,
    DisplayedName = "$11102",
    Description = "$11103",
  },
  --{
    --Type = Ship,
    --ThingToBuild = "ben_flattop",
    --RequiredResearch = "dacolyteTech",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 60,
    --DisplayedName = "$11104",
    --Description = "$11105",
  --},
{
    Type = Ship,
    ThingToBuild = "Ben_Battleship",
    RequiredResearch = "",
    RequiredShipSubSystems = "SleeplessCity3",
    DisplayPriority = 70,
    DisplayedName = "$11106",
    Description = "$11107",
  },
{
    Type = Ship,
    ThingToBuild = "ben_cargobarge",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 40,
    DisplayedName = "$11108",
    Description = "$11109",
  },
{
    Type = Ship,
    ThingToBuild = "ben_resourcecollector",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 80,
    DisplayedName = "$11120",
    Description = "$11121",
  },
{
    Type = Ship,
    ThingToBuild = "ben_probe",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 90,
    DisplayedName = "$11161",
    Description = "$11162",
  },
--{
    --Type = Ship,
    --ThingToBuild = "ben_resourcecollector",
    --RequiredResearch = "",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 80,
    --DisplayedName = "$11108",
    --Description = "$11109",
--},
}
