Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research = {
	{ 
		Name = "SleeplessCityLv1", 
		RequiredResearch = "", 
		RequiredSubSystems = "SleeplessCity1", 
		Cost = 0, 
		Time = 0, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "SleeplessCityLv2", 
		RequiredResearch = "", 
		RequiredSubSystems = "SleeplessCity2", 
		Cost = 0, 
		Time = 0, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "SleeplessCityLv3", 
		RequiredResearch = "", 
		RequiredSubSystems = "SleeplessCity3", 
		Cost = 0, 
		Time = 0, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "HasSleeplessCityLv1", 
		RequiredResearch = "", 
		RequiredSubSystems = "SleeplessCity1", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "HasSleeplessCityLv2", 
		RequiredResearch = "", 
		RequiredSubSystems = "SleeplessCity2", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "HasSleeplessCityLv3", 
		RequiredResearch = "", 
		RequiredSubSystems = "SleeplessCity3", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
  {
    Name = "BenHarvestUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "SleeplessCity1 | SleeplessCity2 | SleeplessCity3",
    Cost = 1000,
    Time = 30,
    DisplayedName = "$11214",
    DisplayPriority = 10,
    Description = "$11215",
    TargetType = Ship,
    TargetName = "ben_cargobarge",
    Icon = Icon_RU,
    ShortDisplayedName = "$11214",
  },
  {
    Name = "BenHarvestUpgrade2",
    RequiredResearch = "BenHarvestUpgrade1",
    RequiredSubSystems = "SleeplessCity2 | SleeplessCity3",
    Cost = 2000,
    Time = 60,
    DisplayedName = "$11216",
    DisplayPriority = 20,
    Description = "$11217",
    TargetType = Ship,
    TargetName = "ben_cargobarge",
    Icon = Icon_RU,
    ShortDisplayedName = "$11216",
  },
  {
    Name = "BenSpeedUpgrade",
    RequiredResearch = "",
    RequiredSubSystems = "SleeplessCity3",
    Cost = 10000,
    Time = 600,
    DisplayedName = "$11218",
    DisplayPriority = 10,
    Description = "$11219",
    TargetType = ship,
    TargetName = "ben_bentus",
    UpgradeType = Ability,
    UpgradeName = "Move",
    Icon = Icon_Speed,
    ShortDisplayedName = "$11218",
  },
  {
    Name = "BenSpeedUpgrade_Battleship",
    RequiredResearch = "BenSpeedUpgrade",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    TargetType = Ship,
    TargetName = "Ben_Battleship",
    UpgradeType = Modifier,
    UpgradeName = "MAXSPEED",
    UpgradeValue = 4,
  },
  {
    Name = "BenSpeedUpgrade_floatingcity",
    RequiredResearch = "BenSpeedUpgrade",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    TargetType = Ship,
    TargetName = "ben_floatingcity",
    UpgradeType = Modifier,
    UpgradeName = "MAXSPEED",
    UpgradeValue = 4,
  },
  {
    Name = "BenSpeedUpgrade_pulsarfrigate",
    RequiredResearch = "BenSpeedUpgrade",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    TargetType = Ship,
    TargetName = "Ben_pulsarfrigate",
    UpgradeType = Modifier,
    UpgradeName = "MAXSPEED",
    UpgradeValue = 3,
  },
  {
    Name = "BenSpeedUpgrade_ioncannonfrigate",
    RequiredResearch = "BenSpeedUpgrade",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    TargetType = Ship,
    TargetName = "Ben_ioncannonfrigate",
    UpgradeType = Modifier,
    UpgradeName = "MAXSPEED",
    UpgradeValue = 3,
  },
  {
    Name = "BenSpeedUpgrade_controlfrigate",
    RequiredResearch = "BenSpeedUpgrade",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    TargetType = Ship,
    TargetName = "Ben_controlfrigate",
    UpgradeType = Modifier,
    UpgradeName = "MAXSPEED",
    UpgradeValue = 3,
  },
  {
    Name = "BenSpeedUpgrade_destroyer",
    RequiredResearch = "BenSpeedUpgrade",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    TargetType = Ship,
    TargetName = "ben_destroyer",
    UpgradeType = Modifier,
    UpgradeName = "MAXSPEED",
    UpgradeValue = 4,
  },
--AI behaviour	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed	
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.025,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.05,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.075,
	},
--AI resource rate	
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},			
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")