Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "HyperspaceCostUpgrade",
    RequiredResearch = "SPOnly",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    TargetType = Ship,
    UpgradeName = "HyperspaceCost",
    UpgradeValue = 0.0,
    TargetName = "Kad_Mothership",
  },
  {
    Name = "Kad_SupportPodHealthUpgrade",
    RequiredResearch = "SPOnly",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kad_FuelPod",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2.25,
  },
  {
    Name = "Kad_NebulaHealthUpgrade",
    RequiredResearch = "SPOnly",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kad_Mothership",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.5,
  },
  {
    Name = "KadCapital1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShip",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8320",
    DisplayPriority = 1,
    Description = "$8321",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Kad_Mothership",
    UpgradeName = "Hyperspace",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8376",
  },
  --{
  --  Name = "carrierHyperspace",
  --  RequiredResearch = "KadCapital1",
  --  RequiredSubSystems = "",
  --  Cost = 0,
  --  Time = 0,
  --  DisplayedName = "$8320",
  --  DisplayPriority = 1,
  --  Description = "$8321",
  --  UpgradeType = Ability,
  --  TargetType = Ships,
  --  UpgradeName = "HyperSpace",
  --  TargetName = "kad_carrier",
  --  Icon = Icon_Hyperspace,
  --  ShortDisplayedName = "$8376",
  --},
  {
    Name = "KadCapital2",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipAdvanced",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8320",
    DisplayPriority = 1,
    Description = "$8321",
    TargetType = Family,
    TargetName = "Capital",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8376",
  },
  --{
  -- Name = "carrierCloakTech",
  --  RequiredResearch = "KadCapital2",
  --  RequiredSubSystems = "",
  --  Cost = 0,
  --  Time = 0,
  --  DisplayedName = "$9367",
  --  DisplayPriority = 2,
  --  Description = "$9368",
  --  UpgradeType = Ability,
  --  TargetType = Ship,
  --  TargetName = "kad_carrier",
  --  UpgradeName = "Cloak",
  --  Icon = Icon_Cloak,
  --  ShortDisplayedName = "$9405",
  --},
  --{
  --  Name = "AdvancedAssaultSwarmerMissile",
  --  RequiredResearch = "",
  --  RequiredSubSystems = "Missile",
  --  Cost = 0,
  --  Time = 0,
  --  DisplayedName = "$9056",
  --  DisplayPriority = 3,
  --  Description = "$9057",
  --  UpgradeType = Ability,
  --  TargetType = Ship,
  --  TargetName = "Kad_AdvancedAssaultSwarmer",
  --  UpgradeName = "UseSpecialWeaponsInNormalAttack",
  --  Icon = Icon_crystal,
  --  ShortDisplayedName = "$9093",
  --},
  {
    Name = "Kad_FighterWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "FighterProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9150",
    DisplayPriority = 100,
    Description = "$9151",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9110",
  },
  {
    Name = "Kad_FighterWeaponUpgrade2",
    RequiredResearch = "Kad_FighterWeaponUpgrade1",
    RequiredSubSystems = "FighterProduction & CapShip",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9152",
    DisplayPriority = 100,
    Description = "$9153",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9111",
  },
  {
    Name = "Kad_FighterWeaponUpgrade3",
    RequiredResearch = "Kad_FighterWeaponUpgrade2",
    RequiredSubSystems = "FighterProduction & CapShipAdvanced",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9154",
    DisplayPriority = 100,
    Description = "$9155",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9112",
  },
  {
    Name = "Kad_CorvetteWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CorvetteProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9156",
    DisplayPriority = 100,
    Description = "$9157",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9113",
  },
  {
    Name = "Kad_CorvetteWeaponUpgrade2",
    RequiredResearch = "Kad_CorvetteWeaponUpgrade1",
    RequiredSubSystems = "CorvetteProduction & CapShip",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9158",
    DisplayPriority = 100,
    Description = "$9159",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9114",
  },
  {
    Name = "Kad_CorvetteWeaponUpgrade3",
    RequiredResearch = "Kad_CorvetteWeaponUpgrade2",
    RequiredSubSystems = "CorvetteProduction & CapShipAdvanced",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9160",
    DisplayPriority = 100,
    Description = "$9161",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9115",
  },
  {
    Name = "Kad_AirHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CorvetteProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9162",
    DisplayPriority = 101,
    Description = "$9163",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9116",
  },
  {
    Name = "Kad_AirHealthUpgrade2",
    RequiredResearch = "Kad_AirHealthUpgrade1",
    RequiredSubSystems = "CorvetteProduction & CapShip",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9164",
    DisplayPriority = 101,
    Description = "$9165",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9117",
  },
  {
    Name = "Kad_AirHealthUpgrade3",
    RequiredResearch = "Kad_AirHealthUpgrade2",
    RequiredSubSystems = "CorvetteProduction & CapShipAdvanced",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9166",
    DisplayPriority = 101,
    Description = "$9167",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9118",
  },
  {
    Name = "Kad_ShipWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShip",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9168",
    DisplayPriority = 200,
    Description = "$9169",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.12,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9119",
  },
  {
    Name = "Kad_ShipWeaponUpgrade2",
    RequiredResearch = "Kad_ShipWeaponUpgrade1",
    RequiredSubSystems = "CapShipProduction & CapShip",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9170",
    DisplayPriority = 200,
    Description = "$9171",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.24,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9120",
  },
  {
    Name = "Kad_ShipWeaponUpgrade3",
    RequiredResearch = "Kad_ShipWeaponUpgrade2",
    RequiredSubSystems = "CapShipProduction & CapShipAdvanced",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9172",
    DisplayPriority = 200,
    Description = "$9173",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.36,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9121",
  },
  {
    Name = "Kad_ShipHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShip",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9174",
    DisplayPriority = 201,
    Description = "$9175",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9119",
  },
  {
    Name = "Kad_ShipHealthUpgrade2",
    RequiredResearch = "Kad_ShipHealthUpgrade1",
    RequiredSubSystems = "CapShipAdvanced",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9176",
    DisplayPriority = 201,
    Description = "$9177",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$9120",
  },
  {
    Name = "Kad_ShipHealthUpgrade3",
    RequiredResearch = "Kad_ShipHealthUpgrade2",
    RequiredSubSystems = "CapShipAdvanced",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9178",
    DisplayPriority = 201,
    Description = "$9179",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$9121",
  },
  {
    Name = "Kad_PlatformHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "PlatformProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9180",
    DisplayPriority = 201,
    Description = "$9181",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9122",
  },
  {
    Name = "Kad_PlatformHealthUpgrade2",
    RequiredResearch = "Kad_PlatformHealthUpgrade1",
    RequiredSubSystems = "PlatformProduction & CapShip",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9182",
    DisplayPriority = 201,
    Description = "$9183",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$9123",
  },
  {
    Name = "Kad_PlatformHealthUpgrade3",
    RequiredResearch = "Kad_PlatformHealthUpgrade2",
    RequiredSubSystems = "PlatformProduction & CapShipAdvanced",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9184",
    DisplayPriority = 201,
    Description = "$9185",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$9124",
  },
----------------------------------------------------------------------
----------------------------------------------------------------------
  {
    Name = "Kad_AirHealthUpgrade1_1",
    RequiredResearch = "Kad_AirHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9162",
    DisplayPriority = 101,
    Description = "$9163",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9116",
  },
  {
    Name = "Kad_AirHealthUpgrade2_1",
    RequiredResearch = "Kad_AirHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9162",
    DisplayPriority = 101,
    Description = "$9163",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9116",
  },
  {
    Name = "Kad_AirHealthUpgrade3_1",
    RequiredResearch = "Kad_AirHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9162",
    DisplayPriority = 101,
    Description = "$9163",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9116",
  },
  {
    Name = "Kad_ShipWeaponUpgrade1_1",
    RequiredResearch = "Kad_ShipWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9168",
    DisplayPriority = 200,
    Description = "$9169",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9119",
  },
  {
    Name = "Kad_ShipWeaponUpgrade2_1",
    RequiredResearch = "Kad_ShipWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9168",
    DisplayPriority = 200,
    Description = "$9169",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9119",
  },
  {
    Name = "Kad_ShipWeaponUpgrade3_1",
    RequiredResearch = "Kad_ShipWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9168",
    DisplayPriority = 200,
    Description = "$9169",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9119",
  },
  {
    Name = "Kad_ShipHealthUpgrade1_1",
    RequiredResearch = "Kad_ShipHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9174",
    DisplayPriority = 201,
    Description = "$9175",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9119",
  },
  {
    Name = "Kad_ShipHealthUpgrade2_1",
    RequiredResearch = "Kad_ShipHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9174",
    DisplayPriority = 201,
    Description = "$9175",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.35,
    Icon = Icon_Health,
    ShortDisplayedName = "$9119",
  },
  {
    Name = "Kad_ShipHealthUpgrade3_1",
    RequiredResearch = "Kad_ShipHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9174",
    DisplayPriority = 201,
    Description = "$9175",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.5,
    Icon = Icon_Health,
    ShortDisplayedName = "$9119",
  },
--AI behaviour	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed	
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.025,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.05,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.075,
	},
--AI resource rate	
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},			
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")