Ship = 0
SubSystem = 1
build = {
  {
    Type = Ship,
    ThingToBuild = "Vgr_Scout",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 20,
    DisplayedName = "$7130",
    Description = "$7131",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Interceptor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 21,
    DisplayedName = "$7132",
    Description = "$7133",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Bomber",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    --RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 22,
    DisplayedName = "$7134",
    Description = "$7135",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_LanceFighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    --RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 24,
    DisplayedName = "$7136",
    Description = "$7137",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_MissileCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 160,
    DisplayedName = "$7138",
    Description = "$7139",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_LaserCorvette",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    --RequiredFleetSubSystems = "CorvetteProduction",
    DisplayPriority = 161,
    DisplayedName = "$7140",
    Description = "$7141",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_CommandCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 162,
    DisplayedName = "$7144",
    Description = "$7145",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_MinelayerCorvette",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 163,
    DisplayedName = "$7142",
    Description = "$7143",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_AssaultFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 200,
    DisplayedName = "$7146",
    Description = "$7147",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_HeavyMissileFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 210,
    DisplayedName = "$7148",
    Description = "$7149",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_InfiltratorFrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    --RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 240,
    DisplayedName = "$7150",
    Description = "$7151",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Carrier",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 250,
    DisplayedName = "$7154",
    Description = "$7155",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_ShipYard",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 260,
    DisplayedName = "$7156",
    Description = "$7157",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Destroyer",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 265,
    DisplayedName = "$7152",
    Description = "$7153",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_BattleCruiser",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 280,
    DisplayedName = "$7158",
    Description = "$7159",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_WeaponPlatform_gun",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 300,
    DisplayedName = "$7160",
    Description = "$7161",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_WeaponPlatform_missile",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 310,
    DisplayedName = "$7162",
    Description = "$7163",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_ResourceCollector",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 320,
    DisplayedName = "$7164",
    Description = "$7165",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_ResourceController",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 330,
    DisplayedName = "$7166",
    Description = "$7167",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_HyperSpace_Platform",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 340,
    DisplayedName = "$7174",
    Description = "$7175",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Probe",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 350,
    DisplayedName = "$7168",
    Description = "$7169",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Probe_Prox",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 360,
    DisplayedName = "$7170",
    Description = "$7171",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Probe_ECM",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 370,
    DisplayedName = "$7172",
    Description = "$7173",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_PlanetKillerMissile",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 380,
    DisplayedName = "Honking big planet killing missile",
    Description = "",
  },
}
