Ship = 0
SubSystem = 1
build = {
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_Fighter",
    --RequiredResearch = "",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 0,
    --DisplayedName = "$7000",
    --Description = "$7001",
  --},
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_Corvette",
    --RequiredResearch = "InstaFighterTech",
    --RequiredFleetSubSystems = "",
    --DisplayPriority = 0,
    --DisplayedName = "$7374",
    --Description = "$7375",
  --},
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_PlatformControl",
    --RequiredResearch = "",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 0,
    --DisplayedName = "$7389",
    --Description = "$7390",
  --},
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_ResearchArmour",
    --RequiredResearch = "",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 1,
    --DisplayedName = "$7382",
    --Description = "$7383",
  --},
  --{
    --Type = SubSystem,
    --ThingToBuild = "tur_ac_ResearchSpeed",
    --RequiredResearch = "",
    --RequiredShipSubSystems = "",
    --DisplayPriority = 2,
    --DisplayedName = "$7380",
    --Description = "$7381",
  --},
  {
    Type = SubSystem,
    ThingToBuild = "tur_ac_Frigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "LightWeapon | HeavyWeapon",
    DisplayPriority = 1,
    DisplayedName = "$9361",
    Description = "$9362",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_ac_heavymissile",
    RequiredResearch = "InstaHeavyGunArrayTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 2,
    DisplayedName = "$9371",
    Description = "$9372",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_ac_hyperspace",
    RequiredResearch = "InstaLightWeaponTech | InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 3,
    DisplayedName = "$9377",
    Description = "$9378",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_as_HeavyGunArray",
    RequiredResearch = "InstaCapShipTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 1,
    DisplayedName = "$9369",
    Description = "$9370",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_as_hyperspace",
    RequiredResearch = "InstaLightWeaponTech | InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 2,
    DisplayedName = "$9377",
    Description = "$9378",
  },
   {
    Type = SubSystem,
    ThingToBuild = "tur_as_Fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 3,
    DisplayedName = "$9351",
    Description = "$9352",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_as_Frigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "LightWeapon | HeavyWeapon",
    DisplayPriority = 4,
    DisplayedName = "$9361",
    Description = "$9362",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_as_Frigateadvanced",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 5,
    DisplayedName = "$9365",
    Description = "$9366",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_as_CapShip",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 6,
    DisplayedName = "$9363",
    Description = "$9364",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_as_FrigateCapture",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 7,
    DisplayedName = "$9367",
    Description = "$9368",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_as_CapShipadvanced",
    RequiredResearch = "InstaHeavyGunArrayTech",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 8,
    DisplayedName = "$9373",
    Description = "$9374",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_R_turret",
    RequiredResearch = "",
    RequiredFleetSubSystems = "LightWeapon",
    DisplayPriority = 1,
    DisplayedName = "$9357",
    Description = "$9358",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_R_hyperspace",
    RequiredResearch = "InstaLightWeaponTech | InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 2,
    DisplayedName = "$9377",
    Description = "$9378",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_R_LightWeapon",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 3,
    DisplayedName = "$9353",
    Description = "$9354",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_R_HeavyWeapon",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 4,
    DisplayedName = "$9355",
    Description = "$9356",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_HC_weapon",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CapShipadvanced | KeyToAllShips",
    DisplayPriority = 1,
    DisplayedName = "$9375",
    Description = "$9376",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tur_HC_hyperspace",
    RequiredResearch = "InstaLightWeaponTech | InstaHeavyWeaponTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 2,
    DisplayedName = "$9377",
    Description = "$9378",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_scout",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 1,
    DisplayedName = "$9301",
    Description = "$9302",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_fighter",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction | KeyToAllShips",
    DisplayPriority = 2,
    DisplayedName = "$9303",
    Description = "$9304",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_attackbomber",
    RequiredResearch = "",
    RequiredFleetSubSystems = "(FighterProduction & LightWeapon) | KeyToAllShips",
    DisplayPriority = 3,
    DisplayedName = "$9305",
    Description = "$9306",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_standardcorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "(FighterProduction & LightWeapon) | KeyToAllShips",
    DisplayPriority = 10,
    DisplayedName = "$9309",
    Description = "$9310",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_missilecorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "(FighterProduction & HeavyWeapon) | KeyToAllShips",
    DisplayPriority = 11,
    DisplayedName = "$9311",
    Description = "$9312",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_minelayercorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "(FighterProduction & HeavyWeapon) | KeyToAllShips",
    DisplayPriority = 12,
    DisplayedName = "$9313",
    Description = "$9314",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_torpedoCorvette",
    RequiredResearch = "InstaFrigateadvancedTech",
    RequiredFleetSubSystems = "FighterProduction | KeyToAllShips",
    DisplayPriority = 14,
    DisplayedName = "$9307",
    Description = "$9308",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_vulcanfrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 21,
    DisplayedName = "$9317",
    Description = "$9318",
  },

  {
    Type = Ship,
    ThingToBuild = "tur_ionarrayfrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Frigateadvanced | KeyToAllShips",
    DisplayPriority = 22,
    DisplayedName = "$9321",
    Description = "$9322",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_SiegeDrillfrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateCapture | KeyToAllShips",
    DisplayPriority = 23,
    DisplayedName = "$9319",
    Description = "$9320",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_Energyfrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 24,
    DisplayedName = "$9315",
    Description = "$9316",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_shipyard",
    RequiredResearch = "",
    RequiredShipSubSystems = "Hyperspace | CapShipProduction", 
    DisplayPriority = 31,
    DisplayedName = "$9325",
    Description = "$9326",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_ResourceController",
    RequiredResearch = "",
    RequiredShipSubSystems = "Hyperspace | CapShipProduction",
    DisplayPriority = 32,
    DisplayedName = "$9327",
    Description = "$9328",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_carrier",
    RequiredResearch = "",
    RequiredShipSubSystems = "CapShipProduction",
    DisplayPriority = 33,
    DisplayedName = "$9323",
    Description = "$9324",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_heavycruiser",
    RequiredResearch = "",
    RequiredShipSubSystems = "CapShipProduction & CapShipadvanced",
    DisplayPriority = 35,
    DisplayedName = "$9329",
    Description = "$9330",
  },
--{
 --Type = Ship,
 --ThingToBuild = "tur_heavygunturret",
 --RequiredResearch = "",
 --RequiredShipSubSystems = "PlatformProduction",
 --DisplayPriority = 41,
 --DisplayedName = "$9329",
 --Description = "$9330",
--},
  {
    Type = Ship,
    ThingToBuild = "tur_cloakgenerator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Frigateadvanced",
    DisplayPriority = 30,
    DisplayedName = "$9333",
    Description = "$9334",
  },
--{
  --Type = Ship,
  --ThingToBuild = "tur_gravwellgenerator",
  --RequiredResearch = "",
  --RequiredShipSubSystems = "PlatformProduction",
  --DisplayPriority = 44,
  --DisplayedName = "$9335",
  --Description = "$9336",
--},
  {
    Type = Ship,
    ThingToBuild = "tur_resourcecollector",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 52,
    DisplayedName = "$9335",
    Description = "$9336",
  },
  {
    Type = Ship,
    ThingToBuild = "tur_Garbage",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateProduction",
    DisplayPriority = 53,
    DisplayedName = "$9337",
    Description = "$9338",
  },
--{
  --Type = Ship,
  --ThingToBuild = "tur_probe",
  --RequiredResearch = "",
  --RequiredShipSubSystems = "",
  --DisplayPriority = 54,
  --DisplayedName = "$9339",
  --Description = "$9340",
--},
}
