dofilepath("Data:leveldata/multiplayer/lib/FXGDeathmatch_Data.lua")

Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
BLUE = 0
YELLOW = 1
RED = nil
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "FXGDM",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
  },
  {
    Name = "Branch1",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "定居氏族",
    DisplayPriority = 1,
    Description = "泰坦帝国分崩离析后，曾经作为其雇佣军的图拉尼人瞅准机会夺取了帝国西部很多行星的控制权，历史上第一次，图拉尼人开始尝试星球上的定居生活。这些选择定居的图拉尼氏族凭借星球上丰富的资源产出，为其他图拉尼人提供着坚实的后勤保障。\n可召唤火神护卫舰进入战场\n常规护航艇武器威力更大\n火神护卫舰特殊能力\n建造护卫舰生产设施后立即获得主力舰生产设施\n重炮巡洋舰可建造资源单位",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_shield,
    ShortDisplayedName = "定居氏族",
  },
  {
    Name = "Branch2",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "乡港氏族",
    DisplayPriority = 2,
    Description = "乡港是图拉尼人最重要的补给基地，图拉尼人为了保卫乡港可以不计任何代价。世代居住在乡港并以守护乡港为己任的图拉尼氏族对任何胆敢进犯的敌人而言都是难缠的对手。\n可召唤离子阵列舰进入战场\n死神攻击艇武器威力更大\n离子阵列舰增幅模式不降低机动性\n建造主力舰生产设施后立即获得一个乡港重炮阵列系统\n乡港生产速度更快",
    UpgradeType = RED,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Health,
    ShortDisplayedName = "乡港氏族",
  },
  {
    Name = "Branch3",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "劫掠氏族",
    DisplayPriority = 3,
    Description = "海盗营生不仅是图拉尼人的老本行，对于世代以此为生的图拉尼氏族来说，这更是他们生存的全部意义。这群外族眼中的亡命之徒最擅长的就是对缺少护航的猎物发动突然袭击，并在追兵赶来前迅速离开。\n可召唤破城登陆舰进入战场\n布雷艇武器威力更大\n破城登陆舰穿透武器系统\n建造主力舰生产设施后立即获得一艘攻击运载舰\n攻击运载舰核导弹武器系统",
    UpgradeType = RED,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Attack,
    ShortDisplayedName = "劫掠氏族",
  },
  {
    Name = "Sumon_VulcanFrigate",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "FrigateProduction",
    Cost = FXG_Sumon_Data.Turanic[1].Cost,
    Time = 100,
    DisplayedName = "召唤火神护卫舰进入战场",
    DisplayPriority = 0,
    Description = "火神护卫舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"tur_vulcanfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "火神护卫舰",
  },
  {
    Name = "Sumon_IonArrayFrigate",
    RequiredResearch = "Branch2 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "Frigateadvanced",
    Cost = FXG_Sumon_Data.Turanic[2].Cost,
    Time = 100,
    DisplayedName = "召唤离子阵列舰进入战场",
    DisplayPriority = 0,
    Description = "离子阵列舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"tur_ionarrayfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "离子阵列舰",
  },
  {
    Name = "Sumon_SiegeDrillFrigate",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "FrigateCapture",
    Cost = FXG_Sumon_Data.Turanic[3].Cost,
    Time = 100,
    DisplayedName = "召唤破城登陆舰进入战场",
    DisplayPriority = 0,
    Description = "破城登陆舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"tur_SiegeDrillfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "破城登陆舰",
  },
  {
    Name = "StandardCorvetteDamageUpgrade",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
		TargetType =		Ship,
		TargetName =		"tur_standardcorvette",
  },
  {
    Name = "TorpedoCorvetteDamageUpgrade",
    RequiredResearch = "Branch2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
		TargetType =		Ship,
		TargetName =		"tur_torpedocorvette",
  },
  {
    Name = "MinelayerCorvetteDamageUpgrade",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
		TargetType =		Ship,
		TargetName =		"tur_minelayercorvette",
  },
  {
    Name = "ShipyardBuildSpeedUpgrade",
    RequiredResearch = "Branch2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tur_shipyard",
    UpgradeName = "BUILDSPEED",
    UpgradeValue = 1.2,
  },
  {
    Name = "InstantBuild_CapShipProduction",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "FrigateProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_HeavyGunArray",
    RequiredResearch = "Branch2",
    RequiredSubSystems = "CapShipProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_Carrier",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "CapShipProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstaFighterTech",
    RequiredResearch = "",
    RequiredSubSystems = "FighterProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaCorvetteTech",
    RequiredResearch = "",
    RequiredSubSystems = "CorvetteProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaFrigateTech",
    RequiredResearch = "",
    RequiredSubSystems = "FrigateProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaCapShipTech",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaHeavyGunArrayTech",
    RequiredResearch = "",
    RequiredSubSystems = "HeavyGunArray | KeyToAllShips",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaLightWeaponTech",
    RequiredResearch = "",
    RequiredSubSystems = "LightWeapon",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaHeavyWeaponTech",
    RequiredResearch = "",
    RequiredSubSystems = "HeavyWeapon",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "InstaFrigateadvancedTech",
    RequiredResearch = "",
    RequiredSubSystems = "Frigateadvanced",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tur_shipyard",
  },
  {
    Name = "scoutCloakTech",
    RequiredResearch = "",
    RequiredSubSystems = "Frigateadvanced",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9367",
    DisplayPriority = 2,
    Description = "$9368",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "tur_scout",
    UpgradeName = "Cloak",
    Icon = Icon_Cloak,
    ShortDisplayedName = "$9405",
  },
--AI behaviour	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed	
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.025,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.05,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.075,
	},
--AI resource rate	
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},			
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")