Ship = 0
SubSystem = 1
build = {
  {
    Type = SubSystem,
    ThingToBuild = "kpr_BUILD",
    RequiredResearch = "photonBombTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 1,
    DisplayedName = "$8330",
    Description = "$8333",
  },
  {
    Type = SubSystem,
    ThingToBuild = "kpr_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "BUILD",
    DisplayPriority = 2,
    DisplayedName = "$8331",
    Description = "$8334",
  },
  {
    Type = SubSystem,
    ThingToBuild = "kpr_Core",
    RequiredResearch = "PhasedCannonTech",
    RequiredFleetSubSystems = "Hyperspace",
    DisplayPriority = 3,
    DisplayedName = "$8332",
    Description = "$8335",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_Scout",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 10,
    DisplayedName = "$8200",
    Description = "$8201",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_bomber",
    RequiredResearch = "",
    RequiredFleetSubSystems = "photonBomb",
    DisplayPriority = 20,
    DisplayedName = "$8202",
    Description = "$8203",
  },
  --{
    --Type = Ship,
    --ThingToBuild = "kpr_Drone",
    --RequiredResearch = "",
    --RequiredFleetSubSystems = "",
    --DisplayPriority = 30,
    --DisplayedName = "$8204",
    --Description = "$8205",
  --},
  {
    Type = Ship,
    ThingToBuild = "kpr_movers",
    RequiredResearch = "",
    RequiredFleetSubSystems = "photonBomb",
    DisplayPriority = 50,
    DisplayedName = "$8210",
    Description = "$8211",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_mover1",
    RequiredResearch = "BUILDTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 51,
    DisplayedName = "$8212",
    Description = "$8213",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_HeavyMover",
    RequiredResearch = "",
    RequiredFleetSubSystems = "photoncannon",
    DisplayPriority = 52,
    DisplayedName = "$8214",
    Description = "$8215",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_CaptureMover",
    RequiredResearch = "HyperspaceTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 53,
    DisplayedName = "$8216",
    Description = "$8217",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_AssaultFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "photoncannon",
    DisplayPriority = 60,
    DisplayedName = "$8220",
    Description = "$8221",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_IonCannonFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Pulsar",
    DisplayPriority = 70,
    DisplayedName = "$8222",
    Description = "$8223",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_Destroyerfrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "ioncannon",
    DisplayPriority = 80,
    DisplayedName = "$8224",
    Description = "$8225",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_defensefieldfrigate",
    RequiredResearch = "HyperspaceTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 85,
    DisplayedName = "$8246",
    Description = "$8247",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_Deliver",
    RequiredResearch = "BUILDTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 100,
    DisplayedName = "$8244",
    Description = "$8245",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_carrier",
    RequiredResearch = "HyperspaceTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 105,
    DisplayedName = "$2403",
    Description = "$8231",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_balcoragate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 110,
    DisplayedName = "$8234",
    Description = "$8235",
  }, 
  {
    Type = Ship,
    ThingToBuild = "kpr_destroyer1",
    RequiredResearch = "",
    RequiredFleetSubSystems = "ioncannon & Pulsar",
    DisplayPriority = 111,
    DisplayedName = "$8232",
    Description = "$8233",
  },
  { 
    Type = Ship, 
    ThingToBuild = "Kpr_ArsenalShip",
    RequiredResearch = "",
    RequiredFleetSubSystems = "PhasedCannon",
    DisplayPriority = 112,
    DisplayedName = "$8236",
    Description = "$8237"
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_Dreadnaught",
    RequiredResearch = "CoreTech",
    RequiredFleetSubSystems = "PhasedCannon",
    DisplayPriority = 116,
    DisplayedName = "$8238",
    Description = "$8239",
  },
  {
    Type = Ship,
    ThingToBuild = "Kpr_Sajuuks",
    RequiredResearch = "",
    RequiredFleetSubSystems = "SuperPulsar",
    DisplayPriority = 118,
    DisplayedName = "$8240",
    Description = "$8241",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_energy_photonBomb",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 120,
    DisplayedName = "$8310",
    Description = "$8311",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_energy_photoncannon",
    RequiredResearch = "HyperspaceTech",
    RequiredFleetSubSystems = "photonBomb",
    DisplayPriority = 121,
    DisplayedName = "$8312",
    Description = "$8313",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_energy_ioncannon",
    RequiredResearch = "HyperspaceTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 122,
    DisplayedName = "$8314",
    Description = "$8315",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_energy_PhasedCannon",
    RequiredResearch = "HyperspaceTech",
    RequiredFleetSubSystems = "photoncannon & ioncannon",
    DisplayPriority = 123,
    DisplayedName = "$8316",
    Description = "$8317",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_energy_Pulsar",
    RequiredResearch = "HyperspaceTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 124,
    DisplayedName = "$8318",
    Description = "$8319",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_energy_SuperPulsar",
    RequiredResearch = "CoreTech",
    RequiredFleetSubSystems = "Pulsar",
    DisplayPriority = 125,
    DisplayedName = "$8320",
    Description = "$8321",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_ResourceCollector",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 130,
    DisplayedName = "$8300",
    Description = "$8301",
  },
  {
    Type = Ship,
    ThingToBuild = "kpr_resourcecontroller",
    RequiredResearch = "HyperspaceTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 131,
    DisplayedName = "$8302",
    Description = "$8303",
  },
--{
  --Type = Ship,
  --ThingToBuild = "kpr_probe",
  --RequiredResearch = "",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 140,
  --DisplayedName = "$8304",
  --Description = "$8305",
--},
  {
    Type = Ship,
    ThingToBuild = "kpr_proximitysensor",
    RequiredResearch = "HyperspaceTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 150,
    DisplayedName = "$8306",
    Description = "$8307",
  },
 }