dofilepath("Data:leveldata/multiplayer/lib/FXGDeathmatch_Data.lua")

Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
BLUE = 0
YELLOW = 1
RED = nil
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "FXGDM",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
  },
  {
    Name = "Branch1",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "自然派系",
    DisplayPriority = 1,
    Description = "自然派系认为科技仍应遵循基本的自然规律，该派系的先祖拒绝接受科技改造，对AI控制舰船更是深恶痛绝。他们的舰队虽然不够强大，但仍然可以凭借意志和谋略顽强作战。\n可召唤打击者进入战场\n伴随者侦察机EMP武器系统\n打击者护卫舰强输出模式\n升级跳跃之力后立即获得造物之手\n造物之手生产速度更快",
    UpgradeType = BLUE,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Speed,
    ShortDisplayedName = "自然派系",
  },
  {
    Name = "Branch2",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "智能派系",
    DisplayPriority = 2,
    Description = "智能派系充分信任人工智能，他们将舰船交给AI全权管理，自己很少甚至不再参与战斗，因此他们可以毫不顾忌地将飞船送入战场。\n可召唤毁灭者进入战场\n伴随者侦察机脉冲武器系统\n毁灭者护卫舰强输出模式\n建造脉冲及离子炮金字塔后立即获得一艘守护者\n守护者载机数量+1",
    UpgradeType = RED,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Emp,
    ShortDisplayedName = "智能派系",
  },
  {
    Name = "Branch3",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "量子派系",
    DisplayPriority = 3,
    Description = "量子派系是以量子通讯员为代表的各种通过科技改造增强自身能力的先祖人，他们驾驶的舰船往往能够做到常规舰船做不到的事。\n可召唤审判者进入战场\n伴随者侦察机感应器扫描能力\n审判者护卫舰增幅能力\n建造定向加农炮金字塔后立即获得一艘狙击舰\n狙击舰射程更远",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_ping,
    ShortDisplayedName = "量子派系",
  },
  {
    Name = "Sumon_AssaultFrigate",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "photoncannon",
    Cost = FXG_Sumon_Data.Keeper[1].Cost,
    Time = 100,
    DisplayedName = "召唤打击者护卫舰进入战场",
    DisplayPriority = 0,
    Description = "打击者护卫舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"kpr_assaultfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "打击者护卫舰",
  },
  {
    Name = "Sumon_DestroyerFrigate",
    RequiredResearch = "Branch2 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "ioncannon",
    Cost = FXG_Sumon_Data.Keeper[2].Cost,
    Time = 100,
    DisplayedName = "召唤毁灭者护卫舰进入战场",
    DisplayPriority = 0,
    Description = "毁灭者护卫舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"kpr_destroyerfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "毁灭者护卫舰",
  },
  {
    Name = "Sumon_FieldFrigate",
    RequiredResearch = "Branch3 & HyperspaceTech",
    RequiredSubSystems = "",
    Cost = FXG_Sumon_Data.Keeper[3].Cost,
    Time = 100,
    DisplayedName = "召唤审判者护卫舰进入战场",
    DisplayPriority = 0,
    Description = "审判者护卫舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"kpr_defensefieldfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "审判者护卫舰",
  },
  {
    Name = "InstantBuild_Carrier",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "Hyperspace",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_Keeper",
    RequiredResearch = "Branch2",
    RequiredSubSystems = "ioncannon & Pulsar",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_ArsenalShip",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "PhasedCannon",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "ScoutEMPAbility",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Kpr_Scout",
    UpgradeName = "SpecialAttack",
  },
  {
    Name = "ScoutPingAbility",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Kpr_Scout",
    UpgradeName = "SensorPing",
  },
  {
    Name = "CarrierBuildSpeedUpgrade",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Carrier",
    UpgradeName = "BUILDSPEED",
    UpgradeValue = 1.2,
  },
  {
    Name = "ArsenalShipWeaponRangeUpgrade",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Kpr_ArsenalShip",
    UpgradeName = "UseSpecialWeaponsInNormalAttack",
  },
  {
    Name = "BUILDTech",
    RequiredResearch = "",
    RequiredSubSystems = "BUILD",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "kpr_balcoragate",
  },
  {
    Name = "HyperspaceTech",
    RequiredResearch = "",
    RequiredSubSystems = "Hyperspace",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 2,
    Description = "",
    TargetName = "kpr_balcoragate",
  },
  {
    Name = "CoreTech",
    RequiredResearch = "",
    RequiredSubSystems = "Core",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 3,
    Description = "",
    TargetName = "kpr_balcoragate",
  },
  {
    Name = "photonBombTech",
    RequiredResearch = "",
    RequiredSubSystems = "photonBomb",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 4,
    Description = "",
    TargetName = "kpr_energy_photonBomb",
  },
  {
    Name = "photoncannonTech",
    RequiredResearch = "",
    RequiredSubSystems = "photoncannon",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 5,
    Description = "",
    TargetName = "kpr_energy_photoncannon",
  },
  {
    Name = "PulsarTech",
    RequiredResearch = "",
    RequiredSubSystems = "Pulsar",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 6,
    Description = "",
    TargetName = "kpr_energy_Pulsar",
  },
  {
    Name = "ioncannonTech",
    RequiredResearch = "",
    RequiredSubSystems = "ioncannon",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 7,
    Description = "",
    TargetName = "kpr_energy_ioncannon",
  },
  {
    Name = "PhasedCannonTech",
    RequiredResearch = "",
    RequiredSubSystems = "PhasedCannon",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 8,
    Description = "",
    TargetName = "kpr_energy_PhasedCannon",
  },
--AI behaviour	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed	
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.025,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.05,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.075,
	},
--AI resource rate	
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},			
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")