supplyLimit("Fighter",28)
	supplyLimit("scout",16)
	supplyIndent("scout", 1)
	supplyLimit("CloakedFighter",8)
	supplyIndent("CloakedFighter", 1)

supplyLimit("Corvette",24)
	supplyLimit("MinelayerCorvette",8)
	supplyIndent("MinelayerCorvette", 1)
	supplyLimit("Swarmerelite",8)
	supplyIndent("Swarmerelite", 1)
	supplyLimit("AdvancedSwarmer",16)
	supplyIndent("AdvancedSwarmer", 1)
	supplyLimit("Azrael",12)
	supplyIndent("Azrael", 1)

supplyLimit("Frigate",70)
	supplyLimit("DefenseFieldFrigate",4)
	supplyIndent("DefenseFieldFrigate", 1)
	supplyLimit("EnergyFrigate",8)
	supplyIndent("EnergyFrigate", 1)
	supplyLimit("militaryCapture",12)
	supplyIndent("militaryCapture", 1)
	supplyLimit("Minesweeperfrigate",8)
	supplyIndent("Minesweeperfrigate", 1)
	supplyLimit("EnergyInterference",8)
	supplyIndent("EnergyInterference", 1)
	supplyLimit("CaptureFrigate",12)
	supplyIndent("CaptureFrigate", 1)

supplyLimit("Capital",24)
	supplyLimit("AttackMothership",6)
	supplyIndent("AttackMothership", 1)
	supplyLimit("Carrier",4)
	supplyIndent("Carrier", 1)
	supplyLimit("turShipyard",2)
	supplyIndent("turShipyard", 1)
	supplyLimit("kCarrier",1)
	supplyIndent("kCarrier", 1)
	supplyLimit("TAICarrier",3)
	supplyIndent("TAICarrier", 1)
	supplyLimit("kadCarrier",2)
	supplyIndent("kadCarrier", 1)
	supplyLimit("RecycleStation",1)
	supplyIndent("RecycleStation", 1)
	supplyLimit("Deliver",4)
	supplyIndent("Deliver", 1)
	supplyLimit("Keeper",8)
	supplyIndent("Keeper", 1)
	supplyLimit("Destroyer",10)
	supplyIndent("Destroyer", 1)
	supplyLimit("GuardianSpirit",2)
	supplyIndent("GuardianSpirit", 1)
	supplyLimit("turcruiser",10)
	supplyIndent("turcruiser", 1)
	supplyLimit("Arsenal",4)
	supplyIndent("Arsenal", 1)
	supplyLimit("HeavyCruiser",4)
	supplyIndent("HeavyCruiser", 1)
	supplyLimit("TurHeavyCruiser",6)
	supplyIndent("TurHeavyCruiser", 1)
	supplyLimit("LightCruiser",2)
	supplyIndent("LightCruiser", 1)
	supplyLimit("DefenseCruiser",2)
	supplyIndent("DefenseCruiser", 1)
	supplyLimit("Battlecruiser",4)
	supplyIndent("Battlecruiser", 2)
	supplyLimit("Dreadnaught",2)
	supplyIndent("Dreadnaught", 1)
	supplyLimit("Shipyard",2)
	supplyIndent("Shipyard", 1)
	supplyLimit("balcoragate",2)
	supplyIndent("balcoragate", 1)
	supplyLimit("TAIMothership",3)
	supplyIndent("TAIMothership", 1)
	supplyLimit("sajuuk",1)
	supplyIndent("sajuuk", 1)
	supplyLimit("Mothership",4)
	supplyIndent("Mothership", 1)
	supplyLimit("taiBattleship",2)
	supplyIndent("taiBattleship", 1)

supplyLimit("Utility",60)
	supplyLimit("ResourceCollector",48)
	supplyIndent("ResourceCollector", 1)
	supplyLimit("ResourceController",12)
	supplyIndent("ResourceController", 1)
	supplyLimit("fuelpod",8)
	supplyIndent("fuelpod", 1)
	supplyLimit("Probe",20)
	supplyIndent("Probe", 1)

supplyLimit("Platform",40)
	supplyLimit("defenseFighter",20)
	supplyIndent("defenseFighter", 1)
	supplyLimit("photonBomb",2)
	supplyIndent("photonBomb", 1)
	supplyLimit("photoncannon",2)
	supplyIndent("photoncannon", 1)
	supplyLimit("ioncannon",2)
	supplyIndent("ioncannon", 1)
	supplyLimit("PhasedCannon",2)
	supplyIndent("PhasedCannon", 1)
	supplyLimit("Pulsar",2)
	supplyIndent("Pulsar", 1)
	supplyLimit("SuperPulsar",2)
	supplyIndent("SuperPulsar", 1)
	supplyLimit("Core1",1)
	supplyIndent("Core1", 1)
	supplyLimit("Core2",1)
	supplyIndent("Core2", 1)
	supplyLimit("Core3",1)
	supplyIndent("Core3", 1)
	supplyLimit("AdvancedSensorsArray",12)
	supplyIndent("AdvancedSensorsArray", 1)
	supplyLimit("GravWellGenerator",12)
	supplyIndent("GravWellGenerator", 1)
	supplyLimit("heavygun",40)
	supplyIndent("heavygun", 1)

supplyLimit("Researchship",6)

supplyLimit("Researchstation",1)

supplyLimit("SinglePlayerMisc",12)

supplyShow("Fighter", "Always");
supplyShow("Corvette", "Always");
supplyShow("Frigate", "Always");
supplyShow("Capital", "Always");
supplyShow("Utility", "Always");
supplyShow("Platform", "Always");
