supplyLimit("Fighter",14)
	supplyLimit("scout",8)
	supplyIndent("scout", 1)
	supplyLimit("CloakedFighter",4)
	supplyIndent("CloakedFighter", 1)

supplyLimit("Corvette",12)
	supplyLimit("MinelayerCorvette",4)
	supplyIndent("MinelayerCorvette", 1)
	supplyLimit("Swarmerelite",4)
	supplyIndent("Swarmerelite", 1)
	supplyLimit("AdvancedSwarmer",8)
	supplyIndent("AdvancedSwarmer", 1)
	supplyLimit("Azrael",6)
	supplyIndent("Azrael", 1)

supplyLimit("Frigate",35)
	supplyLimit("DefenseFieldFrigate",2)
	supplyIndent("DefenseFieldFrigate", 1)
	supplyLimit("EnergyFrigate",4)
	supplyIndent("EnergyFrigate", 1)
	supplyLimit("militaryCapture",6)
	supplyIndent("militaryCapture", 1)
	supplyLimit("Minesweeperfrigate",4)
	supplyIndent("Minesweeperfrigate", 1)
	supplyLimit("EnergyInterference",4)
	supplyIndent("EnergyInterference", 1)
	supplyLimit("CaptureFrigate",6)
	supplyIndent("CaptureFrigate", 1)

supplyLimit("Capital",12)
	supplyLimit("AttackMothership",3)
	supplyIndent("AttackMothership", 1)
	supplyLimit("Carrier",4)
	supplyIndent("Carrier", 1)
	supplyLimit("turShipyard",2)
	supplyIndent("turShipyard", 1)
	supplyLimit("kCarrier",1)
	supplyIndent("kCarrier", 1)
	supplyLimit("TAICarrier",3)
	supplyIndent("TAICarrier", 1)
	supplyLimit("kadCarrier",1)
	supplyIndent("kadCarrier", 1)
	supplyLimit("RecycleStation",1)
	supplyIndent("RecycleStation", 1)
	supplyLimit("Deliver",4)
	supplyIndent("Deliver", 1)
	supplyLimit("Keeper",4)
	supplyIndent("Keeper", 1)
	supplyLimit("Destroyer",5)
	supplyIndent("Destroyer", 1)
	supplyLimit("GuardianSpirit",3)
	supplyIndent("GuardianSpirit", 1)
	supplyLimit("turcruiser",5)
	supplyIndent("turcruiser", 1)
	supplyLimit("Arsenal",2)
	supplyIndent("Arsenal", 1)
	supplyLimit("HeavyCruiser",2)
	supplyIndent("HeavyCruiser", 1)
	supplyLimit("TurHeavyCruiser",2)
	supplyIndent("TurHeavyCruiser", 1)
	supplyLimit("LightCruiser",1)
	supplyIndent("LightCruiser", 1)
	supplyLimit("Battlecruiser",2)
	supplyIndent("Battlecruiser", 1)
	supplyLimit("Dreadnaught",1)
	supplyIndent("Dreadnaught", 1)
	supplyLimit("Shipyard",1)
	supplyIndent("Shipyard", 1)
	supplyLimit("balcoragate",1)
	supplyIndent("balcoragate", 1)
	supplyLimit("TAIMothership",2)
	supplyIndent("TAIMothership", 1)
	supplyLimit("sajuuk",1)
	supplyIndent("sajuuk", 1)
	supplyLimit("Mothership",2)
	supplyIndent("Mothership", 1)
	supplyLimit("taiBattleship",1)
	supplyIndent("taiBattleship", 1)

supplyLimit("Utility",30)
	supplyLimit("ResourceCollector",24)
	supplyIndent("ResourceCollector", 1)
	supplyLimit("ResourceController",6)
	supplyIndent("ResourceController", 1)
	supplyLimit("fuelpod",4)
	supplyIndent("fuelpod", 1)
	supplyLimit("Probe",10)
	supplyIndent("Probe", 1)

supplyLimit("Platform",20)
	supplyLimit("defenseFighter",10)
	supplyIndent("defenseFighter", 1)
	supplyLimit("photonBomb",1)
	supplyIndent("photonBomb", 1)
	supplyLimit("photoncannon",1)
	supplyIndent("photoncannon", 1)
	supplyLimit("ioncannon",1)
	supplyIndent("ioncannon", 1)
	supplyLimit("PhasedCannon",1)
	supplyIndent("PhasedCannon", 1)
	supplyLimit("Pulsar",1)
	supplyIndent("Pulsar", 1)
	supplyLimit("SuperPulsar",1)
	supplyIndent("SuperPulsar", 1)
	supplyLimit("Core1",1)
	supplyIndent("Core1", 1)
	supplyLimit("Core2",1)
	supplyIndent("Core2", 1)
	supplyLimit("Core3",1)
	supplyIndent("Core3", 1)
	supplyLimit("AdvancedSensorsArray",6)
	supplyIndent("AdvancedSensorsArray", 1)
	supplyLimit("GravWellGenerator",6)
	supplyIndent("GravWellGenerator", 1)
	supplyLimit("heavygun",20)
	supplyIndent("heavygun", 1)

supplyLimit("Researchship",6)

supplyLimit("Researchstation",1)


supplyLimit("SinglePlayerMisc",6)

supplyShow("Fighter", "Always");
supplyShow("Corvette", "Always");
supplyShow("Frigate", "Always");
supplyShow("Capital", "Always");
supplyShow("Utility", "Always");
supplyShow("Platform", "Always");