supplyLimit("Fighter",50)
	supplyLimit("scout",20)
	supplyIndent("scout", 1)
	supplyLimit("CloakedFighter",10)
	supplyIndent("CloakedFighter", 1)
	
supplyLimit("Corvette",40)
	supplyLimit("MinelayerCorvette",40)
	supplyIndent("MinelayerCorvette", 1)
	supplyLimit("Swarmerelite",40)
	supplyIndent("Swarmerelite", 1)
	supplyLimit("AdvancedSwarmer",40)
	supplyIndent("AdvancedSwarmer", 1)
	supplyLimit("Azrael",30)
	supplyIndent("Azrael", 1)

supplyLimit("Frigate", 180)
	supplyLimit("DefenseFieldFrigate",40)
	supplyIndent("DefenseFieldFrigate", 1)
	supplyLimit("EnergyFrigate",80)
	supplyIndent("EnergyFrigate", 1)
	supplyLimit("militaryCapture",120)
	supplyIndent("militaryCapture", 1)
	supplyLimit("Minesweeperfrigate",80)
	supplyIndent("Minesweeperfrigate", 1)
	supplyLimit("EnergyInterference",40)
	supplyIndent("EnergyInterference", 1)
	supplyLimit("CaptureFrigate",60)
	supplyIndent("CaptureFrigate", 1)

supplyLimit("Capital", 120)
	supplyLimit("AttackMothership",60)
	supplyIndent("AttackMothership", 1)
	supplyLimit("Carrier",40)
	supplyIndent("Carrier", 1)
	supplyLimit("turShipyard",20)
	supplyIndent("turShipyard", 1)
	supplyLimit("kCarrier",20)
	supplyIndent("kCarrier", 1)
	supplyLimit("TAICarrier",30)
	supplyIndent("TAICarrier", 1)
	supplyLimit("kadCarrier",1)
	supplyIndent("kadCarrier", 1)
	supplyLimit("RecycleStation",10)
	supplyIndent("RecycleStation", 1)
	supplyLimit("Deliver",40)
	supplyIndent("Deliver", 1)
	supplyLimit("Keeper",80)
	supplyIndent("Keeper", 1)
	supplyLimit("Destroyer",100)
	supplyIndent("Destroyer", 1)
	supplyLimit("GuardianSpirit",20)
	supplyIndent("GuardianSpirit", 1)
	supplyLimit("turcruiser",50)
	supplyIndent("turcruiser", 1)
	supplyLimit("Arsenal",40)
	supplyIndent("Arsenal", 1)
	supplyLimit("HeavyCruiser",40)
	supplyIndent("HeavyCruiser", 1)
	supplyLimit("TurHeavyCruiser",60)
	supplyIndent("TurHeavyCruiser", 1)
	supplyLimit("LightCruiser",20)
	supplyIndent("LightCruiser", 1)
	supplyLimit("DefenseCruiser",20)
	supplyIndent("DefenseCruiser", 1)
	supplyLimit("Battlecruiser",40)
	supplyIndent("Battlecruiser", 2)
	supplyLimit("Dreadnaught",20)
	supplyIndent("Dreadnaught", 1)
	supplyLimit("Shipyard",20)
	supplyIndent("Shipyard", 1)
	supplyLimit("balcoragate",20)
	supplyIndent("balcoragate", 1)
	supplyLimit("TAIMothership",30)
	supplyIndent("TAIMothership", 1)
	supplyLimit("sajuuk",1)
	supplyIndent("sajuuk", 1)
	supplyLimit("Mothership",6)
	supplyIndent("Mothership", 1)
	supplyLimit("taiBattleship",20)
	supplyIndent("taiBattleship", 1)

supplyLimit("Utility",120)
	supplyLimit("ResourceCollector",96)
	supplyIndent("ResourceCollector", 1)
	supplyLimit("ResourceController",24)
	supplyIndent("ResourceController", 1)
	supplyLimit("fuelpod",20)
	supplyIndent("fuelpod", 1)
	supplyLimit("Probe",40)
	supplyIndent("Probe", 1)

supplyLimit("Platform",80)
	supplyLimit("defenseFighter",40)
	supplyIndent("defenseFighter", 1)
	supplyLimit("photonBomb",3)
	supplyIndent("photonBomb", 1)
	supplyLimit("photoncannon",3)
	supplyIndent("photoncannon", 1)
	supplyLimit("ioncannon",3)
	supplyIndent("ioncannon", 1)
	supplyLimit("PhasedCannon",3)
	supplyIndent("PhasedCannon", 1)
	supplyLimit("Pulsar",3)
	supplyIndent("Pulsar", 1)
	supplyLimit("SuperPulsar",3)
	supplyIndent("SuperPulsar", 1)
	supplyLimit("Core1",1)
	supplyIndent("Core1", 1)
	supplyLimit("Core2",1)
	supplyIndent("Core2", 1)
	supplyLimit("Core3",1)
	supplyIndent("Core3", 1)
	supplyLimit("AdvancedSensorsArray",24)
	supplyIndent("AdvancedSensorsArray", 1)
	supplyLimit("GravWellGenerator",24)
	supplyIndent("GravWellGenerator", 1)
	supplyLimit("heavygun",80)
	supplyIndent("heavygun", 1)

supplyLimit("Researchship",6)

supplyLimit("Researchstation",3)

supplyLimit("SinglePlayerMisc",1000)

supplyShow("Fighter", "Always");
supplyShow("Corvette", "Always");
supplyShow("Frigate", "Always");
supplyShow("Capital", "Always");
supplyShow("Utility", "Always");
supplyShow("Platform", "Always");