Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research =
{	
  {
    Name = "Kus_DestroyerSpeedDowngrade",
    RequiredResearch = "SPOnly",
    RequiredSubSystems = "CapShip",
    Cost = 500,
    Time = 80,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kus_Destroyer",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 0.48,
  },
  {
    Name = "Kus_DestroyerHealthDowngrade",
    RequiredResearch = "Kus_DestroyerSpeedDowngrade",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kus_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 0.89,
  },
  {
    Name = "Kus_DestroyerDamageUpgrade",
    RequiredResearch = "Kus_DestroyerSpeedDowngrade",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kus_Destroyer",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.15,
  },
  {
    Name = "Kus_CarrierSpeedDowngrade",
    RequiredResearch = "SPOnly",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kus_Carrier",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 0.5,
  },
  {
    Name = "HyperspaceTech",
    RequiredResearch = "",
    RequiredSubSystems = "RA",
    Cost = 0,
    Time = 0,
    UpgradeType = Ability,
    TargetType = AllShips,
    UpgradeName = "Hyperspace",
    TargetName = "kus_researchship",
  },
  {
    Name = "ResearchTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "kus_researchship",
  },
  {
    Name = "PlasmaBombsTech",
    RequiredResearch = "",
    RequiredSubSystems = "FighterProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "kus_researchship",
  },
  {
    Name = "PlasmaBombsWeaponAccuracy",
    RequiredResearch = "PlasmaBombsTech",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    DisplayPriority = 1,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "kus_attackbomber",
    UpgradeName = "WeaponAccuracy",
    UpgradeValue = 2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10052",
  },
  {
    Name = "CorvetteTech",
    RequiredResearch = "",
    RequiredSubSystems = "CorvetteProduction | KeyToAllShips",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "kus_researchship",
  },
  {
    Name = "RATech",
    RequiredResearch = "",
    RequiredSubSystems = "RA",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "kus_researchshipadv",
  },
  {
    Name = "ioncannonTech",
    RequiredResearch = "",
    RequiredSubSystems = "IonCannon",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "kus_researchshipadv",
  },
  {
    Name = "kuscapshipTech",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "kus_researchshipadv",
  },
  {
    Name = "heavygunTech",
    RequiredResearch = "",
    RequiredSubSystems = "heavygun",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "kus_researchsshipadv",
  },
  {
    Name = "Kus_AirWeaponUpgrade1",
    RequiredResearch = "CorvetteTech",
    RequiredSubSystems = "Research | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$10708",
    DisplayPriority = 100,
    Description = "$10709",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10692",
  },
  {
    Name = "Kus_AirWeaponUpgrade2",
    RequiredResearch = "Kus_AirWeaponUpgrade1",
    RequiredSubSystems = "(Research & RA) | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$10710",
    DisplayPriority = 100,
    Description = "$10711",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10693",
  },
  {
    Name = "Kus_AirWeaponUpgrade3",
    RequiredResearch = "Kus_AirWeaponUpgrade2",
    RequiredSubSystems = "(Research & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$10712",
    DisplayPriority = 100,
    Description = "$10713",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10694",
  },
  {
    Name = "Kus_AirHealthUpgrade1",
    RequiredResearch = "CorvetteTech",
    RequiredSubSystems = "Research | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$10714",
    DisplayPriority = 101,
    Description = "$10715",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$10692",
  },
  {
    Name = "Kus_AirHealthUpgrade2",
    RequiredResearch = "Kus_AirHealthUpgrade1",
    RequiredSubSystems = "(Research & RA) | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$10716",
    DisplayPriority = 101,
    Description = "$10717",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$10693",
  },
  {
    Name = "Kus_AirHealthUpgrade3",
    RequiredResearch = "Kus_AirHealthUpgrade2",
    RequiredSubSystems = "(Research & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$10718",
    DisplayPriority = 101,
    Description = "$10719",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$10694",
  },
  {
    Name = "Kus_FrigateWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "RA | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$10720",
    DisplayPriority = 200,
    Description = "$10721",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.12,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10695",
  },
  {
    Name = "Kus_FrigateWeaponUpgrade2",
    RequiredResearch = "Kus_FrigateWeaponUpgrade1",
    RequiredSubSystems = "RA | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$10722",
    DisplayPriority = 200,
    Description = "$10723",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.24,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10696",
  },
  {
    Name = "Kus_FrigateWeaponUpgrade3",
    RequiredResearch = "Kus_FrigateWeaponUpgrade2",
    RequiredSubSystems = "(RA & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$10724",
    DisplayPriority = 200,
    Description = "$10725",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.36,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10697",
  },
  {
    Name = "Kus_FrigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "RA | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$10726",
    DisplayPriority = 201,
    Description = "$10727",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$10695",
  },
  {
    Name = "Kus_FrigateHealthUpgrade2",
    RequiredResearch = "Kus_FrigateHealthUpgrade1",
    RequiredSubSystems = "RA | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$10728",
    DisplayPriority = 201,
    Description = "$10729",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$10696",
  },
  {
    Name = "Kus_FrigateHealthUpgrade3",
    RequiredResearch = "Kus_FrigateHealthUpgrade2",
    RequiredSubSystems = "(RA & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$10730",
    DisplayPriority = 201,
    Description = "$10731",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$10697",
  },
  {
    Name = "Kus_CapitalWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$10732",
    DisplayPriority = 300,
    Description = "$10733",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10698",
  },
  {
    Name = "Kus_CapitalWeaponUpgrade2",
    RequiredResearch = "Kus_CapitalWeaponUpgrade1",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$10734",
    DisplayPriority = 300,
    Description = "$10735",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10699",
  },
  {
    Name = "Kus_CapitalWeaponUpgrade3",
    RequiredResearch = "Kus_CapitalWeaponUpgrade2",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$10736",
    DisplayPriority = 300,
    Description = "$10737",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10700",
  },
  {
    Name = "Kus_CapitalHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$10738",
    DisplayPriority = 301,
    Description = "$10739",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$10698",
  },
  {
    Name = "Kus_CapitalHealthUpgrade2",
    RequiredResearch = "Kus_CapitalHealthUpgrade1",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$10740",
    DisplayPriority = 301,
    Description = "$10741",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$10699",
  },
  {
    Name = "Kus_CapitalHealthUpgrade3",
    RequiredResearch = "Kus_CapitalHealthUpgrade2",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$10742",
    DisplayPriority = 301,
    Description = "$10743",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$10700",
  },
  {
    Name = "Kus_FighterWeaponUpgrade1",
    RequiredResearch = "Kus_AirWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$10708",
    DisplayPriority = 100,
    Description = "$10709",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10692",
  },
  {
    Name = "Kus_FighterWeaponUpgrade2",
    RequiredResearch = "Kus_AirWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$10710",
    DisplayPriority = 100,
    Description = "$10711",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10693",
  },
  {
    Name = "Kus_FighterWeaponUpgrade3",
    RequiredResearch = "Kus_AirWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$10712",
    DisplayPriority = 100,
    Description = "$10713",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$10694",
  },
  {
    Name = "Kus_FighterHealthUpgrade1",
    RequiredResearch = "Kus_AirHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$10714",
    DisplayPriority = 101,
    Description = "$10715",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$10692",
  },
  {
    Name = "Kus_FighterHealthUpgrade2",
    RequiredResearch = "Kus_AirHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$10716",
    DisplayPriority = 101,
    Description = "$10717",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$10693",
  },
  {
    Name = "Kus_FighterHealthUpgrade3",
    RequiredResearch = "Kus_AirHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$10718",
    DisplayPriority = 101,
    Description = "$10719",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$10694",
  },
--AI behaviour 	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.725,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.75,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.775,
	},	
--AI resource rate
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "kus_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "kus_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},
	--Special		
	{ 
		Name =			"MissileDestroyerVolley",
		RequiredResearch =	"",
		RequiredSubSystems =	"",
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,
		Description =		"",
		UpgradeType =		Ability,
		TargetType =		Ship,
		TargetName =		"Kus_MissileDestroyer",
		UpgradeName =		"UseSpecialWeaponsInNormalAttack",		
	},
	{ 
		Name =			"HeavyCorvetteAttackBurst",
		RequiredResearch =	"",
		RequiredSubSystems =	"",
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,
		Description =		"",
		UpgradeType =		Ability,
		TargetType =		Ship,
		TargetName =		"Kus_HeavyCorvette",
		UpgradeName =		"UseSpecialWeaponsInNormalAttack",		
	},		
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")