Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "Hgn_lbc_AFTech",
    RequiredResearch = "",
    RequiredSubSystems = "Never",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "Hgn_LightCruiser",
  },
  {
    Name = "hgnTech",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "Hgn_Mothership",
  },
  {
    Name = "InstaAdvancedFrigateTech",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "Hgn_Mothership",
  },
  {
    Name = "ScoutPingAbility",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 250,
    Time = 20,
    DisplayedName = "$7513",
    DisplayPriority = 1,
    Description = "$7514",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_Scout",
    UpgradeName = "SensorPing",
    Icon = Icon_ping,
    ShortDisplayedName = "$7206",
  },
  {
    Name = "ScoutEMPAbility",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 750,
    Time = 30,
    DisplayedName = "$7519",
    DisplayPriority = 2,
    Description = "$7520",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_Scout",
    UpgradeName = "SpecialAttack",
    Icon = Icon_Emp,
    ShortDisplayedName = "$7209",
  },
  {
    Name = "AttackBomberImprovedBombs",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 750,
    Time = 25,
    DisplayedName = "$7517",
    DisplayPriority = 1,
    Description = "$7518",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_AttackBomber",
    UpgradeName = "UseSpecialWeaponsInNormalAttack",
    Icon = Icon_Attack,
    ShortDisplayedName = "$7208",
  },
  {
    Name = "MovereliteAbility",
    RequiredResearch = "DamageMoverTech",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 500,
    Time = 20,
    DisplayedName = "$7948",
    DisplayPriority = 2,
    Description = "$7949",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "hgn_Moverelite",
    UpgradeName = "SpecialAttack",
    Icon = Icon_Ability,
    ShortDisplayedName = "$7950",
  },
  {
    Name = "AssaultCorvetteImprovedWeapon",
    RequiredResearch = "",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 750,
    Time = 30,
    DisplayedName = "$7728",
    DisplayPriority = 0,
    Description = "$7729",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvette",
    UpgradeName = "WeaponAccuracy",
    UpgradeValue = 4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$7728",
  },
  {
    Name = "GraviticAttractionMines",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 400,
    Time = 20,
    DisplayedName = "$7500",
    DisplayPriority = 2,
    Description = "$7501",
    TargetName = "Hgn_MinelayerCorvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7200",
  },
  {
    Name = "ImprovedTorpedo",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 500,
    Time = 30,
    DisplayedName = "$7515",
    DisplayPriority = 1,
    Description = "$7516",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "UseSpecialWeaponsInNormalAttack",
    Icon = Icon_Attack,
    ShortDisplayedName = "$7207",
  },
  {
    Name = "ImprovedTorpedo1",
    RequiredResearch = "ImprovedTorpedo",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7515",
    DisplayPriority = 1,
    Description = "$7516",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 2,
    Icon = Icon_Ability,
    ShortDisplayedName = "$7207",
  },
  {
    Name = "DefenseFieldFrigateShield",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 750,
    Time = 30,
    DisplayedName = "$7521",
    DisplayPriority = 32,
    Description = "$7522",
    TargetName = "Hgn_DefenseFieldFrigate",
    Icon = Icon_shield,
    ShortDisplayedName = "$7210",
  },
  {
    Name = "DefenseFieldFrigateShield1",
    RequiredResearch = "DefenseFieldFrigateShield",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7951",
    DisplayPriority = 30,
    Description = "$7952",
    UpgradeType = Ability,
    TargetType = Ship,
    UpgradeName = "DefenseField",
    TargetName = "hgn_marinefrigate",
    Icon = Icon_shield,
    ShortDisplayedName = "$7953",
  },
  {
    Name = "DestroyerTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 750,
    Time = 45,
    DisplayedName = "$7507",
    DisplayPriority = 0,
    Description = "$7508",
    TargetName = "Hgn_Destroyer",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7203",
  },
  {
    Name = "BattlecruiserGunWeapons",
    RequiredResearch = "DestroyerTech",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 750,
    Time = 40,
    DisplayedName = "$7917",
    DisplayPriority = 4,
    Description = "$7918",
    TargetName = "hgn_lightcruiser",
    Icon = Icon_Tech,
    ShortDisplayedName = "$1907",
  }, 
  {
    Name = "BattlecruiserIonWeapons",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 900,
    Time = 70,
    DisplayedName = "$7504",
    DisplayPriority = 2,
    Description = "$7505",
    TargetName = "Hgn_BattleCruiser",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7202",
  },
  {
    Name = "BattlecruiserIoneliteWeapons",
    RequiredResearch = "DestroyerHealthUpgrade2 & DestroyerMAXSPEEDUpgrade2",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 1250,
    Time = 80,
    DisplayedName = "$7926",
    DisplayPriority = 3,
    Description = "$7927",
    TargetName = "Hgn_BattleCruiserelite",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7924",
  },
  {
    Name = "PlatformIonWeapons",
    Required = "",
    RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
    Cost = 300,
    Time = 50,
    DisplayedName = "$7502",
    DisplayPriority = 24,
    Description = "$7503",
    TargetName = "Hgn_IonTurret",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7201",
  },
  {
    Name = "RadiationDefenseField",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 250,
    Time = 30,
    DisplayedName = "$7905",
    DisplayPriority = 30,
    Description = "$7906",
    UpgradeType = Ability,
    TargetType = Ship,
    UpgradeName = "DefenseFieldShield",
    TargetName = "Hgn_DefenseFieldFrigate",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7907",
  },
  {
    Name = "SensDisProbe",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 250,
    Time = 25,
    DisplayedName = "$7650",
    DisplayPriority = 5,
    Description = "$7651",
    TargetName = "Hgn_ProximitySensor",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7214",
  },
  {
    Name = "ECMProbe",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 250,
    Time = 25,
    DisplayedName = "$7509",
    DisplayPriority = 4,
    Description = "$7510",
    TargetName = "Hgn_ECMProbe",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7204",
  },
  {
    Name = "DamageMoverTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 500,
    Time = 60,
    DisplayedName = "$7900",
    DisplayPriority = 29,
    Description = "$7901",
    TargetName = "Hgn_Mothership",
    Icon = Icon_Tech,
    ShortDisplayedName = "$7902",
  },
  {
    Name = "RepairAbility",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 300,
    Time = 20,
    DisplayedName = "$7511",
    DisplayPriority = 26,
    Description = "$7512",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_ResourceCollector",
    UpgradeName = "Repair",
    Icon = Icon_Repair,
    ShortDisplayedName = "$7205",
  },
  {
    Name = "HyperspaceCostUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
    Cost = 250,
    Time = 25,
    DisplayedName = "$7627",
    DisplayPriority = 1000,
    Description = "$7628",
    UpgradeType = Modifier,
    TargetType = AllShips,
    UpgradeName = "HyperspaceCost",
    UpgradeValue = 0.8,
    TargetName = "Hgn_Mothership",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "$7280",
  },
  {
    Name = "HyperspaceCostUpgrade2",
    RequiredResearch = "HyperspaceCostUpgrade1",
    RequiredSubSystems = "AdvancedResearch & Hyperspace",
    Cost = 500,
    Time = 30,
    DisplayedName = "$7629",
    DisplayPriority = 1000,
    Description = "$7630",
    UpgradeType = Modifier,
    TargetType = AllShips,
    UpgradeName = "HyperspaceCost",
    UpgradeValue = 0.6,
    TargetName = "Hgn_Mothership",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "$7281",
  },
  {
    Name = "AssaultCorvetteHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
    Cost = 500,
    Time = 40,
    DisplayedName = "$7555",
    DisplayPriority = 200,
    Description = "$7556",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7237",
  },
  {
    Name = "AssaultCorvetteHealthUpgrade2",
    RequiredResearch = "AssaultCorvetteHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 800,
    Time = 50,
    DisplayedName = "$7557",
    DisplayPriority = 200,
    Description = "$7558",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7238",
  },
  {
    Name = "AssaultCorvetteMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
    Cost = 300,
    Time = 40,
    DisplayedName = "$7559",
    DisplayPriority = 203,
    Description = "$7560",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7237",
  },
  {
    Name = "AssaultCorvetteMAXSPEEDUpgrade2",
    RequiredResearch = "AssaultCorvetteMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 500,
    Time = 50,
    DisplayedName = "$7561",
    DisplayPriority = 203,
    Description = "$7562",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7238",
  },
  {
    Name = "PulsarCorvetteHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
    Cost = 400,
    Time = 40,
    DisplayedName = "$7563",
    DisplayPriority = 206,
    Description = "$7564",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarCorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7241",
  },
  {
    Name = "PulsarCorvetteHealthUpgrade2",
    RequiredResearch = "PulsarCorvetteHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 750,
    Time = 50,
    DisplayedName = "$7565",
    DisplayPriority = 206,
    Description = "$7566",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarCorvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7242",
  },
  {
    Name = "assaultcorvetteeliteHealthUpgrade1",
    RequiredResearch = "PulsarCorvetteHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7563",
    DisplayPriority = 206,
    Description = "$7564",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_assaultcorvetteelite",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.25,
    Icon = Icon_Health,
    ShortDisplayedName = "$7241",
  },
  {
    Name = "assaultcorvetteeliteHealthUpgrade2",
    RequiredResearch = "PulsarCorvetteHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7565",
    DisplayPriority = 206,
    Description = "$7566",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_assaultcorvetteelite",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.5,
    Icon = Icon_Health,
    ShortDisplayedName = "$7242",
  },
  {
    Name = "PulsarCorvetteMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
    Cost = 300,
    Time = 40,
    DisplayedName = "$7567",
    DisplayPriority = 209,
    Description = "$7568",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarCorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7241",
  },
  {
    Name = "PulsarCorvetteMAXSPEEDUpgrade2",
    RequiredResearch = "PulsarCorvetteMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 500,
    Time = 50,
    DisplayedName = "$7569",
    DisplayPriority = 209,
    Description = "$7570",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_PulsarCorvette",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7242",
  },
  {
    Name = "TorpedoFrigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 800,
    Time = 60,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7244",
  },
  {
    Name = "TorpedoFrigateHealthUpgrade2",
    RequiredResearch = "TorpedoFrigateHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 1400,
    Time = 75,
    DisplayedName = "$7573",
    DisplayPriority = 300,
    Description = "$7574",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7245",
  },
  {
    Name = "TorpedoFrigateMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 500,
    Time = 50,
    DisplayedName = "$7575",
    DisplayPriority = 303,
    Description = "$7576",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7244",
  },
  {
    Name = "TorpedoFrigateMAXSPEEDUpgrade2",
    RequiredResearch = "TorpedoFrigateMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 750,
    Time = 70,
    DisplayedName = "$7577",
    DisplayPriority = 303,
    Description = "$7578",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7245",
  },
  {
    Name = "AssaultFrigateHealthUpgrade1",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 800,
    Time = 60,
    DisplayedName = "$7587",
    DisplayPriority = 312,
    Description = "$7588",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7251",
  },
  {
    Name = "AssaultFrigateHealthUpgrade2",
    RequiredResearch = "AssaultFrigateHealthUpgrade1 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 1400,
    Time = 75,
    DisplayedName = "$7589",
    DisplayPriority = 312,
    Description = "$7590",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7252",
  },
  {
    Name = "AssaultFrigateMAXSPEEDUpgrade1",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 500,
    Time = 50,
    DisplayedName = "$7591",
    DisplayPriority = 315,
    Description = "$7592",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7251",
  },
  {
    Name = "AssaultFrigateMAXSPEEDUpgrade2",
    RequiredResearch = "AssaultFrigateMAXSPEEDUpgrade1 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 750,
    Time = 70,
    DisplayedName = "$7593",
    DisplayPriority = 315,
    Description = "$7594",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7252",
  },
  {
    Name = "IonCannonFrigateHealthUpgrade1",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 800,
    Time = 60,
    DisplayedName = "$7579",
    DisplayPriority = 306,
    Description = "$7580",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonCannonFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7247",
  },
  {
    Name = "IonCannonFrigateHealthUpgrade2",
    RequiredResearch = "IonCannonFrigateHealthUpgrade1 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 1400,
    Time = 75,
    DisplayedName = "$7581",
    DisplayPriority = 306,
    Description = "$7582",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonCannonFrigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7248",
  },
  {
    Name = "IonCannonFrigateMAXSPEEDUpgrade1",
    RequiredResearch = "InstaAdvancedFrigateTech",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 500,
    Time = 50,
    DisplayedName = "$7583",
    DisplayPriority = 309,
    Description = "$7584",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonCannonFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7247",
  },
  {
    Name = "IonCannonFrigateMAXSPEEDUpgrade2",
    RequiredResearch = "IonCannonFrigateMAXSPEEDUpgrade1 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "AdvancedResearch & FrigateProduction",
    Cost = 750,
    Time = 70,
    DisplayedName = "$7585",
    DisplayPriority = 309,
    Description = "$7586",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonCannonFrigate",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7248",
  },
  {
    Name = "MothershipHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 500,
    Time = 30,
    DisplayedName = "$7523",
    DisplayPriority = 41,
    Description = "$7524",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.5,
    Icon = Icon_Health,
    ShortDisplayedName = "$7211",
  },
  {
    Name = "MothershipHealthUpgrade2",
    RequiredResearch = "MothershipHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 750,
    Time = 40,
    DisplayedName = "$7525",
    DisplayPriority = 41,
    Description = "$7526",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2,
    Icon = Icon_Health,
    ShortDisplayedName = "$7212",
  },
  {
    Name = "MothershipMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 500,
    Time = 30,
    DisplayedName = "$7527",
    DisplayPriority = 44,
    Description = "$7528",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7211",
  },
  {
    Name = "MothershipMAXSPEEDUpgrade2",
    RequiredResearch = "MothershipMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 750,
    Time = 40,
    DisplayedName = "$7529",
    DisplayPriority = 44,
    Description = "$7530",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7212",
  },
  {
    Name = "CarrierHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 750,
    Time = 40,
    DisplayedName = "$7531",
    DisplayPriority = 61,
    Description = "$7532",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7221",
  },
  {
    Name = "CarrierHealthUpgrade2",
    RequiredResearch = "CarrierHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 1000,
    Time = 60,
    DisplayedName = "$7533",
    DisplayPriority = 61,
    Description = "$7534",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7222",
  },
  {
    Name = "CarrierMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 500,
    Time = 30,
    DisplayedName = "$7535",
    DisplayPriority = 64,
    Description = "$7536",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7221",
  },
  {
    Name = "CarrierMAXSPEEDUpgrade2",
    RequiredResearch = "CarrierMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 1000,
    Time = 40,
    DisplayedName = "$7537",
    DisplayPriority = 64,
    Description = "$7538",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Carrier",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7222",
  },
  {
    Name = "DestroyerHealthUpgrade1",
    RequiredResearch = "DestroyerTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 1000,
    Time = 60,
    DisplayedName = "$7639",
    DisplayPriority = 405,
    Description = "$7640",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    ShortDisplayedName = "$7274",
    Icon = Icon_Health,
  },
  {
    Name = "DestroyerHealthUpgrade2",
    RequiredResearch = "DestroyerHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 1500,
    Time = 75,
    DisplayedName = "$7641",
    DisplayPriority = 405,
    Description = "$7642",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7275",
  },
  {
    Name = "DestroyerMAXSPEEDUpgrade1",
    RequiredResearch = "DestroyerTech",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 1000,
    Time = 30,
    DisplayedName = "$7643",
    DisplayPriority = 406,
    Description = "$7644",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Destroyer",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7274",
  },
  {
    Name = "DestroyerMAXSPEEDUpgrade2",
    RequiredResearch = "DestroyerMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 1500,
    Time = 40,
    DisplayedName = "$7645",
    DisplayPriority = 406,
    Description = "$7646",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Destroyer",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7275",
  },
  {
    Name = "BattlecruiserHealthUpgrade1",
    RequiredResearch = "BattlecruiserIonWeapons",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 2000,
    Time = 60,
    DisplayedName = "$7595",
    DisplayPriority = 401,
    Description = "$7596",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BattleCruiser",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7254",
  },
  {
    Name = "BattlecruiserHealthUpgrade2",
    RequiredResearch = "BattlecruiserHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 3000,
    Time = 75,
    DisplayedName = "$7597",
    DisplayPriority = 401,
    Description = "$7598",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BattleCruiser",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7255",
  },
  {
    Name = "BattlecruiserMAXSPEEDUpgrade1",
    RequiredResearch = "BattlecruiserIonWeapons",
    RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
    Cost = 1000,
    Time = 30,
    DisplayedName = "$7599",
    DisplayPriority = 404,
    Description = "$7600",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BattleCruiser",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7254",
  },
  {
    Name = "BattlecruiserMAXSPEEDUpgrade2",
    RequiredResearch = "BattlecruiserMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & CapShipProduction",
    Cost = 1500,
    Time = 40,
    DisplayedName = "$7601",
    DisplayPriority = 404,
    Description = "$7602",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_BattleCruiser",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7255",
  },
  {
    Name = "ShipyardHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
    Cost = 750,
    Time = 30,
    DisplayedName = "$7619",
    DisplayPriority = 1200,
    Description = "$7620",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Shipyard",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7271",
  },
  {
    Name = "ShipyardHealthUpgrade2",
    RequiredResearch = "ShipyardHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch & Hyperspace",
    Cost = 1500,
    Time = 40,
    DisplayedName = "$7621",
    DisplayPriority = 1200,
    Description = "$7622",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Shipyard",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7272",
  },
  {
    Name = "ShipyardMAXSPEEDUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
    Cost = 500,
    Time = 30,
    DisplayedName = "$7623",
    DisplayPriority = 1203,
    Description = "$7624",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Shipyard",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7271",
  },
  {
    Name = "ShipyardMAXSPEEDUpgrade2",
    RequiredResearch = "ShipyardMAXSPEEDUpgrade1",
    RequiredSubSystems = "AdvancedResearch & Hyperspace",
    Cost = 1500,
    Time = 40,
    DisplayedName = "$7625",
    DisplayPriority = 1203,
    Description = "$7626",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_Shipyard",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7272",
  },
  {
    Name = "GunTurretHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 500,
    Time = 30,
    DisplayedName = "$7603",
    DisplayPriority = 600,
    Description = "$7604",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_GunTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7257",
  },
  {
    Name = "GunTurretHealthUpgrade2",
    RequiredResearch = "GunTurretHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 800,
    Time = 40,
    DisplayedName = "$7605",
    DisplayPriority = 600,
    Description = "$7606",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_GunTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7258",
  },
  {
    Name = "IonTurretHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 500,
    Time = 30,
    DisplayedName = "$7607",
    DisplayPriority = 603,
    Description = "$7608",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7261",
  },
  {
    Name = "IonTurretHealthUpgrade2",
    RequiredResearch = "IonTurretHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 800,
    Time = 40,
    DisplayedName = "$7609",
    DisplayPriority = 603,
    Description = "$7610",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_IonTurret",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7262",
  },
  {
    Name = "ResourceCollectorHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 400,
    Time = 40,
    DisplayedName = "$7611",
    DisplayPriority = 701,
    Description = "$7612",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_ResourceCollector",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.5,
    Icon = Icon_Health,
    ShortDisplayedName = "$7264",
  },
  {
    Name = "ResourceCollectorHealthUpgrade2",
    RequiredResearch = "ResourceCollectorHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 800,
    Time = 60,
    DisplayedName = "$7613",
    DisplayPriority = 701,
    Description = "$7614",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_ResourceCollector",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2,
    Icon = Icon_Health,
    ShortDisplayedName = "$7265",
  },
  {
    Name = "ResourceControllerHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 500,
    Time = 30,
    DisplayedName = "$7267",
    DisplayPriority = 704,
    Description = "$7616",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_ResourceController",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7267",
  },
  {
    Name = "ResourceControllerHealthUpgrade2",
    RequiredResearch = "ResourceControllerHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1000,
    Time = 40,
    DisplayedName = "$7617",
    DisplayPriority = 704,
    Description = "$7618",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_ResourceController",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7268",
  },
  {
    Name = "SensorsDowngrade1",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Sensors Downgrade1",
    DisplayPriority = 1210,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "PrimarySensorsRange",
    UpgradeValue = 0.3,
  },
  {
    Name = "SensorsDowngrade2",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Sensors Downgrade2",
    DisplayPriority = 1211,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "SecondarySensorsRange",
    UpgradeValue = 0.3,
  },
  {
    Name = "SensorsDowngrade3",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Sensors Downgrade3",
    DisplayPriority = 1212,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "VisualRange",
    UpgradeValue = 0.3,
  },
  {
    Name = "SensorsBackToNormal1",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "SensorsBackToNormal1",
    DisplayPriority = 1213,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "PrimarySensorsRange",
    UpgradeValue = 1,
  },
  {
    Name = "SensorsBackToNormal2",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "SensorsBackToNormal2",
    DisplayPriority = 1214,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "SecondarySensorsRange",
    UpgradeValue = 1,
  },
  {
    Name = "SensorsBackToNormal3",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "SensorsBackToNormal3",
    DisplayPriority = 1215,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_MotherShip",
    UpgradeName = "VisualRange",
    UpgradeValue = 1,
  },
  {
    Name = "AssaultCorvetteEliteWeaponUpgrade",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Elite Assault Corvette Weapon Upgrade",
    DisplayPriority = 1204,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AssaultCorvetteElite",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 2,
  },
  {
    Name = "AttackBomberEliteWeaponUpgrade",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Elite Attack Bomber Weapon Upgrade",
    DisplayPriority = 1205,
    Description = "",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Hgn_AttackBomberElite",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 2,
  },
  {
    Name = "MoverHealthUpgrade",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Mover health upgrade",
    DisplayPriority = 41,
    Description = "Upgrades Mover health",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Mover",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 5,
  },
  {
    Name = "MoverHealthDowngrade",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Mover health downgrade",
    DisplayPriority = 41,
    Description = "Downgrades Mover health",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Mover",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1,
  },
  {
    Name = "FrigateHealthUpgradeSPGAME",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 800,
    Time = 60,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2.5,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_LOW",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2.5,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_MED",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 3.5,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_HIGH",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_Destroyer",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 4.5,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_1",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.1,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_2",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.2,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_3",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.3,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_4",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.4,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_5",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.5,
  },
  {
    Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_6",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 0.6,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_M10_LVL_1",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_M10_LVL_2",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 3,
  },
  {
    Name = "KeeperHealthUpgradeSPGAME_M10_LVL_3",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_DestroyerM10",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 4,
  },
  {
    Name = "AttackDroidHealthUpgradeSPGAME_LOW",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2,
  },
  {
    Name = "AttackDroidHealthUpgradeSPGAME_MED",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 3,
  },
  {
    Name = "AttackDroidHealthUpgradeSPGAME_HIGH",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 4,
  },
  {
    Name = "AttackDroidWeaponUpgradeSPGAME_LOW",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 1.3,
  },
  {
    Name = "AttackDroidWeaponUpgradeSPGAME_MED",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 1.6,
  },

  {
    Name = "AttackDroidWeaponUpgradeSPGAME_HIGH",
    RequiredResearch = "RESEARCH HACK",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7571",
    DisplayPriority = 300,
    Description = "$7572",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "Kpr_AttackDroid",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 2,
  },
  {
    Name = "attackdroideliteWeapons",
    RequiredResearch = "TorpedoFrigateHealthUpgrade2 & TorpedoFrigateMAXSPEEDUpgrade2",
    RequiredSubSystems = "AdvancedResearch & FighterProduction",
    Cost = 1500,
    Time = 80,
    DisplayedName = "$7955",
    DisplayPriority = 520,
    Description = "$7956",                  
    TargetType = Ship,
    TargetName = "hgn_attackdroidelite",
    Icon = Icon_Tech,
    ShortDisplayedName = "$1708",
  },
  {
    Name = "AttackDroidHealthUpgrade1",
    RequiredResearch = "attackdroideliteWeapons",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1000,
    Time = 60,
    DisplayedName = "$7957",
    DisplayPriority = 521,
    Description = "$7958",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_attackdroidelite",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 2,
    Icon = Icon_Health,
    ShortDisplayedName = "$7959",
  },
  {
    Name = "AttackDroidHealthUpgrade2",
    RequiredResearch = "AttackDroidHealthUpgrade1 & DestroyerHealthUpgrade2 & DestroyerMAXSPEEDUpgrade2",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 2000,
    Time = 80,
    DisplayedName = "$7960",
    DisplayPriority = 525,
    Description = "$7961",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_attackdroidelite",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7962",
  },
  {
    Name = "AttackDroidHealthUpgrade3",
    RequiredResearch = "AttackDroidHealthUpgrade2 & BattlecruiserHealthUpgrade2 & BattlecruiserMAXSPEEDUpgrade2",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 3000,
    Time = 100,
    DisplayedName = "$7963",
    DisplayPriority = 529,
    Description = "$7964",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_attackdroidelite",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 4.5,
    Icon = Icon_Health,
    ShortDisplayedName = "$7965",
  },
  {
    Name = "AttackDroidWeaponUpgrade1",
    RequiredResearch = "attackdroideliteWeapons",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1000,
    Time = 60,
    DisplayedName = "$7966",
    DisplayPriority = 1,
    Description = "$7967",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_attackdroidelite",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 1.5,
    Icon = Icon_Attack,
    ShortDisplayedName = "$7959",
  },
  {
    Name = "AttackDroidWeaponUpgrade2",
    RequiredResearch = "AttackDroidWeaponUpgrade1 & DestroyerHealthUpgrade2 & DestroyerMAXSPEEDUpgrade2",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 2000,
    Time = 80,
    DisplayedName = "$7968",
    DisplayPriority = 1,
    Description = "$7969",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_attackdroidelite",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$7962",
  },
  {
    Name = "AttackDroidWeaponUpgrade3",
    RequiredResearch = "AttackDroidWeaponUpgrade2 & BattlecruiserHealthUpgrade2 & BattlecruiserMAXSPEEDUpgrade2",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 3000,
    Time = 100,
    DisplayedName = "$7970",
    DisplayPriority = 1,
    Description = "$7971",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_attackdroidelite",
    UpgradeName = "WeaponDamage",
    UpgradeValue = 2.5,
    Icon = Icon_Attack,
    ShortDisplayedName = "$7965",
  },
  {
    Name = "AttackDroidMAXSPEEDUpgrade1",
    RequiredResearch = "attackdroideliteWeapons",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 600,
    Time = 40,
    DisplayedName = "$7972",
    DisplayPriority = 542,
    Description = "$7973",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_attackdroidelite",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.32,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7959",
  },
  {
    Name = "AttackDroidMAXSPEEDUpgrade2",
    RequiredResearch = "AttackDroidMAXSPEEDUpgrade1 & DestroyerHealthUpgrade2 & DestroyerMAXSPEEDUpgrade2",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1000,
    Time = 60,
    DisplayedName = "$7974",
    DisplayPriority = 545,
    Description = "$7975",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_attackdroidelite",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.52,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7962",
  },
  {
    Name = "ShipyardelohimHealthUpgrade1",
    RequiredResearch = "ShipyardHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7619",
    DisplayPriority = 1200,
    Description = "$7620",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_shipyard_elohim",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7271",
  },
  {
    Name = "ShipyardelohimHealthUpgrade2",
    RequiredResearch = "ShipyardHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7621",
    DisplayPriority = 1200,
    Description = "$7622",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_shipyard_elohim",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7272",
  },
  {
    Name = "ShipyardelohimMAXSPEEDUpgrade1",
    RequiredResearch = "ShipyardHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7623",
    DisplayPriority = 1203,
    Description = "$7624",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_shipyard_elohim",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7271",
  },
  {
    Name = "ShipyardelohimMAXSPEEDUpgrade2",
    RequiredResearch = "ShipyardHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7625",
    DisplayPriority = 1203,
    Description = "$7626",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_shipyard_elohim",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7272",
  },
  {
    Name = "ShipyardspgHealthUpgrade1",
    RequiredResearch = "ShipyardHealthUpgrade",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7619",
    DisplayPriority = 1200,
    Description = "$7620",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_shipyard_spg",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$7271",
  },
  {
    Name = "ShipyardspgHealthUpgrade2",
    RequiredResearch = "ShipyardHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7621",
    DisplayPriority = 1200,
    Description = "$7622",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_shipyard_spg",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$7272",
  },
  {
    Name = "ShipyardspgMAXSPEEDUpgrade1",
    RequiredResearch = "ShipyardHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7623",
    DisplayPriority = 1203,
    Description = "$7624",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_shipyard_spg",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.2,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7271",
  },
  {
    Name = "ShipyardspgMAXSPEEDUpgrade2",
    RequiredResearch = "ShipyardHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7625",
    DisplayPriority = 1203,
    Description = "$7626",
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "hgn_shipyard_spg",
    UpgradeName = "MAXSPEED",
    UpgradeValue = 1.35,
    Icon = Icon_Speed,
    ShortDisplayedName = "$7272",
  },
--------------------------------------
--------------------------------------
--------------------------------------
--------------------------------------
  {
    Name = "hgn_AirWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8040",
    DisplayPriority = 100,
    Description = "$8041",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8040",
  },
  {
    Name = "hgn_AirWeaponUpgrade2",
    RequiredResearch = "hgn_AirWeaponUpgrade1",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8042",
    DisplayPriority = 100,
    Description = "$8043",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8042",
  },
  {
    Name = "hgn_AirWeaponUpgrade3",
    RequiredResearch = "hgn_AirWeaponUpgrade2",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8044",
    DisplayPriority = 100,
    Description = "$8045",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8044",
  },
  {
    Name = "hgn_AirHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8046",
    DisplayPriority = 101,
    Description = "$8047",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8046",
  },
  {
    Name = "hgn_AirHealthUpgrade2",
    RequiredResearch = "hgn_AirHealthUpgrade1",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8048",
    DisplayPriority = 101,
    Description = "$8049",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8048",
  },
  {
    Name = "hgn_AirHealthUpgrade3",
    RequiredResearch = "hgn_AirHealthUpgrade2",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8050",
    DisplayPriority = 101,
    Description = "$8051",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8050",
  },
  {
    Name = "hgn_ShipWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FrigateProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8052",
    DisplayPriority = 300,
    Description = "$8053",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8052",
  },
  {
    Name = "hgn_ShipWeaponUpgrade2",
    RequiredResearch = "hgn_ShipWeaponUpgrade1",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8054",
    DisplayPriority = 300,
    Description = "$8055",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8054",
  },
  {
    Name = "hgn_ShipWeaponUpgrade3",
    RequiredResearch = "hgn_ShipWeaponUpgrade2",
    RequiredSubSystems = "AdvancedResearch & AdvancedCapShipProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8056",
    DisplayPriority = 300,
    Description = "$8057",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8056",
  },
  {
    Name = "hgn_ShipHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FrigateProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8058",
    DisplayPriority = 301,
    Description = "$8059",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8058",
  },
  {
    Name = "hgn_ShipHealthUpgrade2",
    RequiredResearch = "hgn_ShipHealthUpgrade1",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8060",
    DisplayPriority = 301,
    Description = "$8061",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8060",
  },
  {
    Name = "hgn_ShipHealthUpgrade3",
    RequiredResearch = "hgn_ShipHealthUpgrade2",
    RequiredSubSystems = "AdvancedResearch & AdvancedCapShipProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8062",
    DisplayPriority = 301,
    Description = "$8063",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8062",
  },
  {
    Name = "hgn_PlatformWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8064",
    DisplayPriority = 300,
    Description = "$8065",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8064",
  },
  {
    Name = "hgn_PlatformWeaponUpgrade2",
    RequiredResearch = "hgn_PlatformWeaponUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8066",
    DisplayPriority = 300,
    Description = "$8067",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8066",
  },
  {
    Name = "hgn_PlatformWeaponUpgrade3",
    RequiredResearch = "hgn_PlatformWeaponUpgrade2",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8068",
    DisplayPriority = 300,
    Description = "$8069",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.5,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8068",
  },
  {
    Name = "hgn_PlatformHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8070",
    DisplayPriority = 201,
    Description = "$8071",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8070",
  },
  {
    Name = "hgn_PlatformHealthUpgrade2",
    RequiredResearch = "hgn_PlatformHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8072",
    DisplayPriority = 201,
    Description = "$8073",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$8072",
  },
  {
    Name = "hgn_PlatformHealthUpgrade3",
    RequiredResearch = "hgn_PlatformHealthUpgrade2",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8074",
    DisplayPriority = 201,
    Description = "$8075",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$8074",
  },
  {
    Name = "hgn_AirWeaponUpgrade11",
    RequiredResearch = "hgn_AirWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8040",
    DisplayPriority = 100,
    Description = "$8041",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8040",
  },
  {
    Name = "hgn_AirWeaponUpgrade21",
    RequiredResearch = "hgn_AirWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8042",
    DisplayPriority = 100,
    Description = "$8043",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8042",
  },
  {
    Name = "hgn_AirWeaponUpgrade31",
    RequiredResearch = "hgn_AirWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8044",
    DisplayPriority = 100,
    Description = "$8045",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8044",
  },
  {
    Name = "hgn_AirHealthUpgrade11",
    RequiredResearch = "hgn_AirHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8046",
    DisplayPriority = 101,
    Description = "$8047",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8046",
  },
  {
    Name = "hgn_AirHealthUpgrade21",
    RequiredResearch = "hgn_AirHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8048",
    DisplayPriority = 101,
    Description = "$8049",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8048",
  },
  {
    Name = "hgn_AirHealthUpgrade31",
    RequiredResearch = "hgn_AirHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8050",
    DisplayPriority = 101,
    Description = "$8051",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8050",
  },
  {
    Name = "hgn_ShipWeaponUpgrade11",
    RequiredResearch = "hgn_ShipWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8052",
    DisplayPriority = 300,
    Description = "$8053",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.15,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8052",
  },
  {
    Name = "hgn_ShipWeaponUpgrade21",
    RequiredResearch = "hgn_ShipWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8054",
    DisplayPriority = 300,
    Description = "$8055",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.25,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8054",
  },
  {
    Name = "hgn_ShipWeaponUpgrade31",
    RequiredResearch = "hgn_ShipWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8056",
    DisplayPriority = 300,
    Description = "$8057",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.35,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8056",
  },
  {
    Name = "hgn_ShipHealthUpgrade11",
    RequiredResearch = "hgn_ShipHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8058",
    DisplayPriority = 301,
    Description = "$8059",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8058",
  },
  {
    Name = "hgn_ShipHealthUpgrade21",
    RequiredResearch = "hgn_ShipHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8060",
    DisplayPriority = 301,
    Description = "$8061",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$8060",
  },
  {
    Name = "hgn_ShipHealthUpgrade31",
    RequiredResearch = "hgn_ShipHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8062",
    DisplayPriority = 301,
    Description = "$8063",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$8062",
  },
--AI behaviour	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed	
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.025,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.05,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.075,
	},
--AI resource rate	
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},			
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")