Ship = 0
SubSystem = 1
build =  { 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Swarmer", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "FighterProduction", 
        DisplayPriority = 2, 
        DisplayedName = "$9000", 
        Description = "$9001", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_AssaultSwarmer", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "FighterProduction", 
        DisplayPriority = 3, 
        DisplayedName = "$9002", 
        Description = "$9003", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_LanceSwarmer", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Lance", 
        DisplayPriority = 5, 
        DisplayedName = "$9004",
        Description = "$9005",
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_Variationswarmer",
        RequiredResearch = "", 
        RequiredFleetSubSystems = "CorvetteProduction",
        DisplayPriority = 10,
        DisplayedName = "$9010",
        Description = "$9011", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_AdvancedSwarmer",
        RequiredResearch = "", 
        RequiredFleetSubSystems = "ClusterGun",
        DisplayPriority = 11,
        DisplayedName = "$9006",
        Description = "$9007", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_AdvancedAssaultSwarmer", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Missile", 
        DisplayPriority = 13, 
        DisplayedName = "$9008", 
        Description = "$9009", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_Fuelpod", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "FrigateProduction", 
        DisplayPriority = 20, 
        DisplayedName = "$9014", 
        Description = "$9015", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Multibeamfrigate", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "CapShipProduction", 
        DisplayPriority = 23, 
        DisplayedName = "$9016", 
        Description = "$9017", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_militaryfuelpod", 
        RequiredResearch = "KadCapital1", 
        RequiredFleetSubSystems = "FrigateProduction", 
        DisplayPriority = 25, 
        DisplayedName = "$9018", 
        Description = "$9019", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Carrier", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 30, 
        DisplayedName = "$9026", 
        Description = "$9027", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "kad_guardianspirit", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CapShip", 
        DisplayPriority = 31, 
        DisplayedName = "$9012", 
        Description = "$9013", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "kad_mothership", 
        RequiredResearch = "KadCapital1", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 32, 
        DisplayedName = "$9020", 
        Description = "$9021", 
    },
    --{ 
        --Type = Ship, 
        --ThingToBuild = "kad_mothershipDark", 
        --RequiredResearch = "", 
        --RequiredShipSubSystems = "Hyperspace", 
        --DisplayPriority = 32, 
        --DisplayedName = "$9024", 
        --Description = "$9025", 
    --},
    { 
        Type = Ship, 
        ThingToBuild = "kad_mothershipLight", 
        RequiredResearch = "KadCapital1", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 33, 
        DisplayedName = "$9022", 
        Description = "$9023", 
    },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Araneid", 
        RequiredResearch = "KadCapital1", 
        RequiredFleetSubSystems = "PlatformProduction", 
        DisplayPriority = 41, 
        DisplayedName = "$9034", 
        Description = "$9035", 
    },
  { 
     Type = Ship, 
     ThingToBuild = "Kad_gunturret", 
     RequiredResearch = "", 
     RequiredFleetSubSystems = "", 
     DisplayPriority = 42, 
     DisplayedName = "$9030", 
     Description = "$9031", 
  },
    { 
        Type = Ship, 
        ThingToBuild = "Kad_Salvager", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 50, 
        DisplayedName = "$9038", 
        Description = "$9039",
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_probe", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 51, 
        DisplayedName = "$9042", 
        Description = "$9043", 
    }, 
    { 
        Type = Ship, 
        ThingToBuild = "kad_Resourcefuelpod", 
        RequiredResearch = "KadCapital1", 
        RequiredFleetSubSystems = "PlatformProduction", 
        DisplayPriority = 53, 
        DisplayedName = "$9040", 
        Description = "$9041", 
    }, 
     --{ 
        --Type = Ship, 
        --ThingToBuild = "Kad_proximitysensor", 
        --RequiredResearch = "proximitysensor", 
        --RequiredShipSubSystems = "", 
        --DisplayPriority = 55, 
        --DisplayedName = "$9044", 
        --Description = "$9045", 
    --}, 
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_m_capship",
    	RequiredResearch = "",
    	RequiredFleetSubSystems = "FrigateProduction",
    	DisplayPriority = 1,
    	DisplayedName = "$9050",
    	Description = "$9051",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_m_capshipadvanced",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "CapShip",
    	DisplayPriority = 2,
    	DisplayedName = "$9052",
    	Description = "$9053",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_m_ioncannon",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "CapShipAdvanced",
    	DisplayPriority = 3,
    	DisplayedName = "$9070",
    	Description = "$9071",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_c_fighter",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "",
    	DisplayPriority = 1,
    	DisplayedName = "$9054",
    	Description = "$9055",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_c_Lance",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "FighterProduction",
    	DisplayPriority = 2,
    	DisplayedName = "$9056",
    	Description = "$9057",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_c_frigate",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "FighterProduction",
    	DisplayPriority = 3,
    	DisplayedName = "$9064",
    	Description = "$9065",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_c_multibeam",
    	RequiredResearch = "KadCapital1",
    	RequiredShipSubSystems = "FrigateProduction",
    	DisplayPriority = 4,
    	DisplayedName = "$9066",
    	Description = "$9067",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_c_platformcontrol",
    	RequiredResearch = "KadCapital1",
    	RequiredShipSubSystems = "FighterProduction",
    	DisplayPriority = 5,
    	DisplayedName = "$9062",
    	Description = "$9063",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_c_LiquidMetal",
    	RequiredResearch = "KadCapital1",
    	RequiredShipSubSystems = "FighterProduction",
    	DisplayPriority = 6,
    	DisplayedName = "$9058",
    	Description = "$9059",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_c_ClusterGun",
    	RequiredResearch = "KadCapital2",
    	RequiredShipSubSystems = "CorvetteProduction",
    	DisplayPriority = 7,
    	DisplayedName = "$9060",
    	Description = "$9061",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_c_Missile",
    	RequiredResearch = "KadCapital2",
    	RequiredShipSubSystems = "CapShipProduction",
    	DisplayPriority = 8,
    	DisplayedName = "$9068",
    	Description = "$9069",
    },
    {
    	Type = SubSystem,
    	ThingToBuild = "kad_Module_firecontrol",
    	RequiredResearch = "",
    	RequiredShipSubSystems = "",
    	DisplayPriority = 9,
    	DisplayedName = "",
    	Description = "",
    },

}
