dofilepath("Data:leveldata/multiplayer/lib/FXGDeathmatch_Data.lua")

Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
BLUE = 0
YELLOW = 1
RED = nil
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "FXGDM",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
  },
  {
    Name = "Branch1",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "地方卫队",
    DisplayPriority = 1,
    Description = "希格拉专司民间治安的地方巡逻卫队拥有希格拉最精锐的艇级单位，在遇到大型图拉尼舰队等难缠的敌人时，还能随时得到附近的基斯舰队的支援\n可召唤鱼雷护卫舰进入战场\n能够建造重型脉冲炮艇代替脉冲炮艇\n鱼雷护卫舰反舰鱼雷\n建造主力舰模块后立即获得一艘航母\n航母移动速度更快",
    UpgradeType = BLUE,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Health,
    ShortDisplayedName = "地方卫队",
  },
  {
    Name = "Branch2",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "特种部队",
    DisplayPriority = 2,
    Description = "这支秘密舰队的人员大部分由专注军事的索班基斯精英官兵所组成，负责处理希格拉的各种紧急或敏感任务。\n可召唤强袭登陆舰进入战场\n能够建造攻击轰炸机代替轰炸机\n能够建造强袭登陆舰代替登陆舰\n建造主力舰模块后立即获得一艘驱逐舰\n驱逐舰移动速度更快",
    UpgradeType = RED,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Attack,
    ShortDisplayedName = "特种部队",
  },
  {
    Name = "Branch3",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "联合舰队",
    DisplayPriority = 3,
    Description = "与本土防御由各个基斯舰队分别负责不同，戴阿米德设立了联合舰队负责希格拉的对外军事行动。这支舰队又称第九舰队，拥有光荣而辉煌的历史，以及各个基斯最杰出的军人。\n可召唤防空护卫舰进入战场\n能够建造战斗拦截机代替拦截机\n防空护卫舰EMP武器系统\n建造护卫舰生产设施后立即获得主力舰生产设施\n战术巡洋舰移动速度更快",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "联合舰队",
  },
  {
    Name = "Sumon_TorpedoFrigate",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "FrigateProduction",
    Cost = FXG_Sumon_Data.Hiigaran[1].Cost,
    Time = 100,
    DisplayedName = "召唤鱼雷护卫舰进入战场",
    DisplayPriority = 0,
    Description = "鱼雷护卫舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"hgn_torpedofrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "鱼雷护卫舰",
  },
  {
    Name = "Sumon_MarineFrigate",
    RequiredResearch = "Branch2 & InstaAdvancedFrigateTech",
    RequiredSubSystems = "FrigateProduction",
    Cost = FXG_Sumon_Data.Hiigaran[2].Cost,
    Time = 100,
    DisplayedName = "召唤强袭登陆舰进入战场",
    DisplayPriority = 0,
    Description = "强袭登陆舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"hgn_assaultmarinefrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "强袭登陆舰",
  },
  {
    Name = "Sumon_AssaultFrigate",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "FrigateProduction",
    Cost = FXG_Sumon_Data.Hiigaran[3].Cost,
    Time = 100,
    DisplayedName = "召唤防空护卫舰进入战场",
    DisplayPriority = 0,
    Description = "防空护卫舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"hgn_assaultfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "防空护卫舰",
  },
  {
    Name = "InstantBuild_Carrier",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "CapShipProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_Destroyer",
    RequiredResearch = "Branch2",
    RequiredSubSystems = "CapShipProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_CapShipProduction",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "Hgn_lbc_AFTech",
    RequiredResearch = "",
    RequiredSubSystems = "Never",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "Hgn_LightCruiser",
  },
  {
    Name = "hgnTech",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "Hgn_Mothership",
  },
  {
    Name = "InstaAdvancedFrigateTech",
    RequiredResearch = "",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "Hgn_Mothership",
  },
  {
    Name = "ImprovedTorpedo",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "$7515",
    DisplayPriority = 1,
    Description = "$7516",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_TorpedoFrigate",
    UpgradeName = "UseSpecialWeaponsInNormalAttack",
    Icon = Icon_Attack,
    ShortDisplayedName = "$7207",
  },
  {
    Name = "RepairAbility",
    RequiredResearch = "",
    RequiredSubSystems = "Research | AdvancedResearch",
    Cost = 300,
    Time = 20,
    DisplayedName = "$7511",
    DisplayPriority = 26,
    Description = "$7512",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Hgn_ResourceCollector",
    UpgradeName = "Repair",
    Icon = Icon_Repair,
    ShortDisplayedName = "$7205",
  },
--------------------------------------
--------------------------------------
--------------------------------------
--------------------------------------
  {
    Name = "hgn_AirWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8040",
    DisplayPriority = 100,
    Description = "$8041",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8040",
  },
  {
    Name = "hgn_AirWeaponUpgrade2",
    RequiredResearch = "hgn_AirWeaponUpgrade1",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8042",
    DisplayPriority = 100,
    Description = "$8043",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8042",
  },
  {
    Name = "hgn_AirWeaponUpgrade3",
    RequiredResearch = "hgn_AirWeaponUpgrade2",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8044",
    DisplayPriority = 100,
    Description = "$8045",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8044",
  },
  {
    Name = "hgn_AirHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8046",
    DisplayPriority = 101,
    Description = "$8047",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8046",
  },
  {
    Name = "hgn_AirHealthUpgrade2",
    RequiredResearch = "hgn_AirHealthUpgrade1",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8048",
    DisplayPriority = 101,
    Description = "$8049",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8048",
  },
  {
    Name = "hgn_AirHealthUpgrade3",
    RequiredResearch = "hgn_AirHealthUpgrade2",
    RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8050",
    DisplayPriority = 101,
    Description = "$8051",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8050",
  },
  {
    Name = "hgn_ShipWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FrigateProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8052",
    DisplayPriority = 300,
    Description = "$8053",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8052",
  },
  {
    Name = "hgn_ShipWeaponUpgrade2",
    RequiredResearch = "hgn_ShipWeaponUpgrade1",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8054",
    DisplayPriority = 300,
    Description = "$8055",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8054",
  },
  {
    Name = "hgn_ShipWeaponUpgrade3",
    RequiredResearch = "hgn_ShipWeaponUpgrade2",
    RequiredSubSystems = "AdvancedResearch & AdvancedCapShipProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8056",
    DisplayPriority = 300,
    Description = "$8057",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8056",
  },
  {
    Name = "hgn_ShipHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FrigateProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8058",
    DisplayPriority = 301,
    Description = "$8059",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8058",
  },
  {
    Name = "hgn_ShipHealthUpgrade2",
    RequiredResearch = "hgn_ShipHealthUpgrade1",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8060",
    DisplayPriority = 301,
    Description = "$8061",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8060",
  },
  {
    Name = "hgn_ShipHealthUpgrade3",
    RequiredResearch = "hgn_ShipHealthUpgrade2",
    RequiredSubSystems = "AdvancedResearch & AdvancedCapShipProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8062",
    DisplayPriority = 301,
    Description = "$8063",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8062",
  },
  {
    Name = "hgn_PlatformWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8064",
    DisplayPriority = 300,
    Description = "$8065",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8064",
  },
  {
    Name = "hgn_PlatformWeaponUpgrade2",
    RequiredResearch = "hgn_PlatformWeaponUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8066",
    DisplayPriority = 300,
    Description = "$8067",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8066",
  },
  {
    Name = "hgn_PlatformWeaponUpgrade3",
    RequiredResearch = "hgn_PlatformWeaponUpgrade2",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8068",
    DisplayPriority = 300,
    Description = "$8069",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.5,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8068",
  },
  {
    Name = "hgn_PlatformHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8070",
    DisplayPriority = 201,
    Description = "$8071",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8070",
  },
  {
    Name = "hgn_PlatformHealthUpgrade2",
    RequiredResearch = "hgn_PlatformHealthUpgrade1",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8072",
    DisplayPriority = 201,
    Description = "$8073",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$8072",
  },
  {
    Name = "hgn_PlatformHealthUpgrade3",
    RequiredResearch = "hgn_PlatformHealthUpgrade2",
    RequiredSubSystems = "AdvancedResearch",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8074",
    DisplayPriority = 201,
    Description = "$8075",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Platform",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$8074",
  },
  {
    Name = "hgn_AirWeaponUpgrade11",
    RequiredResearch = "hgn_AirWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8040",
    DisplayPriority = 100,
    Description = "$8041",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8040",
  },
  {
    Name = "hgn_AirWeaponUpgrade21",
    RequiredResearch = "hgn_AirWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8042",
    DisplayPriority = 100,
    Description = "$8043",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8042",
  },
  {
    Name = "hgn_AirWeaponUpgrade31",
    RequiredResearch = "hgn_AirWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8044",
    DisplayPriority = 100,
    Description = "$8045",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8044",
  },
  {
    Name = "hgn_AirHealthUpgrade11",
    RequiredResearch = "hgn_AirHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8046",
    DisplayPriority = 101,
    Description = "$8047",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8046",
  },
  {
    Name = "hgn_AirHealthUpgrade21",
    RequiredResearch = "hgn_AirHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8048",
    DisplayPriority = 101,
    Description = "$8049",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8048",
  },
  {
    Name = "hgn_AirHealthUpgrade31",
    RequiredResearch = "hgn_AirHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8050",
    DisplayPriority = 101,
    Description = "$8051",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8050",
  },
  {
    Name = "hgn_ShipWeaponUpgrade11",
    RequiredResearch = "hgn_ShipWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8052",
    DisplayPriority = 300,
    Description = "$8053",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.15,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8052",
  },
  {
    Name = "hgn_ShipWeaponUpgrade21",
    RequiredResearch = "hgn_ShipWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8054",
    DisplayPriority = 300,
    Description = "$8055",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.25,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8054",
  },
  {
    Name = "hgn_ShipWeaponUpgrade31",
    RequiredResearch = "hgn_ShipWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8056",
    DisplayPriority = 300,
    Description = "$8057",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.35,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8056",
  },
  {
    Name = "hgn_ShipHealthUpgrade11",
    RequiredResearch = "hgn_ShipHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8058",
    DisplayPriority = 301,
    Description = "$8059",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8058",
  },
  {
    Name = "hgn_ShipHealthUpgrade21",
    RequiredResearch = "hgn_ShipHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8060",
    DisplayPriority = 301,
    Description = "$8061",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$8060",
  },
  {
    Name = "hgn_ShipHealthUpgrade31",
    RequiredResearch = "hgn_ShipHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8062",
    DisplayPriority = 301,
    Description = "$8063",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$8062",
  },
--AI behaviour	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed	
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.025,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.05,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.075,
	},
--AI resource rate	
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},			
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")