Ship = 0
SubSystem = 1
build =
{
--Fighters---------------
  {
	Type =	SubSystem,
	ThingToBuild =	"Kus_r",
    RequiredResearch = "",
    RequiredFleetSubSystems = "! Research",
    DisplayPriority = 110,
    DisplayedName = "$10589",
    Description = "$10590",
  },
  {
	Type =	SubSystem,
	ThingToBuild =	"Kus_ra",
    RequiredResearch = "CorvetteTech",
    RequiredFleetSubSystems = "! RA",
    DisplayPriority = 111,
    DisplayedName = "$10609",
    Description = "$10610",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Kus_r_PlasmaBombs",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & (!FighterProduction)",
    DisplayPriority = 1,
    DisplayedName = "$10611",
    Description = "$10612",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Kus_ra_gravitywell",
    RequiredResearch = "CorvetteTech",
    RequiredFleetSubSystems = "!GravityWell",
    DisplayPriority = 4,
    DisplayedName = "$10653",
    Description = "$10654",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Kus_r_Corvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & (!CorvetteProduction)",
    DisplayPriority = 2,
    DisplayedName = "$10615",
    Description = "$10616",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Kus_r_HeavyCorvette",
    RequiredResearch = "CorvetteTech & PlasmaBombsTech",
    RequiredFleetSubSystems = "Research  & (!HeavyCorvette)",
    DisplayPriority = 5,
    DisplayedName = "$10617",
    Description = "$10618",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Kus_r_rapidturret",
    RequiredResearch = "CorvetteTech",
    RequiredFleetSubSystems = "Research & (!RapidTurret)",
    DisplayPriority = 3,
    DisplayedName = "$10619",
    Description = "$10620",
  },
 	{
    Type = SubSystem,
    ThingToBuild = "Kus_ra_capship",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA & (!CapShipProduction)",
    DisplayPriority = 3,
    DisplayedName = "$10625",
    Description = "$10626",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Kus_r_ioncannon",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA & (!IonCannon)",
    DisplayPriority = 2,
    DisplayedName = "$10621",
    Description = "$10622",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Kus_ra_heavygun",
    RequiredResearch = "ioncannonTech",
    RequiredFleetSubSystems = "RA & CapShipProduction & (!heavygun)",
    DisplayPriority = 5,
    DisplayedName = "$10629",
    Description = "$10630",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Kus_ra_missile",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA & CapShipProduction & (!missile)",
    DisplayPriority = 4,
    DisplayedName = "$10627",
    Description = "$10628",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Kus_r_cloakmodule",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA & !CloakFighter",
    DisplayPriority = 1,
    DisplayedName = "$10649",
    Description = "$10650",
  },

  {
    Type = Ship,
    ThingToBuild = "Kus_ResearchShip_1",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & (!FighterProduction)",
    DisplayPriority = 1,
    DisplayedName = "$10611",
    Description = "$10612",
  },
  {
    Type = Ship,
    ThingToBuild = "Kus_ResearchShip_2",
    RequiredResearch = "CorvetteTech",
    RequiredFleetSubSystems = "!GravityWell",
    DisplayPriority = 4,
    DisplayedName = "$10653",
    Description = "$10654",
  },
  {
    Type = Ship,
    ThingToBuild = "Kus_ResearchShip_3",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & (!CorvetteProduction)",
    DisplayPriority = 2,
    DisplayedName = "$10615",
    Description = "$10616",
  },
  {
    Type = Ship,
    ThingToBuild = "Kus_ResearchShip_4",
    RequiredResearch = "CorvetteTech & PlasmaBombsTech",
    RequiredFleetSubSystems = "Research  & (!HeavyCorvette)",
    DisplayPriority = 5,
    DisplayedName = "$10617",
    Description = "$10618",
  },
  {
    Type = Ship,
    ThingToBuild = "Kus_ResearchShip_5",
    RequiredResearch = "CorvetteTech",
    RequiredFleetSubSystems = "Research & (!RapidTurret)",
    DisplayPriority = 3,
    DisplayedName = "$10619",
    Description = "$10620",
  },
 	{
    Type = Ship,
    ThingToBuild = "Kus_ResearchShipAdv_1",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA & (!CapShipProduction)",
    DisplayPriority = 3,
    DisplayedName = "$10625",
    Description = "$10626",
  },
  {
    Type = Ship,
    ThingToBuild = "Kus_ResearchShipAdv_2",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA & (!IonCannon)",
    DisplayPriority = 2,
    DisplayedName = "$10621",
    Description = "$10622",
  },
  {
    Type = Ship,
    ThingToBuild = "Kus_ResearchShipAdv_3",
    RequiredResearch = "ioncannonTech",
    RequiredFleetSubSystems = "RA & CapShipProduction & (!heavygun)",
    DisplayPriority = 5,
    DisplayedName = "$10629",
    Description = "$10630",
  },
  {
    Type = Ship,
    ThingToBuild = "Kus_ResearchShipAdv_4",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA & CapShipProduction & (!missile)",
    DisplayPriority = 4,
    DisplayedName = "$10627",
    Description = "$10628",
  },
  {
    Type = Ship,
    ThingToBuild = "Kus_ResearchShipAdv_5",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA & !CloakFighter",
    DisplayPriority = 1,
    DisplayedName = "$10649",
    Description = "$10650",
  },
	--{
	--	Type =					Ship,
	--	ThingToBuild =			"Kus_Scout",
	--	RequiredResearch =		"",
	--	RequiredShipSubSystems =	"",
	--	DisplayPriority =		10,
  --  DisplayedName = "$10551",
  --  Description = "$10552",
	--},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Interceptor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | KeyToAllShips",
		DisplayPriority =		11,
    DisplayedName = "$10553",
    Description = "$10554",
	},
	--{
	--	Type =					Ship,
	--	ThingToBuild =			"Kus_Defender",
  --  RequiredResearch = "ResearchTech",
  --  RequiredFleetSubSystems = "",
  --  DisplayPriority = 12,
  --  DisplayedName = "$10557",
  --  Description = "$10558",
	--},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_AttackBomber",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction | KeyToAllShips",
    DisplayPriority = 13,
    DisplayedName = "$10555",
    Description = "$10556",
	},	
	{
		Type =					Ship,
		ThingToBuild =			"Kus_CloakedFighter",
		RequiredResearch =		"",
		RequiredFleetSubSystems =	"CloakFighter | KeyToAllShips",
		DisplayPriority =		14,
    DisplayedName = "$10559",
    Description = "$10560",
	},
--Corvettes--------------
	--{
	--	Type =					Ship,
	--	ThingToBuild =			"Kus_RepairCorvette",
	--	RequiredResearch =		"CorvetteDrive",
	--	RequiredShipSubSystems =	"",
	--	DisplayPriority =		20,
	--	DisplayedName =			"$12022",
	--	Description =			"$12023",
	--},
    --
    -- ***WARNING***
    -- This next stanza is referenced by index in DataHW1Campaign/LevelData/Campaign/HomeworldClassic/Kushan/Build.lua.
    -- If you modify it, please keep taht other one up to date!
    --
	{
		Type =					Ship,
		ThingToBuild =			"Kus_SalvageCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "GravityWell | KeyToAllShips",
    DisplayPriority = 24,
    DisplayedName = "$10569",
    Description = "$10570"
	},
	--{
	--	Type =					Ship,
	--	ThingToBuild =			"Kus_LightCorvette",
  --  RequiredResearch = "",
  --  RequiredFleetSubSystems = "CorvetteProduction | KeyToAllShips",
  --  DisplayPriority = 22,
  --  DisplayedName = "$10561",
  --  Description = "$10562",
	--},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_HeavyCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "HeavyCorvette | KeyToAllShips",
    DisplayPriority = 23,
    DisplayedName = "$10563",
    Description = "$10564",
	},	
  {
    Type = Ship,
    ThingToBuild = "Kus_CommandCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CorvetteProduction | KeyToAllShips",
    DisplayPriority = 25,
    DisplayedName = "$10643",
    Description = "$10644",
  },
	{
		Type =					Ship,
		ThingToBuild =			"Kus_MultiGunCorvette",
		RequiredResearch =		"",
		RequiredFleetSubSystems =	"RapidTurret | KeyToAllShips",
		DisplayPriority =		22,
		DisplayedName =			"$10565",
		Description =			"$10566",
	},
	--{
	--	Type =					Ship,
	--	ThingToBuild =			"Kus_MinelayerCorvette",
	--	RequiredResearch =		"MinelayingTech",
	--	RequiredShipSubSystems =	"",
	--	DisplayPriority =		25,
	--	DisplayedName =			"$12018",
	--	Description =			"$12019",
	--},
--Frigates---------------
	--{
	--	Type =					Ship,
	--	ThingToBuild =			"Kus_SupportFrigate",
  --  RequiredResearch = "",
  --  RequiredFleetSubSystems = "RA | KeyToAllShips",
  --  DisplayPriority = 50,
  --  DisplayedName = "$10575",
  --  Description = "$10576",
	--},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_MissileFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA | KeyToAllShips",
    DisplayPriority = 51,
    DisplayedName = "$10647",
    Description = "$10648",
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_AssaultFrigate",
    RequiredResearch = "PlasmaBombsTech",
    RequiredFleetSubSystems = "RA | KeyToAllShips",
    DisplayPriority = 52,
    DisplayedName = "$10573",
    Description = "$10574",
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_IonCannonFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "IonCannon | KeyToAllShips",
    DisplayPriority = 53,
    DisplayedName = "$10579",
    Description = "$10580",
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_DroneFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA | KeyToAllShips",
    DisplayPriority = 54,
    DisplayedName = "$10577",
    Description = "$10578",
	},
--Capital Ships----------
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Carrier",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 70,
    DisplayedName = "$10581",
    Description = "$10582",
	},
	{
  	Type = Ship,
  	ThingToBuild = "Kus_Mothership",
  	RequiredResearch = "",
  	RequiredFleetSubSystems = "RA",
  	DisplayPriority = 71,
  	DisplayedName = "$10595",
  	Description = "$10596",
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Destroyer",
    RequiredResearch = "ioncannonTech",
    RequiredFleetSubSystems = "CapShipProduction | KeyToAllShips",
    DisplayPriority = 72,
    DisplayedName = "$10583",
    Description = "$10584",
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_MissileDestroyer",
    RequiredResearch = "",
    RequiredFleetSubSystems = "missile | KeyToAllShips",
    DisplayPriority = 73,
    DisplayedName = "$10585",
    Description = "$10586",
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_HeavyCruiser",
    RequiredResearch = "",
    RequiredFleetSubSystems = "heavygun | KeyToAllShips",
    DisplayPriority = 74,
    DisplayedName = "$10587",
    Description = "$10588",
	},	
--Utility----------------
	{
		Type =					Ship,
		ThingToBuild =			"Kus_ResourceCollector",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,
		DisplayedName =			"$10597",
		Description =			"$10598"
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_ResourceRefinery",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA",
    DisplayPriority = 101,
    DisplayedName = "$10599",
    Description = "$10600",
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_RepairCarrier",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RA",
    DisplayPriority = 102,
    DisplayedName = "$10651",
    Description = "$10652",
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_ResearchShip",
    RequiredResearch = "",
    RequiredFleetSubSystems = "! Research",
    DisplayPriority = 110,
    DisplayedName = "$10589",
    Description = "$10590",
	},
  {
		Type =					Ship,
		ThingToBuild =			"Kus_ResearchShipAdv",
    RequiredResearch = "CorvetteTech",
    RequiredFleetSubSystems = "! RA",
    DisplayPriority = 111,
    DisplayedName = "$10609",
    Description = "$10610",
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Probe",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		140,
		DisplayedName =			"$10601",
		Description =			"$10602"
	},
	--{
	--	Type =					Ship,
	--	ThingToBuild =			"Kus_ProximitySensor",
	--	RequiredResearch =		"ProximitySensor",
	--	RequiredShipSubSystems =	"",
	--	DisplayPriority =		141,
	--	DisplayedName =			"$12054",
	--	Description =			"$12055"
	--},
	--{
	--	Type =					Ship,
	--	ThingToBuild =			"Kus_SensorArray",
  --  RequiredResearch = "",
  --  RequiredFleetSubSystems = "sensorarray",
  --  DisplayPriority = 142,
  --  DisplayedName = "$10605",
  --  Description = "$10606",
	--},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_GravWellGenerator",
    RequiredResearch = "RATech",
    RequiredFleetSubSystems = "",
		DisplayPriority =		142,
		DisplayedName =			"$10639",
		Description =			"$10594"
	},
	--{
	--	Type =					Ship,
	--	ThingToBuild =			"Kus_CloakGenerator",
	--	RequiredResearch =		"CloakGenerator",
	--	RequiredShipSubSystems =	"",
	--	DisplayPriority =		144,
	--	DisplayedName =			"$12050",
	--	Description =			"$12051"
	--},
--Drones
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone0",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone1",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone2",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone3",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone4",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone5",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone6",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone7",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone8",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone9",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone10",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone11",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone12",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},
	{
		Type =					Ship,
		ThingToBuild =			"Kus_Drone13",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		100,		
	},	
}

