Ship = 0
SubSystem = 1
build = {
  {
    Type = Ship,
    ThingToBuild = "tai_researchship_1f",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & (!FighterProduction)",
    DisplayPriority = 1,
    DisplayedName = "$9611",
    Description = "$9612",
  },
  {
    Type = Ship,
    ThingToBuild = "tai_researchship_2f",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & (!defensefighters)",
    DisplayPriority = 2,
    DisplayedName = "$9613",
    Description = "$9614",
  },
  {
    Type = Ship,
    ThingToBuild = "tai_researchship_3f",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & (!CorvetteProduction)",
    DisplayPriority = 3,
    DisplayedName = "$9615",
    Description = "$9616",
  },
  {
    Type = Ship,
    ThingToBuild = "tai_researchship_4f",
    RequiredResearch = "CorvetteTech",
    RequiredFleetSubSystems = "Research & (!HeavyCorvette)",
    DisplayPriority = 4,
    DisplayedName = "$9617",
    Description = "$9618",
  },
--{
  --Type = SubSystem,
  --ThingToBuild = "tai_r_multigun",
  --RequiredResearch = "CorvetteTech",
  --RequiredFleetSubSystems = "Research",
  --DisplayPriority = 5,
  --DisplayedName = "$9619",
  --Description = "$9620",
--},
  {
    Type = SubSystem,
    ThingToBuild = "tai_rs_ioncannon",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 1,
    DisplayedName = "$9621",
    Description = "$9622",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tai_rs_defense",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 2,
    DisplayedName = "$9623",
    Description = "$9624",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tai_rs_capship",
    RequiredResearch = "ioncannonTech",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 3,
    DisplayedName = "$9625",
    Description = "$9626",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tai_rs_missile",
    RequiredResearch = "taicapshipTech",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 4,
    DisplayedName = "$9627",
    Description = "$9628",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tai_rs_heavygun",
    RequiredResearch = "taicapshipTech",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 5,
    DisplayedName = "$9629",
    Description = "$9630",
  },
  {
    Type = SubSystem,
    ThingToBuild = "tai_rs_sensorarray",
    RequiredResearch = "taicapshipTech",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 6,
    DisplayedName = "$9631",
    Description = "$9632",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_C_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 1,
    DisplayedName = "$9637",
    Description = "$9638",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_M_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 1,
    DisplayedName = "$9637",
    Description = "$9638",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_C_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 2,
    DisplayedName = "$9639",
    Description = "$9640",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_MS_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 2,
    DisplayedName = "$9639",
    Description = "$9640",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_Scout",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 1,
    DisplayedName = "$9551",
    Description = "$9552",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_Interceptor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research | KeyToAllShips",
    DisplayPriority = 2,
    DisplayedName = "$9553",
    Description = "$9554",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_AttackBomber",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction | KeyToAllShips",
    DisplayPriority = 3,
    DisplayedName = "$9555",
    Description = "$9556",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_heavydefender",
    RequiredResearch = "ResearchTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 4,
    DisplayedName = "$9557",
    Description = "$9558",
  },
{
    Type = Ship,
    ThingToBuild = "TAI_defensefighter",
    RequiredResearch = "",
    RequiredFleetSubSystems = "defensefighters | KeyToAllShips",
    DisplayPriority = 5,
    DisplayedName = "$9559",
    Description = "$9560",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_lightcorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CorvetteProduction | KeyToAllShips",
    DisplayPriority = 11,
    DisplayedName = "$9561",
    Description = "$9562",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_heavycorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "HeavyCorvette | KeyToAllShips",
    DisplayPriority = 12,
    DisplayedName = "$9563",
    Description = "$9564",
  },
--{ 
  --Type = Ship, 
  --ThingToBuild = "TAI_multiguncorvette",
  --RequiredResearch = "",
  --RequiredFleetSubSystems = "multigun",
  --DisplayPriority = 13,
  --DisplayedName = "$9565",
  --Description = "$9566"
--},
--{ 
  --Type = Ship, 
  --ThingToBuild = "TAI_repaircorvette",
  --RequiredResearch = "",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 14,
  --DisplayedName = "$9567",
  --Description = "$9568"
--},
  { 
    Type = Ship, 
    ThingToBuild = "TAI_salcapcorvette",
    RequiredResearch = "RSTech",
    RequiredFleetSubSystems = "Research | KeyToAllShips",
    DisplayPriority = 15,
    DisplayedName = "$9569",
    Description = "$9570"
  },
--{
  --Type = Ship,
  --ThingToBuild = "TAI_minelayercorvette",
  --RequiredResearch = "GraviticAttractionTech",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 16,
  --DisplayedName = "$9571",
  --Description = "$9572",
--},
  {
    Type = Ship,
    ThingToBuild = "TAI_standardfrigate",
    RequiredResearch = "PlasmaBombsTech",
    RequiredFleetSubSystems = "RS | KeyToAllShips",
    DisplayPriority = 21,
    DisplayedName = "$9573",
    Description = "$9574",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_supportfrigate",
    RequiredResearch = "RSTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 22,
    DisplayedName = "$9575",
    Description = "$9576",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_ioncannonfrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction | KeyToAllShips",
    DisplayPriority = 23,
    DisplayedName = "$9579",
    Description = "$9580",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_defensefrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "defense | KeyToAllShips",
    DisplayPriority = 24,
    DisplayedName = "$9577",
    Description = "$9578",
  },
--{
  --Type = Ship,
  --ThingToBuild = "TAI_mothership",
  --RequiredResearch = "",
  --RequiredFleetSubSystems = "RS",
  --DisplayPriority = 31,
  --DisplayedName = "$9595",
  --Description = "$9596",
--},
  {
    Type = Ship,
    ThingToBuild = "TAI_carrier",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 32,
    DisplayedName = "$9581",
    Description = "$9582",
  },
  {
    Type = Ship,
    ThingToBuild = "tai_shipyard",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 33,
    DisplayedName = "$9641",
    Description = "$9642",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_Destroyer",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CapShipProduction | KeyToAllShips",
    DisplayPriority = 34,
    DisplayedName = "$9583",
    Description = "$9584",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_missiledestroyer",
    RequiredResearch = "",
    RequiredFleetSubSystems = "missile | KeyToAllShips",
    DisplayPriority = 35,
    DisplayedName = "$9585",
    Description = "$9586",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_heavycruiser",
    RequiredResearch = "",
    RequiredFleetSubSystems = "heavygun | KeyToAllShips",
    DisplayPriority = 36,
    DisplayedName = "$9587",
    Description = "$9588",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_researchship",
    RequiredResearch = "",
    RequiredFleetSubSystems = "! Research",
    DisplayPriority = 41,
    DisplayedName = "$9589",
    Description = "$9590",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_researchstation",
    RequiredResearch = "ResearchTech & CorvetteTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 42,
    DisplayedName = "$9609",
    Description = "$9610",
  },
--{
  --Type = Ship,
  --ThingToBuild = "TAI_cloakgenerator",
  --RequiredResearch = "cloakgeneratorTech",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 43,
  --DisplayedName = "$9591",
  --Description = "$9592",
--},
--{
  --Type = Ship,
  --ThingToBuild = "TAI_gravwellgenerator",
  --RequiredResearch = "gravwellgeneratorTech",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 44,
  --DisplayedName = "$9593",
  --Description = "$9594",
--},
  {
    Type = Ship,
    ThingToBuild = "TAI_ResourceCollector",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 51,
    DisplayedName = "$9597",
    Description = "$9598",
  },
  {
    Type = Ship,
    ThingToBuild = "TAI_ResourceController",
    RequiredResearch = "RSTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 52,
    DisplayedName = "$9599",
    Description = "$9600",
  },
--{
  --Type = Ship,
  --ThingToBuild = "TAI_Probe",
  --RequiredResearch = "",
  --RequiredShipSubSystems = "",
  --DisplayPriority = 53,
  --DisplayedName = "$9601",
  --Description = "$9602",
--},
--{
  --Type = Ship,
  --ThingToBuild = "TAI_proximitysensor",
  --RequiredResearch = "ProbeProxSensorTech",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 54,
  --DisplayedName = "$9603",
  --Description = "$9604",
--},
  {
    Type = Ship,
    ThingToBuild = "TAI_sensorarray",
    RequiredResearch = "",
    RequiredFleetSubSystems = "sensorarray",
    DisplayPriority = 55,
    DisplayedName = "$9605",
    Description = "$9606",
  },
}
