dofilepath("Data:leveldata/multiplayer/lib/FXGDeathmatch_Data.lua")

Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
BLUE = 0
YELLOW = 1
RED = nil
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "FXGDM",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
  },
  {
    Name = "Branch1",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "保皇贵族",
    DisplayPriority = 1,
    Description = "保皇贵族是帝国泰坦内部的保守派，顽固派，但同时也掌握着大多数d资源和兵力，他们梦想着能够有朝一日辅佐新的皇帝一统泰坦世界，从而在新帝国内部获得至高无上的权力。\n可召唤突袭舰进入战场\n轻护航艇建造用时更短\n突袭舰等离子炮EMP效果\n建造导弹阵列模块后立即获得一艘导弹驱逐舰\n船坞生产速度更快",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Build,
    ShortDisplayedName = "保皇贵族",
  },
  {
    Name = "Branch2",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "改革势力",
    DisplayPriority = 2,
    Description = "改革势力与当年的共和党人不同，他们不热衷于权力，而是为了泰坦人的骄傲和荣耀而不懈努力。在泰坦共和国因终结之战而一蹶不振时，这群泰坦人正努力让泰坦之名在东北银河重新崛起。\n可召唤支援舰进入战场\n多炮护航艇建造用时更短\n支援舰火控系统\n建造护航艇模块后立即获得研究站\n研究站生产速度更快",
    UpgradeType = RED,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Tech,
    ShortDisplayedName = "改革势力",
  },
  {
    Name = "Branch3",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "皇家卫队",
    DisplayPriority = 3,
    Description = "皇家卫队曾是泰坦帝国负责保卫皇族成员的精锐舰队，皇帝死后，他们却从未解散，并且不再听令于任何人，而是始终隐秘地进行着自己的行动。他们真正的目的恐怕只有他们自己知道。\n可召唤离子炮护卫舰进入战场\n重护航艇建造用时更短\n离子炮护卫舰机动能力更强\n建造主力舰模块后立即获得一艘驱逐舰\n母舰生产速度更快",
    UpgradeType = BLUE,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_shield,
    ShortDisplayedName = "皇家卫队",
  },
  {
    Name = "Sumon_AssaultFrigate",
    RequiredResearch = "Branch1 & PlasmaBombsTech",
    RequiredSubSystems = "RS",
    Cost = FXG_Sumon_Data.Taiidan[1].Cost,
    Time = 100,
    DisplayedName = "召唤突袭舰进入战场",
    DisplayPriority = 0,
    Description = "突袭舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"tai_standardfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "突袭舰",
  },
  {
    Name = "Sumon_SupportFrigate",
    RequiredResearch = "Branch2 & RSTech",
    RequiredSubSystems = "",
    Cost = FXG_Sumon_Data.Taiidan[2].Cost,
    Time = 100,
    DisplayedName = "召唤支援舰进入战场",
    DisplayPriority = 0,
    Description = "支援舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"tai_supportfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "支援舰",
  },
  {
    Name = "Sumon_IonCannonFrigate",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "FrigateProduction",
    Cost = FXG_Sumon_Data.Taiidan[3].Cost,
    Time = 100,
    DisplayedName = "召唤离子炮护卫舰进入战场",
    DisplayPriority = 0,
    Description = "离子炮护卫舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"tai_ioncannonfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "离子炮护卫舰",
  },
  {
    Name = "InstantBuild_MissileDestroyer",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "missile",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_ResearchStation",
    RequiredResearch = "Branch2",
    RequiredSubSystems = "CorvetteProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_Destroyer",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "CapShipProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "ResearchTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tai_researchship",
  },
  {
    Name = "PlasmaBombsTech",
    RequiredResearch = "",
    RequiredSubSystems = "FighterProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tai_researchship",
  },
  {
    Name = "PlasmaBombsWeaponAccuracy",
    RequiredResearch = "PlasmaBombsTech",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    DisplayPriority = 1,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tai_attackbomber",
    UpgradeName = "WeaponAccuracy",
    UpgradeValue = 2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9052",
  },
  {
    Name = "CorvetteTech",
    RequiredResearch = "",
    RequiredSubSystems = "CorvetteProduction | KeyToAllShips",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tai_researchship",
  },
  {
    Name = "RSTech",
    RequiredResearch = "",
    RequiredSubSystems = "RS",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "TAI_researchstation",
  },
  {
    Name = "ioncannonTech",
    RequiredResearch = "",
    RequiredSubSystems = "FrigateProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "TAI_researchstation",
  },
  {
    Name = "taicapshipTech",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "TAI_researchstation",
  },
  {
    Name = "heavygunTech",
    RequiredResearch = "",
    RequiredSubSystems = "heavygun",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "TAI_researchstation",
  },
  {
    Name = "Tai_AirWeaponUpgrade1",
    RequiredResearch = "CorvetteTech",
    RequiredSubSystems = "Research | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9708",
    DisplayPriority = 100,
    Description = "$9709",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9692",
  },
  {
    Name = "Tai_AirWeaponUpgrade2",
    RequiredResearch = "Tai_AirWeaponUpgrade1",
    RequiredSubSystems = "(Research & RS) | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9710",
    DisplayPriority = 100,
    Description = "$9711",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9693",
  },
  {
    Name = "Tai_AirWeaponUpgrade3",
    RequiredResearch = "Tai_AirWeaponUpgrade2",
    RequiredSubSystems = "(Research & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9712",
    DisplayPriority = 100,
    Description = "$9713",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9694",
  },
  {
    Name = "Tai_AirHealthUpgrade1",
    RequiredResearch = "CorvetteTech",
    RequiredSubSystems = "Research | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9714",
    DisplayPriority = 101,
    Description = "$9715",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9692",
  },
  {
    Name = "Tai_AirHealthUpgrade2",
    RequiredResearch = "Tai_AirHealthUpgrade1",
    RequiredSubSystems = "(Research & RS) | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9716",
    DisplayPriority = 101,
    Description = "$9717",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9693",
  },
  {
    Name = "Tai_AirHealthUpgrade3",
    RequiredResearch = "Tai_AirHealthUpgrade2",
    RequiredSubSystems = "(Research & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9718",
    DisplayPriority = 101,
    Description = "$9719",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9694",
  },
  {
    Name = "Tai_FrigateWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "RS | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9720",
    DisplayPriority = 200,
    Description = "$9721",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.12,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9695",
  },
  {
    Name = "Tai_FrigateWeaponUpgrade2",
    RequiredResearch = "Tai_FrigateWeaponUpgrade1",
    RequiredSubSystems = "RS | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9722",
    DisplayPriority = 200,
    Description = "$9723",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.24,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9696",
  },
  {
    Name = "Tai_FrigateWeaponUpgrade3",
    RequiredResearch = "Tai_FrigateWeaponUpgrade2",
    RequiredSubSystems = "(RS & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9724",
    DisplayPriority = 200,
    Description = "$9725",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.36,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9697",
  },
  {
    Name = "Tai_FrigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "RS | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9726",
    DisplayPriority = 201,
    Description = "$9727",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9695",
  },
  {
    Name = "Tai_FrigateHealthUpgrade2",
    RequiredResearch = "Tai_FrigateHealthUpgrade1",
    RequiredSubSystems = "RS | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9728",
    DisplayPriority = 201,
    Description = "$9729",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$9696",
  },
  {
    Name = "Tai_FrigateHealthUpgrade3",
    RequiredResearch = "Tai_FrigateHealthUpgrade2",
    RequiredSubSystems = "(RS & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9730",
    DisplayPriority = 201,
    Description = "$9731",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$9697",
  },
  {
    Name = "Tai_CapitalWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9732",
    DisplayPriority = 300,
    Description = "$9733",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9698",
  },
  {
    Name = "Tai_CapitalWeaponUpgrade2",
    RequiredResearch = "Tai_CapitalWeaponUpgrade1",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9734",
    DisplayPriority = 300,
    Description = "$9735",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9699",
  },
  {
    Name = "Tai_CapitalWeaponUpgrade3",
    RequiredResearch = "Tai_CapitalWeaponUpgrade2",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9736",
    DisplayPriority = 300,
    Description = "$9737",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9700",
  },
  {
    Name = "Tai_CapitalHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9738",
    DisplayPriority = 301,
    Description = "$9739",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9698",
  },
  {
    Name = "Tai_CapitalHealthUpgrade2",
    RequiredResearch = "Tai_CapitalHealthUpgrade1",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9740",
    DisplayPriority = 301,
    Description = "$9741",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9699",
  },
  {
    Name = "Tai_CapitalHealthUpgrade3",
    RequiredResearch = "Tai_CapitalHealthUpgrade2",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9742",
    DisplayPriority = 301,
    Description = "$9743",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9700",
  },
  {
    Name = "Tai_FighterWeaponUpgrade1",
    RequiredResearch = "Tai_AirWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9708",
    DisplayPriority = 100,
    Description = "$9709",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9692",
  },
  {
    Name = "Tai_FighterWeaponUpgrade2",
    RequiredResearch = "Tai_AirWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9710",
    DisplayPriority = 100,
    Description = "$9711",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9693",
  },
  {
    Name = "Tai_FighterWeaponUpgrade3",
    RequiredResearch = "Tai_AirWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9712",
    DisplayPriority = 100,
    Description = "$9713",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9694",
  },
  {
    Name = "Tai_FighterHealthUpgrade1",
    RequiredResearch = "Tai_AirHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9714",
    DisplayPriority = 101,
    Description = "$9715",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9692",
  },
  {
    Name = "Tai_FighterHealthUpgrade2",
    RequiredResearch = "Tai_AirHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9716",
    DisplayPriority = 101,
    Description = "$9717",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9693",
  },
  {
    Name = "Tai_FighterHealthUpgrade3",
    RequiredResearch = "Tai_AirHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9718",
    DisplayPriority = 101,
    Description = "$9719",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9694",
  },
--AI behaviour	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed	
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.025,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.05,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.075,
	},
--AI resource rate	
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},			
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")