Councilor_Actor=
{
	Hiigaran={Military=2,},
	Vaygr={Military=3,},
	Taiidan={Military=20,},
	Turanic={Military=21,},
	Kadesh={Military=16,},
	Keeper={Military=4,},
	Bentusi={Military=6,},
	Kushan={Military=13,},
	Observer={Military=1,},
}

Councilor_DevelopData=
{
	Hiigaran=
	{
		{
			Name=Councilor_Text[1],
			NaSu={"Hgn_C_Production_Fighter","Hgn_MS_Production_Fighter"},
			RqSu={},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[2],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[3],
			NaSu={"Hgn_C_Production_Corvette","Hgn_MS_Production_Corvette",},
			RqSu={"Hgn_C_Production_Fighter","Hgn_MS_Production_Fighter",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[4],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[5],
					RqSu={"Hgn_C_Module_Research","Hgn_MS_Module_Research",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[6],
			NaSu={"Hgn_C_Module_Research","Hgn_MS_Module_Research",},
			RqSu={"Hgn_C_Production_Fighter","Hgn_MS_Production_Fighter",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[7],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[8],
					RqSu={"Hgn_C_Production_Corvette","Hgn_MS_Production_Corvette",},
					RqSh="",
				},
				{
					Item=Councilor_Text[9],
					RqSu={"Hgn_C_Production_Frigate","Hgn_MS_Production_Frigate",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[10],
			NaSu={"Hgn_C_Production_Frigate","Hgn_MS_Production_Frigate",},
			RqSu={"Hgn_C_Production_Corvette","Hgn_MS_Production_Corvette",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[11],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[12],
					RqSu={"Hgn_C_Module_Research","Hgn_MS_Module_Research",},
					RqSh="",
				},
				{
					Item=Councilor_Text[13],
					RqSu={"Hgn_C_Module_ResearchAdvanced","Hgn_MS_Module_ResearchAdvanced",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[14],
			NaSu={"Hgn_C_Module_ResearchAdvanced","Hgn_MS_Module_ResearchAdvanced",},
			RqSu={"Hgn_C_Module_Research","Hgn_MS_Module_Research",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[15],
					RqSu={"Hgn_C_Production_Frigate","Hgn_MS_Production_Frigate",},
					RqSh="",
				},
				{
					Item=Councilor_Text[16],
					RqSu={"Hgn_MS_Production_CapShip",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[17],
			NaSu={"Hgn_MS_Production_CapShip",},
			RqSu={"Hgn_C_Production_Frigate","Hgn_MS_Production_Frigate",},
			RqSh="Hgn_Mothership",
			Lock=
			{
				{
					Item=Councilor_Text[18],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[19],
					RqSu={"Hgn_C_Module_Hyperspace","Hgn_MS_Module_Hyperspace",},
					RqSh="",
				},
				{
					Item=Councilor_Text[20],
					RqSu={"Hgn_C_Module_ResearchAdvanced","Hgn_MS_Module_ResearchAdvanced",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[17],
			NaSu={"Hgn_MS_Production_CapShip",},
			RqSu={"Hgn_C_Module_Hyperspace","Hgn_MS_Module_Hyperspace",},
			RqSh="Hgn_Mothership",
			Lock=
			{
				{
					Item=Councilor_Text[21],
					RqSu={"Hgn_C_Module_ResearchAdvanced","Hgn_MS_Module_ResearchAdvanced",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[22],
			NaSu={"Hgn_C_Module_Hyperspace","Hgn_MS_Module_Hyperspace",},
			RqSu={"Hgn_C_Module_Research","Hgn_MS_Module_Research",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[23],
					RqSu={"Hgn_MS_Production_CapShip",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[24],
			NaSh="Hgn_Shipyard",
			RqSu={"Hgn_C_Module_Hyperspace","Hgn_MS_Module_Hyperspace",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[25],
					RqSu={"Hgn_MS_Production_CapShip",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[26],
			NaSu={"Hgn_SY_Production_CapshipAdvanced",},
			RqSu={"Hgn_C_Module_ResearchAdvanced","Hgn_MS_Module_ResearchAdvanced",},
			RqSh="Hgn_Shipyard",
			Lock=
			{
				{
					Item=Councilor_Text[27],
					RqSu={},
					RqSh="Hgn_LightCruiser",
				},
			},
		},
		{
			Name=Councilor_Text[28],
			NaSu={"Hgn_LBC_HeavyTurret",},
			RqSu={"Hgn_SY_Production_CapshipAdvanced",},
			RqSh="Hgn_LightCruiser",
			Lock=
			{
				{
					Item=Councilor_Text[29],
					RqSu={},
					RqSh="",
				},
			},
		},
	},
	Kadesh=
	{
		{
			Name=Councilor_Text[30],
			NaSu={"Kad_C_Fighter"},
			RqSu={},
			RqSh="Kad_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[31],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[32],
			NaSu={"Kad_C_Corvette",},
			RqSu={"Kad_C_Fighter",},
			RqSh="Kad_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[33],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[34],
			NaSu={"Kad_M_Capship",},
			RqSu={"Kad_C_Corvette",},
			RqSh="Kad_Mothership",
			Lock=
			{
				{
					Item=Councilor_Text[35],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[36],
					RqSu={},
					RqSh="Kad_Carrier",
				},
			},
		},
		{
			Name=Councilor_Text[37],
			NaSu={"Kad_M_CapshipAdvanced",},
			RqSu={"Kad_M_Capship",},
			RqSh="Kad_Mothership",
			Lock=
			{
				{
					Item=Councilor_Text[38],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[39],
					RqSu={},
					RqSh="Kad_Carrier",
				},
				{
					Item=Councilor_Text[173],
					RqSu={"Kad_C_MultiBeam","Kad_C_SuperSwarmer","Kad_C_Hyperspace",},
					RqSh="Kad_Carrier",
				},
				{
					Item=Councilor_Text[40],
					RqSu={"Kad_C_MultiBeam","Kad_C_SuperSwarmer",},
					RqSh="Kad_Carrier",
				},
				{
					Item=Councilor_Text[41],
					RqSu={"Kad_C_SuperSwarmer",},
					RqSh="Kad_Carrier",
				},
			},
		},
		{
			Name=Councilor_Text[42],
			NaSu={"Kad_C_MultiBeam","Kad_C_MultiBeam_F",},
			RqSu={"Kad_M_Capship",},
			RqSh="Kad_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[43],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[44],
			NaSu={"Kad_C_SuperSwarmer","Kad_C_SuperSwarmer_F",},
			RqSu={"Kad_M_Capship",},
			RqSh="Kad_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[45],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[46],
			NaSu={"Kad_C_PlatformControl",},
			RqSu={"Kad_C_Fighter",},
			RqSh="Kad_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[47],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[48],
			NaSu={"Kad_C_LiquidMetal",},
			RqSu={"Kad_C_Corvette",},
			RqSh="Kad_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[49],
					RqSu={"",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[50],
			NaSu={"Kad_C_Hyperspace",},
			RqSu={"Kad_M_Capship",},
			RqSh="Kad_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[168],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[170],
					RqSu={"Kad_M_CapshipAdvanced",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[52],
			NaSu={"Kad_C_Cloak",},
			RqSu={"Kad_M_CapshipAdvanced",},
			RqSh="Kad_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[53],
					RqSu={"",},
					RqSh="",
				},
			},
		},
	},
	Keeper=
	{
		{
			Name=Councilor_Text[54],
			NaSh="Kpr_Energy_PhotonBomb",
			RqSu={},
			RqSh="Kpr_BalcoraGate",
			Lock=
			{
				{
					Item=Councilor_Text[55],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[56],
			NaSu={"Kpr_BUILD",},
			RqSu={},
			RqSh="Kpr_Energy_PhotonBomb",
			Lock=
			{
				{
					Item=Councilor_Text[57],
					RqSu={},
					RqSh="Kpr_BalcoraGate",
				},
				{
					Item=Councilor_Text[58],
					RqSu={},
					RqSh="Kpr_Deliver",
				},
			},
		},
		{
			Name=Councilor_Text[59],
			NaSu={"Kpr_Hyperspace",},
			RqSu={"Kpr_BUILD",},
			RqSh="Kpr_BalcoraGate",
			Lock=
			{
				{
					Item=Councilor_Text[60],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[61],
					RqSu={},
					RqSh="Kpr_Deliver",
				},
			},
		},
		{
			Name=Councilor_Text[62],
			NaSh="Kpr_Energy_Photoncannon",
			RqSu={"Kpr_Hyperspace",},
			RqSh="Kpr_BalcoraGate",
			Lock=
			{
				{
					Item=Councilor_Text[63],
					RqSu={},
					RqSh="Kpr_Deliver, Kpr_Carrier",
				},
			},
		},
		{
			Name=Councilor_Text[64],
			NaSh="Kpr_Energy_Pulsar",
			RqSu={"Kpr_Hyperspace",},
			RqSh="Kpr_BalcoraGate",
			Lock=
			{
				{
					Item=Councilor_Text[65],
					RqSu={},
					RqSh="Kpr_Deliver, Kpr_Carrier",
				},
				{
					Item=Councilor_Text[66],
					RqSu={},
					RqSh="Kpr_Energy_IonCannon",
				},
			},
		},
		{
			Name=Councilor_Text[67],
			NaSh="Kpr_Energy_IonCannon",
			RqSu={"Kpr_Hyperspace",},
			RqSh="Kpr_BalcoraGate",
			Lock=
			{
				{
					Item=Councilor_Text[68],
					RqSu={},
					RqSh="Kpr_Deliver, Kpr_Carrier",
				},
				{
					Item=Councilor_Text[69],
					RqSu={},
					RqSh="Kpr_Energy_Pulsar",
				},
			},
		},
		{
			Name=Councilor_Text[70],
			NaSh="Kpr_Energy_PhasedCannon",
			RqSu={"Kpr_Hyperspace",},
			RqSh="Kpr_Energy_IonCannon",
			Lock=
			{
				{
					Item=Councilor_Text[71],
					RqSu={},
					RqSh="Kpr_Energy_Photoncannon",
				},
			},
		},
		{
			Name=Councilor_Text[72],
			NaSu={"Kpr_Core",},
			RqSu={"Kpr_Hyperspace",},
			RqSh="Kpr_BalcoraGate",
			Lock=
			{
				{
					Item=Councilor_Text[73],
					RqSu={},
					RqSh="Kpr_Energy_PhasedCannon",
				},
			},
		},
		{
			Name=Councilor_Text[74],
			NaSh="Kpr_Energy_SuperPulsar",
			RqSu={"Kpr_Core",},
			RqSh="Kpr_BalcoraGate",
			Lock=
			{
				{
					Item=Councilor_Text[75],
					RqSu={},
					RqSh="",
				},
			},
		},
	},
	Taiidan=
	{
		{
			Name=Councilor_Text[76],
			NaSh="Tai_ResearchShip_5",
			RqSu={},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[77],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[78],
			NaSh="Tai_ResearchShip_3",
			RqSu={},
			RqSh="Tai_ResearchShip_5",
			Lock=
			{
				{
					Item=Councilor_Text[79],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[80],
					RqSu={},
					RqSh="Tai_Carrier",
				},
			},
		},
		{
			Name=Councilor_Text[81],
			NaSh="Tai_ResearchShip_1",
			RqSu={},
			RqSh="Tai_ResearchShip_5",
			Lock=
			{
				{
					Item=Councilor_Text[82],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[83],
					RqSu={},
					RqSh="Tai_ResearchStation",
				},
			},
		},
		{
			Name=Councilor_Text[84],
			NaSh="Tai_ResearchShip_2",
			RqSu={},
			RqSh="Tai_ResearchShip_5",
			Lock=
			{
				{
					Item=Councilor_Text[85],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[86],
			NaSh="Tai_ResearchShip_4",
			RqSu={},
			RqSh="Tai_ResearchShip_3",
			Lock=
			{
				{
					Item=Councilor_Text[87],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[88],
			NaSh="Tai_ResearchStation",
			RqSu={"tai_r_Corvette",},
			RqSh="Tai_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[89],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[90],
					RqSu={},
					RqSh="Tai_ResearchShip_1",
				},
			},
		},
		{
			Name=Councilor_Text[91],
			NaSu={"Tai_RS_IonCannon",},
			RqSu={},
			RqSh="Tai_ResearchStation",
			Lock=
			{
				{
					Item=Councilor_Text[92],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[93],
			NaSu={"Tai_RS_Defense",},
			RqSu={"Tai_RS_IonCannon",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[94],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[95],
			NaSu={"Tai_RS_Capship",},
			RqSu={"Tai_RS_IonCannon",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[96],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[97],
			NaSu={"Tai_RS_SensorArray",},
			RqSu={"Tai_RS_Capship"},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[98],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[99],
			NaSu={"Tai_RS_Missile",},
			RqSu={"Tai_RS_Capship",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[100],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[101],
			NaSu={"Tai_RS_HeavyGun",},
			RqSu={"Tai_RS_Capship"},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[102],
					RqSu={},
					RqSh="",
				},
			},
		},
	},
	Vaygr=
	{
		{
			Name=Councilor_Text[103],
			NaSh="Vgr_Shipyard",
			RqSu={"Vgr_C_Module_Hyperspace", "Vgr_MS_Module_Hyperspace",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[104],
					RqSu={"Vgr_MS_Production_CapShip",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[105],
			NaSu={"Vgr_MS_Production_Fighter",},
			RqSu={},
			RqSh="Vgr_Mothership, Vgr_Shipyard",
			Lock=
			{
				{
					Item=Councilor_Text[106],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[107],
			NaSu={"Vgr_C_Module_NuclearBomb", "Vgr_MS_Module_NuclearBomb",},
			RqSu={"Vgr_MS_Production_Fighter",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[108],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[109],
			NaSu={"Vgr_C_Module_FighterLance", "Vgr_MS_Module_FighterLance",},
			RqSu={"Vgr_MS_Production_Fighter",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[110],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[111],
			NaSu={"Vgr_MS_Production_Corvette",},
			RqSu={"Vgr_MS_Production_Fighter",},
			RqSh="Vgr_Mothership, Vgr_Shipyard",
			Lock=
			{
				{
					Item=Councilor_Text[112],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[113],
			NaSu={"Vgr_C_Module_CorvetteLaser", "Vgr_MS_Module_CorvetteLaser",},
			RqSu={"Vgr_MS_Production_Corvette",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[114],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[115],
			NaSu={"Vgr_C_Module_Research","Vgr_MS_Module_Research",},
			RqSu={"Vgr_MS_Production_Corvette",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[116],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[117],
					RqSu={},
					RqSh="Vgr_Mothership, Vgr_Shipyard",
				},
			},
		},
		{
			Name=Councilor_Text[118],
			NaSu={"Vgr_C_Module_Hyperspace", "Vgr_MS_Module_Hyperspace",},
			RqSu={"Vgr_C_Module_Research","Vgr_MS_Module_Research",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[119],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[160],
					RqSu={"Vgr_MS_Production_CapShip",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[120],
			NaSu={"Vgr_MS_Production_Frigate",},
			RqSu={"Vgr_C_Module_Research","Vgr_MS_Module_Research",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[121],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[122],
			NaSu={"Vgr_C_Module_FrigateArtillery","Vgr_MS_Module_FrigateArtillery",},
			RqSu={"Vgr_MS_Production_Frigate",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[123],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[124],
			NaSu={"Vgr_C_Module_FrigateEW","Vgr_MS_Module_FrigateEW",},
			RqSu={"Vgr_MS_Production_Frigate",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[125],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[126],
			NaSu={"Vgr_C_Module_FrigateInfiltrator","Vgr_MS_Module_FrigateInfiltrator",},
			RqSu={"Vgr_MS_Production_Frigate",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[127],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[128],
			NaSu={"Vgr_MS_Production_CapShip",},
			RqSu={"Vgr_MS_Production_Frigate",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[129],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[162],
					RqSu={},
					RqSh="Vgr_Carrier",
				},
				{
					Item=Councilor_Text[163],
					RqSu={"Vgr_C_Module_Hyperspace", "Vgr_MS_Module_Hyperspace",},
					RqSh="",
				},
				{
					Item=Councilor_Text[161],
					RqSu={"Vgr_C_Module_Hyperspace", "Vgr_MS_Module_Hyperspace",},
					RqSh="Vgr_Carrier",
				},
			},
		},
		{
			Name=Councilor_Text[130],
			NaSu={"Vgr_SY_Production_CapShip",},
			RqSu={"Vgr_MS_Production_CapShip",},
			RqSh="Vgr_Shipyard",
			Lock=
			{
				{
					Item=Councilor_Text[131],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[166],
			NaSu={"Vgr_C_Production_Frigate",},
			RqSu={"Vgr_MS_Production_CapShip",},
			RqSh="Vgr_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[167],
					RqSu={},
					RqSh="",
				},
			},
		},
	},
	Turanic=
	{
		{
			Name=Councilor_Text[132],
			NaSu={"Tur_AS_Fighter",},
			RqSu={},
			RqSh="Tur_Shipyard",
			Lock=
			{
				{
					Item=Councilor_Text[133],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[134],
			NaSu={"Tur_R_LightWeapon",},
			RqSu={"Tur_AS_Fighter",},
			RqSh="Tur_ResourceController",
			Lock=
			{
				{
					Item=Councilor_Text[135],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[136],
					RqSu={"Tur_R_HeavyWeapon",},
					RqSh="",
				},
				{
					Item=Councilor_Text[176],
					RqSu={"Tur_AS_Frigate",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[137],
			NaSu={"Tur_R_HeavyWeapon",},
			RqSu={"Tur_AS_Fighter",},
			RqSh="Tur_ResourceController",
			Lock=
			{
				{
					Item=Councilor_Text[138],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[177],
					RqSu={"Tur_R_LightWeapon",},
					RqSh="",
				},
				{
					Item=Councilor_Text[139],
					RqSu={"Tur_AS_Frigate",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[140],
			NaSu={"Tur_AS_Frigate",},
			RqSu={"Tur_R_LightWeapon","Tur_R_HeavyWeapon",},
			RqSh="Tur_Shipyard",
			Lock=
			{
				{
					Item=Councilor_Text[174],
					RqSu={},
					RqSh="",
				},
				{
					Item=Councilor_Text[141],
					RqSu={"Tur_R_LightWeapon",},
					RqSh="",
				},
				{
					Item=Councilor_Text[175],
					RqSu={"Tur_R_HeavyWeapon",},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[142],
			NaSu={"Tur_AS_FrigateAdvanced",},
			RqSu={"Tur_AS_Frigate",},
			RqSh="Tur_Shipyard",
			Lock=
			{
				{
					Item=Councilor_Text[143],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[144],
			NaSu={"Tur_AS_FrigateCapture",},
			RqSu={"Tur_AS_Frigate",},
			RqSh="Tur_Shipyard",
			Lock=
			{
				{
					Item=Councilor_Text[145],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[146],
			NaSu={"Tur_AS_Hyperspace","Tur_R_hyperspace",},
			RqSu={"Tur_R_LightWeapon","Tur_R_HeavyWeapon",},
			RqSh="Tur_Shipyard, Tur_ResourceController",
			Lock=
			{
				{
					Item=Councilor_Text[147],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[148],
			NaSu={"Tur_AS_CapShip",},
			RqSu={"Tur_AS_Frigate",},
			RqSh="Tur_Shipyard",
			Lock=
			{
				{
					Item=Councilor_Text[149],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[150],
			NaSu={"Tur_AS_HeavyGunArray",},
			RqSu={"Tur_AS_CapShip",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[151],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[152],
			NaSu={"Tur_AS_CapShipAdvanced",},
			RqSu={"Tur_AS_HeavyGunArray",},
			RqSh="",
			Lock=
			{
				{
					Item=Councilor_Text[153],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[154],
			NaSu={"Tur_R_turret",},
			RqSu={"Tur_R_LightWeapon",},
			RqSh="Tur_ResourceController",
			Lock=
			{
				{
					Item=Councilor_Text[155],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[156],
			NaSu={"Tur_AC_HeavyMissile",},
			RqSu={"Tur_AS_CapShipAdvanced",},
			RqSh="Tur_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[157],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[178],
			NaSu={"Tur_AC_Frigate",},
			RqSu={},
			RqSh="Tur_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[179],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[201],
			NaSu={"Tur_AC_Repair",},
			RqSu={},
			RqSh="Tur_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[202],
					RqSu={},
					RqSh="",
				},
			},
		},
		{
			Name=Councilor_Text[203],
			NaSu={"Tur_AC_Raid",},
			RqSu={"Tur_AS_CapShipAdvanced",},
			RqSh="Tur_Carrier",
			Lock=
			{
				{
					Item=Councilor_Text[204],
					RqSu={},
					RqSh="",
				},
			},
		},
	},
}

Councilor_Suggestions=
{
	function(iPlayer,iRace,Councilor_MData)
		if(CouncilorRaceData[iRace].AntiFr[1]~=nil)and(Councilor_MData.AAFr+CouncilorData[iPlayer].AntiFr<0.5*Councilor_MData.EFrigate)and(Councilor_MData.EFrigate>50)then
			local iText=Councilor_Text[181]
			return Concilor_RecommandItem(iPlayer,iRace,iText,CouncilorRaceData[iRace].AntiFr)
		end
		return 0
	end,
	function(iPlayer,iRace,Councilor_MData)
		if (CouncilorRaceData[iRace].AntiFi[1]~=nil)and(Councilor_MData.EFighter>0.5*(Councilor_MData.ECorvette+Councilor_MData.EFrigate))and(Councilor_MData.AAFi+CouncilorData[iPlayer].AntiFi<Councilor_MData.EFighter)then
			local iText=Councilor_Text[182]
			return Concilor_RecommandItem(iPlayer,iRace,iText,CouncilorRaceData[iRace].AntiFi)
		end
		return 0
	end,
	function(iPlayer,iRace,Councilor_MData)
		if (CouncilorRaceData[iRace].AntiCo[1]~=nil)and(Councilor_MData.ECorvette>0.5*(Councilor_MData.EFighter+Councilor_MData.EFrigate))and(Councilor_MData.AACo+CouncilorData[iPlayer].AntiCo<Councilor_MData.ECorvette)then
			local iText=Councilor_Text[183]
			return Concilor_RecommandItem(iPlayer,iRace,iText,CouncilorRaceData[iRace].AntiCo)
		end
		return 0
	end,
	function(iPlayer,iRace,Councilor_MData)
		if(CouncilorData[iPlayer].Fighter>0.5*(CouncilorData[iPlayer].Corvette+CouncilorData[iPlayer].Frigate))and(Councilor_MData.EAFi>CouncilorData[iPlayer].Fighter)then
			local iText=Councilor_Text[184]
			Subtitle_Add2(Councilor_Actor[iRace].Military, iText)
			return 1
		end
		return 0
	end,
	function(iPlayer,iRace,Councilor_MData)
		if(CouncilorData[iPlayer].Corvette>0.5*(CouncilorData[iPlayer].Fighter+CouncilorData[iPlayer].Frigate))and(Councilor_MData.EACo>CouncilorData[iPlayer].Corvette)then
			local iText=Councilor_Text[185]
			Subtitle_Add2(Councilor_Actor[iRace].Military, iText)
			return 1
		end
		return 0
	end,
	function(iPlayer,iRace,Councilor_MData)
		if(CouncilorData[iPlayer].Frigate>2*(CouncilorData[iPlayer].Fighter+CouncilorData[iPlayer].Corvette))and(Councilor_MData.EAFi+Councilor_MData.EACo<Councilor_MData.AFighter+Councilor_MData.ACorvette)then
			local iText=Councilor_Text[186]
			Subtitle_Add2(Councilor_Actor[iRace].Military, iText)
			return 1
		end
		return 0
	end,
	function(iPlayer,iRace,Councilor_MData)
		if (Universe_GameTime()>180) then
			local iText=""
			local iTIndex={{"EAFi","Fighter",Councilor_Text[196]},{"EACo","Corvette",Councilor_Text[197]},{"EAFr","Frigate",Councilor_Text[198]}}
			local iIndex=random(3)
			if(Councilor_MData[iTIndex[iIndex][1]]>1.5*CouncilorData[iPlayer][iTIndex[iIndex][2]])and(CouncilorData[iPlayer][iTIndex[iIndex][2]]>0)then
				iText=Councilor_Text[195]..iTIndex[iIndex][3]..Councilor_Text[199]
				Subtitle_Add2(Councilor_Actor[iRace].Military, iText)
				return 1
			elseif(Councilor_MData[iTIndex[iIndex][1]]<0.5*CouncilorData[iPlayer][iTIndex[iIndex][2]])then
				iText=Councilor_Text[195]..iTIndex[iIndex][3]..Councilor_Text[200]
				Subtitle_Add2(Councilor_Actor[iRace].Military, iText)
				return 1
			end
		end
		return 0
	end,
	function(iPlayer,iRace,Councilor_MData)
		if (Universe_GameTime()>180) then
			local iText=""
			if(Councilor_MData.EFighter+Councilor_MData.ECorvette+Councilor_MData.EFrigate<0.8*(CouncilorData[iPlayer].Fighter+CouncilorData[iPlayer].Corvette+CouncilorData[iPlayer].Frigate+Councilor_MData.AFighter+Councilor_MData.ACorvette+Councilor_MData.AFrigate))then
				iText=Councilor_Text[187]
			elseif(Councilor_MData.EFighter+Councilor_MData.ECorvette+Councilor_MData.EFrigate>1.25*(CouncilorData[iPlayer].Fighter+CouncilorData[iPlayer].Corvette+CouncilorData[iPlayer].Frigate+Councilor_MData.AFighter+Councilor_MData.ACorvette+Councilor_MData.AFrigate))then
				iText=Councilor_Text[188]
			else
				iText=Councilor_Text[189]
			end
			Subtitle_Add2(Councilor_Actor[iRace].Military, iText)
			return 1
		end
		return 0
	end,
	function(iPlayer,iRace,Councilor_MData)
		if (Councilor_DevelopData[iRace]~=nil) then
			local iIndex=1
			local iFlag=0
			local iPoss={}
			while (Councilor_DevelopData[iRace][iIndex]~=nil) do
				iFlag=Councilor_DevelopPossible(iPlayer,Councilor_DevelopData[iRace][iIndex])
				if (iFlag==1) then
					tinsert(iPoss,iIndex)
				end
				iIndex=iIndex+1
			end
			if (iPoss[1]~=nil) then
				iIndex=iPoss[random(getn(iPoss))]
				iFlag=getn(Councilor_DevelopData[iRace][iIndex].Lock)
				while (iFlag>0) do
					if(Councilor_DevelopPossible2(iPlayer,Councilor_DevelopData[iRace][iIndex].Lock[iFlag])==1)then
						break
					else
						iFlag=iFlag-1
					end
				end
				if (iFlag>0) then
					local iText=Councilor_Text[190]..Councilor_DevelopData[iRace][iIndex].Name..Councilor_Text[191]..Councilor_DevelopData[iRace][iIndex].Lock[iFlag].Item
					Subtitle_Add2(Councilor_Actor[iRace].Military, iText)
					return 1
				end
			end
		end
		return 0
	end,
	function(iPlayer,iRace,Councilor_MData)
		--if(iRace~="Observer")then
			local numBuilder=0
			local iIndex=1
			while(CouncilorRaceData[iRace].Builder[iIndex]~=nil) do
				numBuilder = numBuilder + Player_GetNumberOfSquadronsOfTypeAwakeOrSleeping(iPlayer, CouncilorRaceData[iRace].Builder[iIndex][1])
				iIndex=iIndex+1
			end
			iIndex=1
			local numWorker=0
			while(CouncilorRaceData[iRace].Worker[iIndex]~=nil) do
				numWorker = numWorker + Player_GetNumberOfSquadronsOfTypeAwakeOrSleeping(iPlayer, CouncilorRaceData[iRace].Worker[iIndex][1])
				iIndex=iIndex+1
			end
			if (3.5*numBuilder>numWorker)and(Player_GetRU(iPlayer)<1000) then
				local iText=Councilor_Text[192]
				Subtitle_Add3(Councilor_Actor[iRace].Military, iText, CouncilorRaceData[iRace].Worker[random(getn(CouncilorRaceData[iRace].Worker))][2])
				return 1
			elseif (4.5*numBuilder<numWorker)and(Player_GetRU(iPlayer)>2000) then
				local iText=Councilor_Text[193]
				Subtitle_Add2(Councilor_Actor[iRace].Military, iText)
				return 1
			end
			return 0
		--else
		--	return 0
		--end
	end,
}
