Ship = 0
SubSystem = 1
build = {
--  {
--    Type = SubSystem,
--    ThingToBuild = "vgr_dc_Missiledefense_turret",
--    RequiredResearch = "",
--    RequiredFleetSubSystems = "Research",
--    DisplayPriority = 1,
--    DisplayedName = "$2140",
--    Description = "$8004",
--  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_c_module_frigateinfiltrator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 5,
    DisplayedName = "$8128",
    Description = "$8129",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_ms_module_frigateinfiltrator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 5,
    DisplayedName = "$8128",
    Description = "$8129",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_c_module_frigateEW",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 4,
    DisplayedName = "$8126",
    Description = "$8127",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_ms_module_frigateEW",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 4,
    DisplayedName = "$8126",
    Description = "$8127",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_c_module_frigateartillery",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 3,
    DisplayedName = "$8124",
    Description = "$8125",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_ms_module_frigateartillery",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 3,
    DisplayedName = "$8124",
    Description = "$8125",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_c_module_corvettelaser",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CorvetteProduction",
    DisplayPriority = 2,
    DisplayedName = "$8122",
    Description = "$8123",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_ms_module_corvettelaser",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CorvetteProduction",
    DisplayPriority = 2,
    DisplayedName = "$8122",
    Description = "$8123",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_c_module_fighterlance",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 1,
    DisplayedName = "$8120",
    Description = "$8121",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_ms_module_fighterlance",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 1,
    DisplayedName = "$8120",
    Description = "$8121",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_c_module_nuclearbomb",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 0,
    DisplayedName = "$8118",
    Description = "$8119",
  },
  {
    Type = SubSystem,
    ThingToBuild = "vgr_ms_module_nuclearbomb",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 0,
    DisplayedName = "$8118",
    Description = "$8119",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Production_Fighter",
    RequiredResearch = "",
    RequiredFleetSubSystems = "! FighterProduction",
    DisplayPriority = 0,
    DisplayedName = "$7100",
    Description = "$7101",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Production_Fighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "! FighterProduction",
    DisplayPriority = 0,
    DisplayedName = "$7100",
    Description = "$7101",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Production_Corvette",
    RequiredResearch = "FighterTech",
    RequiredFleetSubSystems = "! CorvetteProduction",
    DisplayPriority = 0,
    DisplayedName = "$7102",
    Description = "$7103",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Production_Corvette",
    RequiredResearch = "FighterTech",
    RequiredFleetSubSystems = "! CorvetteProduction",
    DisplayPriority = 10,
    DisplayedName = "$7102",
    Description = "$7103",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Production_Frigate",
    RequiredResearch = "ResearchTech",
    RequiredFleetSubSystems = "! FrigateProduction",
    DisplayPriority = 0,
    DisplayedName = "$7104",
    Description = "$7105",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Production_Frigate",
    RequiredResearch = "ResearchTech",
    RequiredFleetSubSystems = "! FrigateProduction",
    DisplayPriority = 20,
    DisplayedName = "$7104",
    Description = "$7105",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_PlatformControl",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7108",
    Description = "$7109",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_PlatformControl",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 0,
    DisplayedName = "$7108",
    Description = "$7109",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Production_CapShip",
    RequiredResearch = "FrigateTech",
    RequiredFleetSubSystems = "! CapShipProduction",
    DisplayPriority = 30,
    DisplayedName = "$7106",
    Description = "$7107",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_SY_Production_CapShip",
    RequiredResearch = "CapShipTech",
    RequiredFleetSubSystems = "! AdvancedCapShipProduction",
    DisplayPriority = 30,
    DisplayedName = "$8112",
    Description = "$8130",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_Research",
    RequiredResearch = "CorvetteTech",
    RequiredShipSubSystems = "",
    DisplayPriority = 10,
    DisplayedName = "$7110",
    Description = "$7111",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_Research",
    RequiredResearch = "CorvetteTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 40,
    DisplayedName = "$7110",
    Description = "$7111",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_CloakGenerator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 15,
    DisplayedName = "$7118",
    Description = "$7119",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_CloakGenerator",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 15,
    DisplayedName = "$7118",
    Description = "$7119",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 16,
    DisplayedName = "$7116",
    Description = "$7117",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 16,
    DisplayedName = "$7116",
    Description = "$7117",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_FireControl",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 21,
    DisplayedName = "$7120",
    Description = "$7121",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_FireControl",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 21,
    DisplayedName = "$7120",
    Description = "$7121",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Module_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 20,
    DisplayedName = "$7114",
    Description = "$7115",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Module_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 50,
    DisplayedName = "$7114",
    Description = "$7115",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Sensors_AdvancedArray",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 25,
    DisplayedName = "$7122",
    Description = "$7123",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Sensors_AdvancedArray",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 25,
    DisplayedName = "$7122",
    Description = "$7123",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_C_Sensors_DetectHyperspace",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 30,
    DisplayedName = "$7126",
    Description = "$7127",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Vgr_MS_Sensors_DetectHyperspace",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 30,
    DisplayedName = "$7126",
    Description = "$7127",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Scout",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 20,
    DisplayedName = "$7130",
    Description = "$7131",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Interceptor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 21,
    DisplayedName = "$7132",
    Description = "$7133",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Bomber",
    RequiredResearch = "",
    RequiredShipSubSystems = "NuclearBomb",
    --RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 22,
    DisplayedName = "$7134",
    Description = "$7135",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_LanceFighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "FighterLance",
    --RequiredFleetSubSystems = "FighterProduction",
    DisplayPriority = 24,
    DisplayedName = "$7136",
    Description = "$7137",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_MissileCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CorvetteProduction",
    DisplayPriority = 160,
    DisplayedName = "$7138",
    Description = "$7139",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_LaserCorvette",
    RequiredResearch = "",
    RequiredShipSubSystems = "CorvetteLaser",
    --RequiredFleetSubSystems = "CorvetteProduction",
    DisplayPriority = 161,
    DisplayedName = "$7140",
    Description = "$7141",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_CommandCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CorvetteProduction & Research",
    DisplayPriority = 162,
    DisplayedName = "$7144",
    Description = "$7145",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_MinelayerCorvette",
    RequiredResearch = "CorvetteGraviticAttraction",
    RequiredShipSubSystems = "CorvetteProduction",
    DisplayPriority = 163,
    DisplayedName = "$7142",
    Description = "$7143",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_AssaultFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 200,
    DisplayedName = "$7146",
    Description = "$7147",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_HeavyMissileFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 210,
    DisplayedName = "$7148",
    Description = "$7149",
  },
  { 
    Type = Ship, 
    ThingToBuild = "Vgr_ArtilleryFrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateArtillery",
    --RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 220,
    DisplayedName = "$7976",
    Description = "$7977" 
  },
  { 
    Type = Ship, 
    ThingToBuild = "vgr_EWfighter",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateEW",
    --RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 230,
    DisplayedName = "$8013",
    Description = "$8014" 
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_InfiltratorFrigate",
    RequiredResearch = "",
    RequiredShipSubSystems = "FrigateInfiltrator",
    --RequiredFleetSubSystems = "FrigateProduction",
    DisplayPriority = 240,
    DisplayedName = "$7150",
    Description = "$7151",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Carrier",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 250,
    DisplayedName = "$7154",
    Description = "$7155",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_ShipYard",
    RequiredResearch = "",
    RequiredShipSubSystems = "Hyperspace",
    DisplayPriority = 260,
    DisplayedName = "$7156",
    Description = "$7157",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Destroyer",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CapShipProduction | AdvancedCapShipProduction",
    DisplayPriority = 265,
    DisplayedName = "$7152",
    Description = "$7153",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_BattleCruiser",
    RequiredResearch = "",
    RequiredFleetSubSystems = "AdvancedCapShipProduction",
    DisplayPriority = 280,
    DisplayedName = "$7158",
    Description = "$7159",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_WeaponPlatform_gun",
    RequiredResearch = "",
    RequiredShipSubSystems = "PlatformProduction",
    DisplayPriority = 300,
    DisplayedName = "$7160",
    Description = "$7161",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_WeaponPlatform_missile",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 310,
    DisplayedName = "$7162",
    Description = "$7163",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_ResourceCollector",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 320,
    DisplayedName = "$7164",
    Description = "$7165",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_ResourceController",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 330,
    DisplayedName = "$7166",
    Description = "$7167",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_HyperSpace_Platform",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Hyperspace",
    DisplayPriority = 340,
    DisplayedName = "$7174",
    Description = "$7175",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Probe",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 350,
    DisplayedName = "$7168",
    Description = "$7169",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Probe_Prox",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research",
    DisplayPriority = 360,
    DisplayedName = "$7170",
    Description = "$7171",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_Probe_ECM",
    RequiredResearch = "ProbeSensorDisruption",
    RequiredShipSubSystems = "",
    DisplayPriority = 370,
    DisplayedName = "$7172",
    Description = "$7173",
  },
  {
    Type = Ship,
    ThingToBuild = "Vgr_PlanetKillerMissile",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 380,
    DisplayedName = "Honking big planet killing missile",
    Description = "",
  },
}
