dofilepath("Data:leveldata/multiplayer/lib/FXGDeathmatch_Data.lua")

Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
BLUE = 0
YELLOW = 1
RED = nil
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "FXGDM",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
  },
  {
    Name = "Branch1",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "机动舰队",
    DisplayPriority = 1,
    Description = "机动舰队是维格尔人实施侵略的先头部队，凭借闪电般的速度，他们能够轻易将对方的防线撕碎，而后敌人便会很快被蜂拥而至的维格尔大军淹没。\n可召唤突袭舰进入战场\n突击机飞行速度更快\n突袭舰造价更低\n建造主力舰生产设施后立即获得一艘航母\n航母装甲更厚",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Speed,
    ShortDisplayedName = "机动舰队",
  },
  {
    Name = "Branch2",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "掠夺部队",
    DisplayPriority = 2,
    Description = "掠夺部队在维格尔占领区内活动，他们不放过任何能够充实维格尔大军的猎物。他们不仅对弱小的猎物下手，更敢于虎口夺食。\n可召唤渗透船进入战场\n轰炸机飞行速度更快\n渗透船造价更低\n建造护卫舰生产设施后立即获得主力舰生产设施\n战列巡洋舰装甲更厚",
    UpgradeType = RED,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_Attack,
    ShortDisplayedName = "掠夺部队",
  },
  {
    Name = "Branch3",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 123,
    Time = 100,
    DisplayedName = "精锐卫队",
    DisplayPriority = 3,
    Description = "精锐卫队曾始终不离马坎左右，是维格尔战斗力最强的一支部队。在马坎死后，他们拒绝了所有军阀的收编，为了生存，他们成为了一支劫掠舰队，虽然失去资源支持的他们实力有所下降，但仍是任何人都不能小觑的一支力量。\n可召唤重型导弹护卫舰进入战场\n长枪战斗机飞行速度更快\n重型导弹护卫舰造价更低\n建造主力舰模块后立即获得一艘驱逐舰\n驱逐舰装甲更厚",
    UpgradeType = BLUE,
		TargetType =		Ship,
		TargetName =		"hgn_scout",
    Icon = Icon_shield,
    ShortDisplayedName = "精锐卫队",
  },
  {
    Name = "Sumon_AssaultFrigate",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "FrigateProduction",
    Cost = FXG_Sumon_Data.Vaygr[1].Cost,
    Time = 100,
    DisplayedName = "召唤突袭舰进入战场",
    DisplayPriority = 0,
    Description = "突袭舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"vgr_assaultfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "突袭舰",
  },
  {
    Name = "Sumon_InfiltratorFrigate",
    RequiredResearch = "Branch2",
    RequiredSubSystems = "FrigateInfiltrator",
    Cost = FXG_Sumon_Data.Vaygr[2].Cost,
    Time = 100,
    DisplayedName = "召唤渗透船进入战场",
    DisplayPriority = 0,
    Description = "渗透船",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"vgr_infiltratorfrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "渗透船",
  },
  {
    Name = "Sumon_HeavyMissileFrigate",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "FrigateProduction",
    Cost = FXG_Sumon_Data.Vaygr[3].Cost,
    Time = 100,
    DisplayedName = "召唤重型导弹护卫舰进入战场",
    DisplayPriority = 0,
    Description = "重型导弹护卫舰",
    UpgradeType = YELLOW,
		TargetType =		Ship,
		TargetName =		"vgr_heavymissilefrigate",
    Icon = Icon_Hyperspace,
    ShortDisplayedName = "重型导弹护卫舰",
  },
  {
    Name = "InstantBuild_Carrier",
    RequiredResearch = "Branch1",
    RequiredSubSystems = "CapShipProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_CapShipProduction",
    RequiredResearch = "Branch2",
    RequiredSubSystems = "FrigateProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "InstantBuild_Destroyer",
    RequiredResearch = "Branch3",
    RequiredSubSystems = "CapShipProduction",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "FighterTech",
    RequiredResearch = "",
    RequiredSubSystems = "FighterProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8015",
    DisplayPriority = 0,
    Description = "$8016",
    TargetType = Family,
    TargetName = "Corvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8023",
  },
  {
    Name = "CorvetteTech",
    RequiredResearch = "",
    RequiredSubSystems = "CorvetteProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8015",
    DisplayPriority = 10,
    Description = "$8016",
    TargetType = Family,
    TargetName = "Corvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8023",
  },
  {
    Name = "ResearchTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8015",
    DisplayPriority = 20,
    Description = "$8016",
    TargetType = Family,
    TargetName = "Corvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8023",
  },
  {
    Name = "FrigateTech",
    RequiredResearch = "",
    RequiredSubSystems = "FrigateProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8019",
    DisplayPriority = 30,
    Description = "$8020",
    TargetType = Family,
    TargetName = "Frigate",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8019",
  },
  {
    Name = "CapShipTech",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8015",
    DisplayPriority = 40,
    Description = "$8016",
    TargetType = Family,
    TargetName = "Corvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8023",
  },
  {
    Name = "infiltratorfrigateCloak",
    RequiredResearch = "FrigateInfiltrationTech",
    RequiredSubSystems = "Research & FrigateProduction",
    Cost = 350,
    Time = 25,
    DisplayedName = "$8005",
    DisplayPriority = 253,
    Description = "$8006",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "vgr_infiltratorfrigate",
    UpgradeName = "Cloak",
    Icon = Icon_Cloak,
    ShortDisplayedName = "$8005",
  },
  {
    Name = "RepairAbility",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 250,
    Time = 15,
    DisplayedName = "$7724",
    DisplayPriority = 280,
    Description = "$7725",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Vgr_ResourceCollector",
    UpgradeName = "Repair",
    Icon = Icon_Repair,
    ShortDisplayedName = "$7311",
  },
-------------------------------------
-------------------------------------
-------------------------------------
  {
    Name = "vgr_AirWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8076",
    DisplayPriority = 100,
    Description = "$8077",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8076",
  },
  {
    Name = "vgr_AirWeaponUpgrade2",
    RequiredResearch = "vgr_AirWeaponUpgrade1",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8078",
    DisplayPriority = 100,
    Description = "$8079",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8078",
  },
  {
    Name = "vgr_AirWeaponUpgrade3",
    RequiredResearch = "vgr_AirWeaponUpgrade2",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8080",
    DisplayPriority = 100,
    Description = "$8081",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8080",
  },
  {
    Name = "vgr_FighterHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8082",
    DisplayPriority = 101,
    Description = "$8083",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8082",
  },
  {
    Name = "vgr_FighterHealthUpgrade2",
    RequiredResearch = "vgr_FighterHealthUpgrade1",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8084",
    DisplayPriority = 101,
    Description = "$8085",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8084",
  },
  {
    Name = "vgr_FighterHealthUpgrade3",
    RequiredResearch = "vgr_FighterHealthUpgrade2",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8086",
    DisplayPriority = 101,
    Description = "$8087",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8086",
  },
  {
    Name = "vgr_CorvetteHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8088",
    DisplayPriority = 101,
    Description = "$8089",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.15,
    Icon = Icon_Health,
    ShortDisplayedName = "$8088",
  },
  {
    Name = "vgr_CorvetteHealthUpgrade2",
    RequiredResearch = "vgr_CorvetteHealthUpgrade1",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8090",
    DisplayPriority = 101,
    Description = "$8091",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.25,
    Icon = Icon_Health,
    ShortDisplayedName = "$8090",
  },
  {
    Name = "vgr_CorvetteHealthUpgrade3",
    RequiredResearch = "vgr_CorvetteHealthUpgrade2",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8092",
    DisplayPriority = 101,
    Description = "$8093",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.35,
    Icon = Icon_Health,
    ShortDisplayedName = "$8092",
  },
  {
    Name = "vgr_ShipWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FrigateProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8094",
    DisplayPriority = 300,
    Description = "$8095",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8094",
  },
  {
    Name = "vgr_ShipWeaponUpgrade2",
    RequiredResearch = "vgr_ShipWeaponUpgrade1",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8096",
    DisplayPriority = 300,
    Description = "$8097",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8096",
  },
  {
    Name = "vgr_ShipWeaponUpgrade3",
    RequiredResearch = "vgr_ShipWeaponUpgrade2",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8098",
    DisplayPriority = 300,
    Description = "$8099",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8098",
  },
  {
    Name = "vgr_frigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & frigateProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8100",
    DisplayPriority = 301,
    Description = "$8101",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8100",
  },
  {
    Name = "vgr_frigateHealthUpgrade2",
    RequiredResearch = "vgr_frigateHealthUpgrade1",
    RequiredSubSystems = "Research & frigateProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8102",
    DisplayPriority = 301,
    Description = "$8103",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$8102",
  },
  {
    Name = "vgr_frigateHealthUpgrade3",
    RequiredResearch = "vgr_frigateHealthUpgrade2",
    RequiredSubSystems = "Research & frigateProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8104",
    DisplayPriority = 301,
    Description = "$8105",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$8104",
  },
  {
    Name = "vgr_CapitalHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8106",
    DisplayPriority = 301,
    Description = "$8107",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.15,
    Icon = Icon_Health,
    ShortDisplayedName = "$8106",
  },
  {
    Name = "vgr_CapitalHealthUpgrade2",
    RequiredResearch = "vgr_CapitalHealthUpgrade1",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8108",
    DisplayPriority = 301,
    Description = "$8109",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.25,
    Icon = Icon_Health,
    ShortDisplayedName = "$8108",
  },
  {
    Name = "vgr_CapitalHealthUpgrade3",
    RequiredResearch = "vgr_CapitalHealthUpgrade2",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8110",
    DisplayPriority = 301,
    Description = "$8111",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.35,
    Icon = Icon_Health,
    ShortDisplayedName = "$8110",
  },
  {
    Name = "vgr_AirWeaponUpgrade11",
    RequiredResearch = "vgr_AirWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8076",
    DisplayPriority = 100,
    Description = "$8077",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8076",
  },
  {
    Name = "vgr_AirWeaponUpgrade21",
    RequiredResearch = "vgr_AirWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8078",
    DisplayPriority = 100,
    Description = "$8079",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8078",
  },
  {
    Name = "vgr_AirWeaponUpgrade31",
    RequiredResearch = "vgr_AirWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8080",
    DisplayPriority = 100,
    Description = "$8081",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8080",
  },
  {
    Name = "vgr_ShipWeaponUpgrade11",
    RequiredResearch = "vgr_ShipWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8094",
    DisplayPriority = 300,
    Description = "$8095",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8094",
  },
  {
    Name = "vgr_ShipWeaponUpgrade21",
    RequiredResearch = "vgr_ShipWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8096",
    DisplayPriority = 300,
    Description = "$8097",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8096",
  },
  {
    Name = "vgr_ShipWeaponUpgrade31",
    RequiredResearch = "vgr_ShipWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8098",
    DisplayPriority = 300,
    Description = "$8099",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8098",
  },
--AI behaviour	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed	
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.025,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.05,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.075,
	},
--AI resource rate	
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},			
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")