Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "FighterTech",
    RequiredResearch = "",
    RequiredSubSystems = "FighterProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8015",
    DisplayPriority = 0,
    Description = "$8016",
    TargetType = Family,
    TargetName = "Corvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8023",
  },
  {
    Name = "CorvetteTech",
    RequiredResearch = "",
    RequiredSubSystems = "CorvetteProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8015",
    DisplayPriority = 10,
    Description = "$8016",
    TargetType = Family,
    TargetName = "Corvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8023",
  },
  {
    Name = "ResearchTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8015",
    DisplayPriority = 20,
    Description = "$8016",
    TargetType = Family,
    TargetName = "Corvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8023",
  },
  {
    Name = "FrigateTech",
    RequiredResearch = "",
    RequiredSubSystems = "FrigateProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8019",
    DisplayPriority = 30,
    Description = "$8020",
    TargetType = Family,
    TargetName = "Frigate",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8019",
  },
  {
    Name = "CapShipTech",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8015",
    DisplayPriority = 40,
    Description = "$8016",
    TargetType = Family,
    TargetName = "Corvette",
    Icon = Icon_Tech,
    ShortDisplayedName = "$8023",
  },
  {
    Name = "RepairAbility",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 250,
    Time = 15,
    DisplayedName = "$7724",
    DisplayPriority = 280,
    Description = "$7725",
    UpgradeType = Ability,
    TargetType = Ship,
    TargetName = "Vgr_ResourceCollector",
    UpgradeName = "Repair",
    Icon = Icon_Repair,
    ShortDisplayedName = "$7311",
  },

-------------------------------------
-------------------------------------
-------------------------------------
  {
    Name = "vgr_AirWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8076",
    DisplayPriority = 100,
    Description = "$8077",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8076",
  },
  {
    Name = "vgr_AirWeaponUpgrade2",
    RequiredResearch = "vgr_AirWeaponUpgrade1",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8078",
    DisplayPriority = 100,
    Description = "$8079",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8078",
  },
  {
    Name = "vgr_AirWeaponUpgrade3",
    RequiredResearch = "vgr_AirWeaponUpgrade2",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8080",
    DisplayPriority = 100,
    Description = "$8081",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8080",
  },
  {
    Name = "vgr_FighterHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 300,
    Time = 48,
    DisplayedName = "$8082",
    DisplayPriority = 101,
    Description = "$8083",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8082",
  },
  {
    Name = "vgr_FighterHealthUpgrade2",
    RequiredResearch = "vgr_FighterHealthUpgrade1",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 450,
    Time = 72,
    DisplayedName = "$8084",
    DisplayPriority = 101,
    Description = "$8085",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8084",
  },
  {
    Name = "vgr_FighterHealthUpgrade3",
    RequiredResearch = "vgr_FighterHealthUpgrade2",
    RequiredSubSystems = "Research & FighterProduction",
    Cost = 600,
    Time = 96,
    DisplayedName = "$8086",
    DisplayPriority = 101,
    Description = "$8087",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8086",
  },
  {
    Name = "vgr_CorvetteHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 200,
    Time = 32,
    DisplayedName = "$8088",
    DisplayPriority = 101,
    Description = "$8089",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8088",
  },
  {
    Name = "vgr_CorvetteHealthUpgrade2",
    RequiredResearch = "vgr_CorvetteHealthUpgrade1",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 300,
    Time = 40,
    DisplayedName = "$8090",
    DisplayPriority = 101,
    Description = "$8091",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8090",
  },
  {
    Name = "vgr_CorvetteHealthUpgrade3",
    RequiredResearch = "vgr_CorvetteHealthUpgrade2",
    RequiredSubSystems = "Research & CorvetteProduction",
    Cost = 400,
    Time = 48,
    DisplayedName = "$8092",
    DisplayPriority = 101,
    Description = "$8093",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8092",
  },
  {
    Name = "vgr_ShipWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & FrigateProduction",
    Cost = 1000,
    Time = 160,
    DisplayedName = "$8094",
    DisplayPriority = 300,
    Description = "$8095",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8094",
  },
  {
    Name = "vgr_ShipWeaponUpgrade2",
    RequiredResearch = "vgr_ShipWeaponUpgrade1",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 1500,
    Time = 200,
    DisplayedName = "$8096",
    DisplayPriority = 300,
    Description = "$8097",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8096",
  },
  {
    Name = "vgr_ShipWeaponUpgrade3",
    RequiredResearch = "vgr_ShipWeaponUpgrade2",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 2000,
    Time = 240,
    DisplayedName = "$8098",
    DisplayPriority = 300,
    Description = "$8099",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8098",
  },
  {
    Name = "vgr_frigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & frigateProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8100",
    DisplayPriority = 301,
    Description = "$8101",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8100",
  },
  {
    Name = "vgr_frigateHealthUpgrade2",
    RequiredResearch = "vgr_frigateHealthUpgrade1",
    RequiredSubSystems = "Research & frigateProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8102",
    DisplayPriority = 301,
    Description = "$8103",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$8102",
  },
  {
    Name = "vgr_frigateHealthUpgrade3",
    RequiredResearch = "vgr_frigateHealthUpgrade2",
    RequiredSubSystems = "Research & frigateProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8104",
    DisplayPriority = 301,
    Description = "$8105",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$8104",
  },
  {
    Name = "vgr_CapitalHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 500,
    Time = 80,
    DisplayedName = "$8106",
    DisplayPriority = 301,
    Description = "$8107",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$8106",
  },
  {
    Name = "vgr_CapitalHealthUpgrade2",
    RequiredResearch = "vgr_CapitalHealthUpgrade1",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 750,
    Time = 100,
    DisplayedName = "$8108",
    DisplayPriority = 301,
    Description = "$8109",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$8108",
  },
  {
    Name = "vgr_CapitalHealthUpgrade3",
    RequiredResearch = "vgr_CapitalHealthUpgrade2",
    RequiredSubSystems = "Research & CapShipProduction",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$8110",
    DisplayPriority = 301,
    Description = "$8111",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$8110",
  },
  {
    Name = "vgr_AirWeaponUpgrade11",
    RequiredResearch = "vgr_AirWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8076",
    DisplayPriority = 100,
    Description = "$8077",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8076",
  },
  {
    Name = "vgr_AirWeaponUpgrade21",
    RequiredResearch = "vgr_AirWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8078",
    DisplayPriority = 100,
    Description = "$8079",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8078",
  },
  {
    Name = "vgr_AirWeaponUpgrade31",
    RequiredResearch = "vgr_AirWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8080",
    DisplayPriority = 100,
    Description = "$8081",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8080",
  },
  {
    Name = "vgr_ShipWeaponUpgrade11",
    RequiredResearch = "vgr_ShipWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8094",
    DisplayPriority = 300,
    Description = "$8095",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8094",
  },
  {
    Name = "vgr_ShipWeaponUpgrade21",
    RequiredResearch = "vgr_ShipWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8096",
    DisplayPriority = 300,
    Description = "$8097",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8096",
  },
  {
    Name = "vgr_ShipWeaponUpgrade31",
    RequiredResearch = "vgr_ShipWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$8098",
    DisplayPriority = 300,
    Description = "$8099",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$8098",
  },
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")
dofilepath("data:scripts/races/vaygr/scripts/SPReserch.lua")