Ship = 0
SubSystem = 1
build = {
  {
    Type = Ship,
    ThingToBuild = "Tai_ResearchShip_1f",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & FighterModule & (!FighterProduction)",
    DisplayPriority = 1,
    DisplayedName = "$9611",
    Description = "$9612",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_ResearchShip_2f",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & FighterModule & (!defensefighters)",
    DisplayPriority = 2,
    DisplayedName = "$9613",
    Description = "$9614",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_ResearchShip_3f",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & FighterModule & (!CorvetteProduction)",
    DisplayPriority = 3,
    DisplayedName = "$9615",
    Description = "$9616",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_ResearchShip_4f",
    RequiredResearch = "CorvetteTech",
    RequiredFleetSubSystems = "Research & CorvetteProduction & (!HeavyCorvette)",
    DisplayPriority = 4,
    DisplayedName = "$9617",
    Description = "$9618",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_ResearchShip_5f",
    RequiredResearch = "",
    RequiredFleetSubSystems = "Research & (!FighterModule)",
    DisplayPriority = 0,
    DisplayedName = "$9643",
    Description = "$9644",
  },
--{
  --Type = SubSystem,
  --ThingToBuild = "tai_r_multigun",
  --RequiredResearch = "CorvetteTech",
  --RequiredFleetSubSystems = "Research",
  --DisplayPriority = 5,
  --DisplayedName = "$9619",
  --Description = "$9620",
--},
  {
    Type = SubSystem,
    ThingToBuild = "Tai_RS_IonCannon",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 1,
    DisplayedName = "$9621",
    Description = "$9622",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_RS_Defense",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 2,
    DisplayedName = "$9623",
    Description = "$9624",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_RS_Capship",
    RequiredResearch = "ioncannonTech",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 3,
    DisplayedName = "$9625",
    Description = "$9626",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_RS_Missile",
    RequiredResearch = "taicapshipTech",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 4,
    DisplayedName = "$9627",
    Description = "$9628",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_RS_HeavyGun",
    RequiredResearch = "taicapshipTech",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 5,
    DisplayedName = "$9629",
    Description = "$9630",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_RS_SensorArray",
    RequiredResearch = "taicapshipTech",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 6,
    DisplayedName = "$9631",
    Description = "$9632",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_C_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 1,
    DisplayedName = "$9637",
    Description = "$9638",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_M_Hyperspace",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 1,
    DisplayedName = "$9637",
    Description = "$9638",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_C_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 2,
    DisplayedName = "$9639",
    Description = "$9640",
  },
  {
    Type = SubSystem,
    ThingToBuild = "Tai_MS_HyperspaceInhibitor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 2,
    DisplayedName = "$9639",
    Description = "$9640",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_Scout",
    RequiredResearch = "",
    RequiredShipSubSystems = "",
    DisplayPriority = 1,
    DisplayedName = "$9551",
    Description = "$9552",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_Interceptor",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterModule | KeyToAllShips",
    DisplayPriority = 2,
    DisplayedName = "$9553",
    Description = "$9554",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_AttackBomber",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FighterProduction | KeyToAllShips",
    DisplayPriority = 3,
    DisplayedName = "$9555",
    Description = "$9556",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_LightCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CorvetteProduction | KeyToAllShips",
    DisplayPriority = 11,
    DisplayedName = "$9561",
    Description = "$9562",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_HeavyCorvette",
    RequiredResearch = "",
    RequiredFleetSubSystems = "HeavyCorvette | KeyToAllShips",
    DisplayPriority = 12,
    DisplayedName = "$9563",
    Description = "$9564",
  },
--{ 
  --Type = Ship, 
  --ThingToBuild = "TAI_multiguncorvette",
  --RequiredResearch = "",
  --RequiredFleetSubSystems = "multigun",
  --DisplayPriority = 13,
  --DisplayedName = "$9565",
  --Description = "$9566"
--},
	{ 
	  Type = Ship, 
	  ThingToBuild = "TAI_repaircorvette",
	  RequiredResearch = "",
	  RequiredFleetSubSystems = "CorvetteProduction | KeyToAllShips",
	  DisplayPriority = 14,
	  DisplayedName = "$9567",
	  Description = "$9568"
	},
  { 
    Type = Ship, 
    ThingToBuild = "Tai_SalcapCorvette",
    RequiredResearch = "RSTech",
    RequiredFleetSubSystems = "CorvetteProduction | KeyToAllShips",
    DisplayPriority = 15,
    DisplayedName = "$9569",
    Description = "$9570"
  },
--{
  --Type = Ship,
  --ThingToBuild = "TAI_minelayercorvette",
  --RequiredResearch = "GraviticAttractionTech",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 16,
  --DisplayedName = "$9571",
  --Description = "$9572",
--},
  {
    Type = Ship,
    ThingToBuild = "Tai_SupportFrigate",
    RequiredResearch = "RSTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 21,
    DisplayedName = "$9575",
    Description = "$9576",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_StandardFrigate",
    RequiredResearch = "PlasmaBombsTech",
    RequiredFleetSubSystems = "RS | KeyToAllShips",
    DisplayPriority = 22,
    DisplayedName = "$9573",
    Description = "$9574",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_IonCannonFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "FrigateProduction | KeyToAllShips",
    DisplayPriority = 23,
    DisplayedName = "$9579",
    Description = "$9580",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_DefenseFrigate",
    RequiredResearch = "",
    RequiredFleetSubSystems = "defense | KeyToAllShips",
    DisplayPriority = 24,
    DisplayedName = "$9577",
    Description = "$9578",
  },
	{
	  Type = Ship,
	  ThingToBuild = "TAI_mothership",
	  RequiredResearch = "",
	  RequiredFleetSubSystems = "RS",
	  DisplayPriority = 31,
	  DisplayedName = "$9595",
	  Description = "$9596",
	},
  {
    Type = Ship,
    ThingToBuild = "Tai_Carrier",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 32,
    DisplayedName = "$9581",
    Description = "$9582",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_Shipyard",
    RequiredResearch = "",
    RequiredFleetSubSystems = "RS",
    DisplayPriority = 33,
    DisplayedName = "$9641",
    Description = "$9642",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_Destroyer",
    RequiredResearch = "",
    RequiredFleetSubSystems = "CapShipProduction",
    DisplayPriority = 34,
    DisplayedName = "$9583",
    Description = "$9584",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_MissileDestroyer",
    RequiredResearch = "",
    RequiredFleetSubSystems = "missile",
    DisplayPriority = 35,
    DisplayedName = "$9585",
    Description = "$9586",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_HeavyCruiser",
    RequiredResearch = "",
    RequiredFleetSubSystems = "heavygun",
    DisplayPriority = 36,
    DisplayedName = "$9587",
    Description = "$9588",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_BattleShip",
    RequiredResearch = "",
    RequiredFleetSubSystems = "heavygun",
    DisplayPriority = 37,
    DisplayedName = "$9607",
    Description = "$9608",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_HeavyDefender",
    RequiredResearch = "",
    RequiredFleetSubSystems = "defensefighters | KeyToAllShips",
    DisplayPriority = 4,
    DisplayedName = "$9557",
    Description = "$9558",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_DefenseFighter",
    RequiredResearch = "",
    RequiredFleetSubSystems = "defensefighters | KeyToAllShips",
    DisplayPriority = 5,
    DisplayedName = "$9559",
    Description = "$9560",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_researchship",
    RequiredResearch = "",
    RequiredFleetSubSystems = "! Research",
    DisplayPriority = 41,
    DisplayedName = "$9589",
    Description = "$9590",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_ResearchStation",
    RequiredResearch = "ResearchTech & CorvetteTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 42,
    DisplayedName = "$9609",
    Description = "$9610",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_SensorArray",
    RequiredResearch = "",
    RequiredFleetSubSystems = "sensorarray",
    DisplayPriority = 55,
    DisplayedName = "$9605",
    Description = "$9606",
  },
--{
  --Type = Ship,
  --ThingToBuild = "TAI_cloakgenerator",
  --RequiredResearch = "cloakgeneratorTech",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 43,
  --DisplayedName = "$9591",
  --Description = "$9592",
--},
--{
  --Type = Ship,
  --ThingToBuild = "TAI_gravwellgenerator",
  --RequiredResearch = "gravwellgeneratorTech",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 44,
  --DisplayedName = "$9593",
  --Description = "$9594",
--},
  {
    Type = Ship,
    ThingToBuild = "Tai_ResourceCollector",
    RequiredResearch = "",
    RequiredFleetSubSystems = "",
    DisplayPriority = 51,
    DisplayedName = "$9597",
    Description = "$9598",
  },
  {
    Type = Ship,
    ThingToBuild = "Tai_ResourceController",
    RequiredResearch = "RSTech",
    RequiredFleetSubSystems = "",
    DisplayPriority = 52,
    DisplayedName = "$9599",
    Description = "$9600",
  },
--{
  --Type = Ship,
  --ThingToBuild = "TAI_Probe",
  --RequiredResearch = "",
  --RequiredShipSubSystems = "",
  --DisplayPriority = 53,
  --DisplayedName = "$9601",
  --Description = "$9602",
--},
--{
  --Type = Ship,
  --ThingToBuild = "TAI_proximitysensor",
  --RequiredResearch = "ProbeProxSensorTech",
  --RequiredFleetSubSystems = "",
  --DisplayPriority = 54,
  --DisplayedName = "$9603",
  --Description = "$9604",
--},
}
