Icon_Speed = "data:ui/newui/research/icons/speed.tga"
Icon_Health = "data:ui/newui/research/icons/health.tga"
Icon_Tech = "data:ui/newui/research/icons/tech.tga"
Icon_Ability = "data:ui/newui/research/icons/ability.tga"
Icon_Build = "data:ui/newui/research/icons/build.tga"
Icon_Attack = "data:ui/newui/research/icons/attack.tga"
Icon_Cloak = "data:ui/newui/research/icons/cloak.tga"
Icon_Emp = "data:ui/newui/research/icons/Emp.tga"
Icon_Hyperspace = "data:ui/newui/research/icons/hyperspace.tga"
Icon_ping = "data:ui/newui/research/icons/ping.tga"
Icon_Repair = "data:ui/newui/research/icons/repair.tga"
Icon_RU = "data:ui/newui/research/icons/ru.tga"
Icon_shield = "data:ui/newui/research/icons/shield.tga"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research = {
  {
    Name = "Tai_AirWeaponUpgrade1",
    RequiredResearch = "CorvetteTech",
    RequiredSubSystems = "Research | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9708",
    DisplayPriority = 100,
    Description = "$9709",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9692",
  },
  {
    Name = "Tai_AirWeaponUpgrade2",
    RequiredResearch = "Tai_AirWeaponUpgrade1",
    RequiredSubSystems = "(Research & RS) | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9710",
    DisplayPriority = 100,
    Description = "$9711",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9693",
  },
  {
    Name = "Tai_AirWeaponUpgrade3",
    RequiredResearch = "Tai_AirWeaponUpgrade2",
    RequiredSubSystems = "(Research & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9712",
    DisplayPriority = 100,
    Description = "$9713",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9694",
  },
  {
    Name = "Tai_AirHealthUpgrade1",
    RequiredResearch = "CorvetteTech",
    RequiredSubSystems = "Research | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9714",
    DisplayPriority = 101,
    Description = "$9715",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9692",
  },
  {
    Name = "Tai_AirHealthUpgrade2",
    RequiredResearch = "Tai_AirHealthUpgrade1",
    RequiredSubSystems = "(Research & RS) | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9716",
    DisplayPriority = 101,
    Description = "$9717",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9693",
  },
  {
    Name = "Tai_AirHealthUpgrade3",
    RequiredResearch = "Tai_AirHealthUpgrade2",
    RequiredSubSystems = "(Research & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9718",
    DisplayPriority = 101,
    Description = "$9719",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Corvette",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9694",
  },
  {
    Name = "Tai_FrigateWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "RS | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9720",
    DisplayPriority = 200,
    Description = "$9721",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.12,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9695",
  },
  {
    Name = "Tai_FrigateWeaponUpgrade2",
    RequiredResearch = "Tai_FrigateWeaponUpgrade1",
    RequiredSubSystems = "RS | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9722",
    DisplayPriority = 200,
    Description = "$9723",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.24,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9696",
  },
  {
    Name = "Tai_FrigateWeaponUpgrade3",
    RequiredResearch = "Tai_FrigateWeaponUpgrade2",
    RequiredSubSystems = "(RS & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9724",
    DisplayPriority = 200,
    Description = "$9725",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.36,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9697",
  },
  {
    Name = "Tai_FrigateHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "RS | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9726",
    DisplayPriority = 201,
    Description = "$9727",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9695",
  },
  {
    Name = "Tai_FrigateHealthUpgrade2",
    RequiredResearch = "Tai_FrigateHealthUpgrade1",
    RequiredSubSystems = "RS | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9728",
    DisplayPriority = 201,
    Description = "$9729",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.4,
    Icon = Icon_Health,
    ShortDisplayedName = "$9696",
  },
  {
    Name = "Tai_FrigateHealthUpgrade3",
    RequiredResearch = "Tai_FrigateHealthUpgrade2",
    RequiredSubSystems = "(RS & CapShipProduction) | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9730",
    DisplayPriority = 201,
    Description = "$9731",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Frigate",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.6,
    Icon = Icon_Health,
    ShortDisplayedName = "$9697",
  },
  {
    Name = "Tai_CapitalWeaponUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9732",
    DisplayPriority = 300,
    Description = "$9733",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.1,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9698",
  },
  {
    Name = "Tai_CapitalWeaponUpgrade2",
    RequiredResearch = "Tai_CapitalWeaponUpgrade1",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9734",
    DisplayPriority = 300,
    Description = "$9735",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9699",
  },
  {
    Name = "Tai_CapitalWeaponUpgrade3",
    RequiredResearch = "Tai_CapitalWeaponUpgrade2",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9736",
    DisplayPriority = 300,
    Description = "$9737",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9700",
  },
  {
    Name = "Tai_CapitalHealthUpgrade1",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 500,
    Time = 80,
    DisplayedName = "$9738",
    DisplayPriority = 301,
    Description = "$9739",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9698",
  },
  {
    Name = "Tai_CapitalHealthUpgrade2",
    RequiredResearch = "Tai_CapitalHealthUpgrade1",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 750,
    Time = 100,
    DisplayedName = "$9740",
    DisplayPriority = 301,
    Description = "$9741",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9699",
  },
  {
    Name = "Tai_CapitalHealthUpgrade3",
    RequiredResearch = "Tai_CapitalHealthUpgrade2",
    RequiredSubSystems = "CapShipProduction | KeyToAllShips",
    Cost = 1000,
    Time = 120,
    DisplayedName = "$9742",
    DisplayPriority = 301,
    Description = "$9743",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Capital",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9700",
  },
  {
    Name = "Tai_FighterWeaponUpgrade1",
    RequiredResearch = "Tai_AirWeaponUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9708",
    DisplayPriority = 100,
    Description = "$9709",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9692",
  },
  {
    Name = "Tai_FighterWeaponUpgrade2",
    RequiredResearch = "Tai_AirWeaponUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9710",
    DisplayPriority = 100,
    Description = "$9711",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.3,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9693",
  },
  {
    Name = "Tai_FighterWeaponUpgrade3",
    RequiredResearch = "Tai_AirWeaponUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9712",
    DisplayPriority = 100,
    Description = "$9713",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "WEAPONDAMAGE",
    UpgradeValue = 1.4,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9694",
  },
  {
    Name = "Tai_FighterHealthUpgrade1",
    RequiredResearch = "Tai_AirHealthUpgrade1",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9714",
    DisplayPriority = 101,
    Description = "$9715",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.1,
    Icon = Icon_Health,
    ShortDisplayedName = "$9692",
  },
  {
    Name = "Tai_FighterHealthUpgrade2",
    RequiredResearch = "Tai_AirHealthUpgrade2",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9716",
    DisplayPriority = 101,
    Description = "$9717",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.2,
    Icon = Icon_Health,
    ShortDisplayedName = "$9693",
  },
  {
    Name = "Tai_FighterHealthUpgrade3",
    RequiredResearch = "Tai_AirHealthUpgrade3",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "$9718",
    DisplayPriority = 101,
    Description = "$9719",
    UpgradeType = Modifier,
    TargetType = Family,
    TargetName = "Fighter",
    UpgradeName = "MAXHEALTH",
    UpgradeValue = 1.3,
    Icon = Icon_Health,
    ShortDisplayedName = "$9694",
  },
  {
    Name = "ResearchTech",
    RequiredResearch = "",
    RequiredSubSystems = "Research",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tai_researchship",
  },
  {
    Name = "PlasmaBombsTech",
    RequiredResearch = "",
    RequiredSubSystems = "FighterProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tai_researchship",
  },
  {
    Name = "PlasmaBombsWeaponAccuracy",
    RequiredResearch = "PlasmaBombsTech",
    RequiredSubSystems = "",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    DisplayPriority = 1,
    UpgradeType = Modifier,
    TargetType = Ship,
    TargetName = "tai_attackbomber",
    UpgradeName = "WeaponAccuracy",
    UpgradeValue = 2,
    Icon = Icon_Attack,
    ShortDisplayedName = "$9052",
  },
  {
    Name = "CorvetteTech",
    RequiredResearch = "",
    RequiredSubSystems = "CorvetteProduction | KeyToAllShips",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "tai_researchship",
  },
  {
    Name = "RSTech",
    RequiredResearch = "",
    RequiredSubSystems = "RS",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "TAI_researchstation",
  },
  {
    Name = "ioncannonTech",
    RequiredResearch = "",
    RequiredSubSystems = "FrigateProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "TAI_researchstation",
  },
  {
    Name = "taicapshipTech",
    RequiredResearch = "",
    RequiredSubSystems = "CapShipProduction",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "TAI_researchstation",
  },
  {
    Name = "heavygunTech",
    RequiredResearch = "",
    RequiredSubSystems = "heavygun",
    Cost = 0,
    Time = 0,
    DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
    DisplayPriority = 1,
    Description = "",
    TargetName = "TAI_researchstation",
  },
  {
    Name = "FXP_Attack",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 1,
    Time = 100,
  },
  {
    Name = "FXP_BeenAttack",
    RequiredResearch = "",
    RequiredSubSystems = "",
    Cost = 1,
    Time = 100,
  },
--AI behaviour	
	{ 
		Name = "cpuplayers_defensive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_aggressive", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
	{ 
		Name = "cpuplayers_dynamic", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},
--AI no-rush	
	{ 
		Name = "cpuplayers_norushtime5", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime10", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},		
	{ 
		Name = "cpuplayers_norushtime15", 
		RequiredResearch = "", 
		RequiredSubSystems = "", 
		Cost = 1, 
		Time = 1, 
		DisplayedName = "", 
		DisplayPriority = 0,        
		Description = "",             
		TargetName = "",
	},	
--AI build speed	
	{ 
		Name =			"AllShipBuildSpeed",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.025,
	},	
	{ 
		Name =			"AllShipBuildSpeedHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.05,
	},	
	{ 
		Name =			"AllShipBuildSpeedExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
		UpgradeName =		"BUILDSPEED",
		UpgradeValue =		1.075,
	},
--AI resource rate	
	{ 
		Name =			"ResourceCollectionRateHard",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.04,
	},	
	{ 
		Name =			"ResourceCollectionRateExpert",
		RequiredResearch =	"",                       
		RequiredSubSystems =	"",                               
		Cost = 			1,
		Time = 			1,
		DisplayedName =		"",
		DisplayPriority =	0,                                                    
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName = "hgn_resourcecollector",
		UpgradeName =		"ResourceCollectionRate",
		UpgradeValue =		1.08,
	},			
}

dofilepath("data:scripts/races/AIscripts/AIReserch.lua")